### ISSUE TITLE
vebus: Add Multi uptime counter

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#1000]
The following dbus item will contain the Multi uptime counter `Devices/0/UpTime`.
This item will be updated every ~60 seconds.

Todo: 

- [x] Add to mk2-dbus
- [ ] Add to GUI
- [x] Add to VRM

**Comment by vejpasop** [comment]
Included in mk2-dbus V3.43

**Comment by mpvader** [comment]
@izak I see in vrmlogger that this logs the uptime for device 0 only; is that on purpose?

![image](https://user-images.githubusercontent.com/5200296/224572446-ede04f27-9ef6-4b5b-9464-8605de4f050e.png)

**Comment by izak** [comment]
@mpvader That was a mistake. I incorrectly assumed this path counts the uptime for the whole "cluster", also because the dbus path is specifically mentioned above. I cleared it up with Jos, I'll have to add 11 more attributes!

**Comment by izak** [comment]
After quick discussion with Jos, no need to add anything to the GUI. This is for debugging purposes, so we got everything we need already in v3.00~24.

Closing.
