### ISSUE TITLE
How to upgrade from 2.89 to 2.9x ?

### ISSUE THREAD

**Issue by jjtoard** [victronenergy/venus#1004]
How to upgrade from 2.89 to 2.9x ?
I don't get the option to upgrade even that the 2.9x version is available for a while.

**Comment by mpvader** [comment]
Hi @jjtoard , thats best asked, or first searched for, on https://community.victronenergy.com/ and then the Mods section.

this issue tracker is for development, not support. Success!

**Comment by jjtoard** [comment]
ok thanks
