### ISSUE TITLE
vebus:  Revert ext-control status and move to systemcalc

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#1008]
Generating the ext control status (0xFC) in mk2dbus based on BOL frame transmission breaks functionality in certain modbus scenarios.
Instead we move it to systemcalc.

Todo:

- [x] revert changes to mk2dbus.
- [x] Add to systemcalc

**Comment by izak** [comment]
Released in Venus 2.93 & Venus 3.00~15. Closing.
