### ISSUE TITLE
Beaglebone Black - Venus OS - 7Inch Touch Screen Monitor

### ISSUE THREAD

**Issue by Tomi87** [victronenergy/venus#1010]
Hello, I would like to ask for help with the configuration of a 7-inch touch monitor on a Beaglebone Black Venus OS via HDMI if possible...

https://www.aliexpress.com/item/1005002537702672.html?spm=a2g0o.order_list.order_list_main.5.265e18022z1gnZ

**Comment by mkrenzke** [comment]
There is a "Modifications" section in the [Community](https://community.victronenergy.com/spaces/31/index.html), that's the right place to ask. Not here please.
