### ISSUE TITLE
Generator start/stop: generate alarm when generator is not in autostart mode

### ISSUE THREAD

**Issue by jepefe** [victronenergy/venus#1016]
- [x] Add alarm to generator start/stop (jpe)
- [x] Add alarm to Venus gui (jpe)

To prevent people from disabling autostart and then forgetting to enable it. 

Alarm is optional and can be enabled from generator start/stop settings.
Alarm should wait 5/10 minutes before triggering, this lets the operator some time to do whatever he has to do.

**Comment by mpvader** [comment]
@jepefe & @izak how about making this part of the generator start stop changes now being worked on?

and then also include a resettable downwards counting timer?

i’ve been thinking about that, and only sensible solution is downward counting service timer.

not upward counting.

**Comment by kwindrem** [comment]
Interestingly, I added a service timer as part of GuiMods. Might check that out.

My counter actually counts up but it's displayed as time remaining until next service. It was easier to handle it as an up count especially when changing the service interval.

**Comment by mpvader** [comment]
Moved; too late for v3.00

**Comment by jepefe** [comment]
Finished.
gui: [feat_service_interval](https://github.com/victronenergy/gui/tree/feat_service_interval/qml) 
dbus_generator: [v1.6.2](https://github.com/victronenergy/dbus_generator/releases/tag/v1.6.2)
Ready to be added to the 3.10 ToDo list once it is open.
![Screenshot from 2023-05-26 01-55-20](https://github.com/victronenergy/venus/assets/6424631/ff5dad1f-98f9-4d92-a19c-ef5cb39b9cfa)
![Screenshot from 2023-05-26 01-55-12](https://github.com/victronenergy/venus/assets/6424631/d8f6c75a-6d14-4073-81f8-5941b1c57d6a)
![Screenshot from 2023-05-26 01-55-40](https://github.com/victronenergy/venus/assets/6424631/c2d71b6a-4211-437e-9fe1-bc434598f2aa)

**Comment by mpvader** [comment]
can be closed @jepefe ? It works well, I used it :)

**Comment by jepefe** [comment]
Yes, can be closed. Thanks for testing it :)
