### ISSUE TITLE
dbus_modbustcp: python example no longer works

### ISSUE THREAD

**Issue by new-gen23** [victronenergy/venus#1035]
https://github.com/riptideio/pymodbus/issues/1126
`Pymodbus.client.sync` no longer exist it is now Pymodbus.client.`

However, changing this in ModbusCli.py (line 7) to Pymodbus.client, this leads to the following problem:
`Traceback (most recent call last):
  File "/home/newgen/victron/dbus_modbustcp/examples/ModbusCli.py", line 21, in <module>
    client = ModbusTcpClient(host=args.dest[0], port=args.port)
TypeError: 'NoneType' object is not subscriptable`

Any ideas?

**Comment by izak** [comment]
`TypeError: 'NoneType' object is not subscriptable` happens because args.dest is None (instead of a list, since `nargs=1` was passed), which means you called the command without the `--dest` argument. So likely operator error.

Tested with python 3.8.10 and pymodbus 3.6.9.
