### ISSUE TITLE
systemcalc: Add summary path for inverter/vebus DC current

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#1039]
At the moment the GUI (and VRM?) gets the VebusService from systemcalc, and then queries it directly to find /Dc/0/Power, to animate that line on the Overview.

This does not work for Multi-RS, because the present method assumes the inverter is a VE.Bus inverter. If `com.victronenergy.system/VebusService` is not defined, it has no other way of knowing what service it should get this information from.

That technically means it never worked correctly for  Phoenix inverter either? **This needs to be confirmed**.

What we need is a summary path showing the inverter/inverter-charger DC current and power, so that there is a single place for a user interface to get this information.

Probably something like `/Dc/Inverter/{Service,Power,Current}`

TODO
- [x] Check if issue also applies Phoenix inverter (it does!)
- [x] GUI changes?
- [x] Document in dbus documentation, and in user interface google doc
- [x] modbus-tcp ?
- [ ] VRM ?

**Comment by mpvader** [comment]
why doesn't that work for the RS?

**Comment by izak** [comment]
The balls-view now animates the DC to Multi-RS (and also other inverters including Inverter RS).

![Selection_040](https://github.com/victronenergy/venus/assets/851549/a44ff27b-746f-4c5f-8ec0-c469d66c72f2)

**Comment by izak** [comment]
After a short discussion with Alex, no need to log this to VRM.
