### ISSUE TITLE
turn off AC & Grid

### ISSUE THREAD

**Issue by dennis230694** [victronenergy/venus#1045]
Hello, i'm working on a DC System in my Solarmotorboat. i don't have any AC Devices, just a Victron Smartsolar MPPT Controller and a 500a Smartshunt. i don't want to see the AC Controller on my Dashboard. is it Possible to turn off all AC and Grid devices?

**Comment by mpvader** [comment]
Hi @dennis230694 ; not in the current implementation, in the gui overview page, ie the one with the boxes and lines connecting the boxes, it will always show the multi.

We're working on a completely new version where this is fixed.
