### ISSUE TITLE
Setting digital input 1 to Touch input control results in non-existing digital input 0 to appear

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1050]
Seen by myself on my own Cerbo GX while running v3.00~26. Restarting the gui makes it go away again.

Setting any of the other digital inputs to `Touch input control` does not cause this to happen.

![image](https://user-images.githubusercontent.com/5200296/227744538-701e566c-2a04-4fc4-833d-290e77adbb03.png)

**Comment by izak** [comment]
Initial assessment:

This is unrelated to dbus-digitalinputs. It's an issue in `VeQItemTableModel` (most likely). It is also not limited to Digital inputs. It also happens if you toggle an input backwards and forwards between any two types or Disabled.
