### ISSUE TITLE
dbus-modbus-client: Add Comap support

### ISSUE THREAD

**Issue by dirkjanfaber** [victronenergy/venus#1055]
Add support for the Comap InteliLite 4 AMF 25 (and possibly others). 

On the Comap side, first the MODBUS server needs to be enabled (via the _Setpoints -> CM-Ethernet -> MODBUS settings_)

![image](https://user-images.githubusercontent.com/3098947/229060988-6066465c-7b24-4e85-a4c4-a78e5981aa05.png)

TODO
- [x] Add comap driver to dbus-modbus-client
- [x] Log relevant new values to VRM
- [x] modbustcp for some new paths
- [x] dbus-generator-starter
- [x] Adapt GUI pages currently used for FischerPanda to be more generic and reusable for ComAp

**Comment by izak** [comment]
Dbus paths for comap:

Paths common to other .genset services
```
/NrOfPhases    ->  1, 2 or 3 for single-phase, split-phase and 3-phase respectively
/Ac/Power      -> Total AC power rounded to the nearest Kilowatt (Comap controller supports no more accuracy)
/Ac/L1/Power   -> Per phase power values to the nearest Kilowatt
/Ac/L2/Power
/Ac/L3/Power
/Ac/Frequency   -> AC Frequency, to 0.1Hz
/Ac/L1/Voltage  -> Per phase voltages to the nearest 1V
/Ac/L2/Voltage
/Ac/L3/Voltage
/Ac/L1/Current  -> Per phase current to the nearest 1A
/Ac/L2/Current
/Ac/L3/Current
/Ac/Energy/Forward -> Produced energy in kWh
```

Paths specific to comap, some in common with FischerPanda:
```
/Engine/Speed                -> Engine speed in RPM 
/Engine/CoolantTemperature   -> Engine coolant temperature
/Engine/OilPressure          -> Engine oil pressure
/Engine/Load                 -> Engine load as a percentage
/Engine/OperatingHours       -> Operating hours, to the nearest 0.1 hours.
/StarterVoltage              -> Voltage of starter battery
/FuelLevel                   -> Fuel level as a percentage; on HG195 trailer this always showed invalid
/StatusCode                  -> Enum, re-uses and maps the one previously made for FischerPanda.
```

Paths NOT implemented
```
/ErrorCode    -> FischerPanda has 166 error codes. Comap has no such register at all.
```

## Status code

Value | Meaning
-----|-----
0  | Stopped / Ready
1  | Self-test
2  | Preheat (glow-plugs on Diesel engine)
3  | Starting
8  | Running
9  | Stopping
10 | Error (not ready to start, or controller is in Emergency Manual mode)

**Comment by mpvader** [comment]
Hey @izak , nice thanks. Do you still have the service interval (hours or minutes) on your radar?

**Comment by izak** [comment]
Minor corrections needed:

Engine OperatingHours should be in seconds (even though the name says HOURS).

Oil Pressure is in Bar from controller, but we probably want to use kPa. Need to change multiplier.

**Comment by Pye-lmk-power** [comment]
Are you working with the DSE8610 or DEif AGC150?

**Comment by philipptrenz** [comment]
Hi @Pye-lmk-power, these GitHub issues are primarily to organize development work. A better place for you questions is here: https://community.victronenergy.com

In short: We already support the DSE 8610 MKII controller. Support for DSE 8610 can be added, if someone provides us with access to such a system for testing.  Regarding DEIF AGC150: I can confirm, that we're currently looking into that.
