### ISSUE TITLE
multiple batteries as separate VRM Instance

### ISSUE THREAD

**Issue by Micha854** [victronenergy/venus#1059]
Hallo!

we have 2 batteries

1. pylontech
2 DIY storage

both are connected via CAN and are also displayed in venus

Only one battery monitor with instance 512 can be found in the vrm portal

it's either the pylontech or the DIY store. depending on which one was last read!

Is there a possibility that both batteries in the device list get a separate ID because this is the only way I can evaluate both batteries in the extended statistics

**Comment by mpvader** [comment]
Hi, no that is not possible. Venus OS supports only one CanBUS BMS
