### ISSUE TITLE
Daly BMS per CAN cellVoltage min > max

### ISSUE THREAD

**Issue by Micha854** [victronenergy/venus#1060]
Hello, I have connected a Daly BMS with CAN and here I observe "MinCellVoltage" > "MaxCellVoltage"

![alt text](https://community.victronenergy.com/storage/attachments/51925-min-max.png)

The Daly displays the values correctly. Is there a problem with Victron here?

What can I do?

**Comment by mpvader** [comment]
Hi @Micha854 , we don't have native support for Daly BMS.

Best search for an answer on this forum, or ask the question if it hasn't been answered before.
https://community.victronenergy.com/spaces/31/mods.html

Success!
