### ISSUE TITLE
bug in dbus_generator.py

### ISSUE THREAD

**Issue by kwindrem** [victronenergy/venus#1064]
dbus_generator.py sets up the following:

		commondbustree = {
			'com.victronenergy.settings': {
				'/Settings/System/TimeZone': dummy,
				'/Settings/System/AcInput1': dummy,
				'/Settings/System/AcInput2': dummy,
				'/Settings/Relay/Polarity': dummy
				},

/Settings/System/AcInput1 and /Settings/System/AcInput2 do not exist, however
/Settings/SystemSetup/AcInput1 and /Settings/SystemSetup/AcInput2 do exist

I'm looking at v3.00~32 but may have been a problem for some time.

Plus it does not appear they are used anywhere. Checked all .py in dbus-generator-starter

**Comment by jepefe** [comment]
This has been corrected already on latest release. Issue closed
