### ISSUE TITLE
ESS: add option to use battery power only for critical loads

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1066]
This is (for example) for a system with a grid meter, quite significant non-critical loads, dc-coupled solar, and feed-back to the grid not allowed and disabled.

Then, what they want is to use the solar power both for critical and non-critical loads. But once the sun is no longer sufficient to cater for all the loads, use the battery power only for the critical loads. To keep the battery power available for a grid failure (loadshedding).

**Comment by warwickchapman** [comment]
See https://community.victronenergy.com/idea/22664/idea-battery-discharge-current-limit.html

The requested functionality will allow battery banks to be sized to get critical loads through the night without battery being discharged into the non-essentials.

That would be a very big win for a lot of us in areas with frequent grid outages.

Then, to make others happy per above post - perhaps the “Limit battery discharge” options can be:

- Critical Loads (Dynamically calibrated to match current critical load value)

- Specfied Power Value (enter in W)

**Comment by warwickchapman** [comment]
This feature is being request quite vigorously by an increasingly discerning userbase.  I am being asked about it on a weekly basis now.  I understand it is not terribly complex to implement and would like to motivate for it to be given priority.

**Comment by izak** [comment]
Open to alternative labeling.

Item is not shown if Grid Metering is not set to "External meter", and if "AC out in use" is not enabled. It would make no sense.

![Selection_473](https://github.com/victronenergy/venus/assets/851549/f6d80644-3f20-49fd-a061-1e1e0ee85527)
![Selection_474](https://github.com/victronenergy/venus/assets/851549/b9075a20-0593-4a21-97ec-e85d01b57e4f)

**Comment by warwickchapman** [comment]
This is becoming important for Multi RS.
