### ISSUE TITLE
generator start/stop small improvements

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1067]
- [x] Make the new warm-up and cooldown work for both ACin-1 and ACin-2; instead of, as its now, require the generator to be wired to ACin-1
- [x] Look into hiding or disabling the warm-up, cooldown as well as `stop generator when ...` settings when the vebus firmware version doesn't support it yet.
- [ ] Check if having user select ACin1/ACin2 yet another time in the gen start/stop menus is really the best option; or can the user select generator? Or do something else?
- [x] Add states to VRM Portal Dashboard, see also below comment.
- [x] Add Warm-up and Cool-down enums to VRM dataAttribute Generator state, `gaS`, 1166. see also below comment.

**Comment by mpvader** [comment]
Comment from Kevin in ~37 thread:

> The generator warm-up and cool-down options do not appear unless one of the system AC inputs is set to generator. All other generator settings appear even of no generator AC input is defined.

**Comment by mpvader** [comment]
Hey @izak , has the VRM Portal devteam already been told to add the warm-up and cooldown state to the VRM Portal?

See this screenshot, and also see the `Stopped` in the second screenshot, that is also wrong I'd think.

![image](https://user-images.githubusercontent.com/5200296/235324616-32ca6173-2d8d-4746-9909-8695e56b4859.png)

![image](https://user-images.githubusercontent.com/5200296/235324660-8f170330-ad83-4e60-9ca5-effdc1ea2906.png)

**Comment by mpvader** [comment]
dataAttribute gaS (1166) is missing the new enums:

![image](https://user-images.githubusercontent.com/5200296/235325844-167655f6-a367-4dec-8f51-776081d9f48e.png)

**Comment by kwindrem** [comment]
I noticed /Ac/Control/IgnoreAcIn1 dbus parameter can not be read.

Also a question: can there be a conflict between this and the ignore AC in mechanism set via assistants in the Multi?

**Comment by mpvader** [comment]
@vejpasop pls check Kevins question. Also I asked Izak to make sure the four new paths are documented on the public dbus wiki page. Depending on the answer to this: pls include info about this there as well. Also that they can’t be read. Which for me is all fine, as long as it works for us (whicj it does) and pecularities are documntd

**Comment by vejpasop** [comment]
The `/Ac/Control/IgnoreAcIn1` dbus item is only available with Multi firmware version 502 and up. This path is there to instruct the Multi to ignore the AC input. The actual ignore status is available on `Ac/State/IgnoreAcIn1` and is affected by ignore AC in control from the following "modules"

- dbus item `/Ac/Control/IgnoreAcIn1`
- Grid code 
- BMS
- The ignore AC in mechanism via the assistants  

So all of the above can control the ignore AC in. These are ORed. So if there is at least one "module" telling to ignore. The AC input is ignored.

**Comment by kwindrem** [comment]
This sounds perfect. My concern is clearing /Ac/Control/IgnoreAcIn1 would upset the other ignores and allow AC in to pass. That won't happen based on the above description.

As mpvader says ot being able to read /Ac/Control/IgnoreAcIn1 is OK as long as it's documented. It's just odd to see a dbus parameter not show the current state in dbus-spy. I'm also guessing a test for valid would fail but haven't tried it.

Thanks to all that have worked on warm-up and cool-down.

**Comment by mpvader** [comment]
@izak / @jepefe pls check all above, and let me know what (if anything) should be part of v3.00

One reason to make some of it part of above might change setting names or paths, and then if we don’t change it now, we’ll have to migrate it later.

**Comment by mpvader** [comment]
All that really needed doing is done.

I’ve moved this to v3.10 now since there is one more open item on the todo. Which we might decide to not do but thats for later.

for now, this is good enough.

**Comment by mpvader** [comment]
closing; its good enough.
