### ISSUE TITLE
Collect informations from Hybrid-Inverter

### ISSUE THREAD

**Issue by Chris87-ux** [victronenergy/venus#1068]
I have a SolarEdge (SE10k-RWS) on my installation. The Inverter has its own Batterie, unfortunately the shown PV-Power is not the power comming from the Pannels, it is the converted power, so all power which is going to the Batterie is not displayed.

It would be great to display also the Batterie-power and SOC.

Additional to this the charge/dischanrg does sometimes interfare each other, so the charge and discharge could be also controlled by Victron.
[Power-Control-Open-Protocol-for-SolarEdge-Inverters.pdf](https://github.com/victronenergy/venus/files/11377305/Power-Control-Open-Protocol-for-SolarEdge-Inverters.pdf)

Br/ Chris

**Comment by mpvader** [comment]
Hi Chris. Thanks. That would be nice to have. Its on our long term list. Matthijs
