### ISSUE TITLE
Systemcalc: system state is External control while inverting

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1073]
It should say inverting. Or not?

and was this behaviour changed in v3.00? Since then this is a v3.00 issue

https://vrm.victronenergy.com/installation/183123/diagnostics

![2B42AB5F-64B7-439B-9CE7-92307FDD2B5D](https://user-images.githubusercontent.com/5200296/236623636-be08b2ad-e109-4b32-8132-a1fd6d9534ef.png)
![4BEC0AFB-4A6C-4709-BE1B-B38DC952A030](https://user-images.githubusercontent.com/5200296/236623638-f703909f-1b6e-44b5-bb8e-0d8a3926ca29.png)
![F81846A8-11F5-491F-856A-55266D2BE0DD](https://user-images.githubusercontent.com/5200296/236623639-d041a9f6-cc85-497a-946d-f3bb1c2e9b18.png)

**Comment by izak** [comment]
Found it. In commit [3f39582d][1], 2.93, when we moved this state from mk2-dbus to systemcalc. Not really wrong (it is in external control state), but more important to see that it is inverting. So I'll prioritise that state.

[1]: https://github.com/victronenergy/dbus-systemcalc-py/commit/3f39582d79cc04d36332ac4cf3279361049b51d5
