### ISSUE TITLE
generator start-stop: Add service interval feature

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#1086]
The idea is that there will be a count-down timer that counts down (in hours) towards the next oil-change/service.

When the counter reaches zero, the user will be notified. Might be as simple as raising a warning (not alarm, alarm means it stopped working).

Resetting the service interval restarts the count-down.

TODO
- [ ] Implement countdown timer
- [ ] Add warning to GUI
- [ ] Log to VRM
- [ ] Modbus TCP register

**Comment by jepefe** [comment]
Hi @izak 

Duplicated?
https://github.com/victronenergy/venus/issues/1080

**Comment by izak** [comment]
Indeed. Duplicate.
