### ISSUE TITLE
beaglebone enhanced: recursive lock detected during reboot

### ISSUE THREAD

**Issue by jhofstee** [victronenergy/venus#109]
the device reboots fine though....

Sending all processes the TERM signal...
Sending all processes the KILL signal...
Unmounting remote filesystems...
Deactivating swap...
Unmounting local filesystems...
[  339.128515] EXT4-fs (mmcblk1p3): re-mounted. Opts: data=ordered
Rebooting... [  341.319268] musb-hdrc musb-hdrc.1.auto: remove, state 1
[  341.325367] usb usb1: USB disconnect, device number 1
[  341.330748] usb 1-1: USB disconnect, device number 2
[  341.335986] usb 1-1.4: USB disconnect, device number 3
[  341.350440] RTL871X: rtw_ndev_uninit(wlan0)
[  341.376227] RTL871X: rtw_ndev_uninit(wlan1)
[  341.383930]
[  341.385507] =============================================
[  341.391165] [ INFO: possible recursive locking detected ]
[  341.396828] 4.1.36-venus #1 Tainted: G           O
[  341.402121] ---------------------------------------------
[  341.407779] reboot/4000 is trying to acquire lock:
[  341.412801]  (&(plock)->rlock){+.....}, at: [<bf0fc584>] rtw_free_xmitframe_queue+0x18/0x58 [8723bu]
[  341.422959]
[  341.422959] but task is already holding lock:
[  341.429075]  (&(plock)->rlock){+.....}, at: [<bf0f7f38>] rtw_free_stainfo+0x48/0x364 [8723bu]
[  341.438283]
[  341.438283] other info that might help us debug this:
[  341.445128]  Possible unsafe locking scenario:
[  341.445128]
[  341.451334]        CPU0
[  341.453893]        ----
[  341.456451]   lock(&(plock)->rlock);
[  341.460204]   lock(&(plock)->rlock);
[  341.463956]
[  341.463956]  *** DEADLOCK ***
[  341.463956]
[  341.470162]  May be due to missing lock nesting notation
[  341.470162]
[  341.477280] 9 locks held by reboot/4000:
[  341.481388]  #0:  (reboot_mutex){+.+.+.}, at: [<c00513e8>] SyS_reboot+0x90/0x1d8
[  341.489182]  #1:  (&dev->mutex){......}, at: [<c02a813c>] device_shutdown+0x84/0x1ec
[  341.497334]  #2:  (&dev->mutex){......}, at: [<c02a814c>] device_shutdown+0x94/0x1ec
[  341.505478]  #3:  (usb_bus_list_lock){+.+.+.}, at: [<c0303e08>] usb_remove_hcd+0x98/0x1fc
[  341.514086]  #4:  (&dev->mutex){......}, at: [<c02feaac>] usb_disconnect+0x40/0x280
[  341.522139]  #5:  (&dev->mutex){......}, at: [<c02feaac>] usb_disconnect+0x40/0x280
[  341.530191]  #6:  (&dev->mutex){......}, at: [<c02feaac>] usb_disconnect+0x40/0x280
[  341.538243]  #7:  (&dev->mutex){......}, at: [<c02a9bbc>] device_release_driver+0x18/0x2c
[  341.546845]  #8:  (&(plock)->rlock){+.....}, at: [<bf0f7f38>] rtw_free_stainfo+0x48/0x364 [8723bu]
[  341.556452]
[  341.556452] stack backtrace:
[  341.561026] CPU: 0 PID: 4000 Comm: reboot Tainted: G           O    4.1.36-venus #1
[  341.569053] Hardware name: Generic AM33XX (Flattened Device Tree)
[  341.575468] [<c0014804>] (unwind_backtrace) from [<c0012954>] (show_stack+0x10/0x14)
[  341.583598] [<c0012954>] (show_stack) from [<c0067fe0>] (__lock_acquire+0x1454/0x1da0)
[  341.591905] [<c0067fe0>] (__lock_acquire) from [<c006922c>] (lock_acquire+0xac/0x12c)
[  341.600130] [<c006922c>] (lock_acquire) from [<c04c3694>] (_raw_spin_lock_bh+0x44/0x54)
[  341.608713] [<c04c3694>] (_raw_spin_lock_bh) from [<bf0fc584>] (rtw_free_xmitframe_queue+0x18/0x58 [8723bu])
[  341.619336] [<bf0fc584>] (rtw_free_xmitframe_queue [8723bu]) from [<bf0f7f44>] (rtw_free_stainfo+0x54/0x364 [8723bu])
[  341.630763] [<bf0f7f44>] (rtw_free_stainfo [8723bu]) from [<bf0faab0>] (free_mlme_ap_info+0x3c/0x48 [8723bu])
[  341.641460] [<bf0faab0>] (free_mlme_ap_info [8723bu]) from [<bf10ba6c>] (rtw_usb_if1_deinit+0x34/0xa4 [8723bu])
[  341.652342] [<bf10ba6c>] (rtw_usb_if1_deinit [8723bu]) from [<bf10bbe0>] (rtw_dev_remove+0x74/0x88 [8723bu])
[  341.662804] [<bf10bbe0>] (rtw_dev_remove [8723bu]) from [<c030957c>] (usb_unbind_interface+0x7c/0x290)
[  341.672574] [<c030957c>] (usb_unbind_interface) from [<c02a9b30>] (__device_release_driver+0x70/0xe4)
[  341.682249] [<c02a9b30>] (__device_release_driver) from [<c02a9bc4>] (device_release_driver+0x20/0x2c)
[  341.692013] [<c02a9bc4>] (device_release_driver) from [<c02a961c>] (bus_remove_device+0xdc/0x108)
[  341.701322] [<c02a961c>] (bus_remove_device) from [<c02a69a0>] (device_del+0x110/0x210)
[  341.709724] [<c02a69a0>] (device_del) from [<c030716c>] (usb_disable_device+0xa0/0x1e8)
[  341.718122] [<c030716c>] (usb_disable_device) from [<c02feae0>] (usb_disconnect+0x74/0x280)
[  341.726884] [<c02feae0>] (usb_disconnect) from [<c02fec7c>] (usb_disconnect+0x210/0x280)
[  341.739355] musb-hdrc musb-hdrc.1.auto: USB bus 1 deregistered
[  341.746076] udc musb-hdrc.0.auto: releasing 'musb-hdrc.0.auto'
[  341.753127] reboot: Restarting system

**Comment by mpvader** [comment]
Yes its a known issue:

https://github.com/victronenergy/meta-victronenergy/commit/ea27495e0d4178fe4189f0fcb59914123b65a730

Not something I want to spend any of our on for fixing it.
