### ISSUE TITLE
v3.10: grid meter data missing in device list summary

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1096]
And maybe other places too.

see first two answers here:

https://community.victronenergy.com/questions/210133/venus-os-v3102-available-for-testing.html

**Comment by mpvader** [comment]
Fixed per Venus OS v3.10~4

**Comment by mpvader** [comment]
Looks like its not (fully) solved?

see the empty line with EM24:

![IMG_9207](https://github.com/victronenergy/venus/assets/5200296/777b3266-ab32-44a6-a748-5fb52b94d9c3)

**Comment by izak** [comment]
The fix isn't in v3.10~7. Needs gui v5.6.4, but we only have v5.6.3.

**Comment by mpvader** [comment]
thanks; that will explained it. v3.10~8 is building now.
