### ISSUE TITLE
beaglebone enhanced: interrupt wind (can1)

### ISSUE THREAD

**Issue by jhofstee** [victronenergy/venus#110]
Not really a storm, but does consume 15%-20% cpu.
Nothing is connected to the CAN-bus

root@beaglebone:/log# uname -a
Linux beaglebone 4.1.36-venus #1 Mon Dec 12 11:04:06 UTC 2016 armv7l GNU/Linux
root@beaglebone:/log# cat /proc/interrupts
           CPU0
 16:     125781      INTC  68 Level     gp_timer
 19:       2998      INTC  12 Level     edma
 21:         78      INTC  14 Level     edma_error
 29:          0  44e07000.gpio   6 Edge      48060000.mmc cd
154:      19523      INTC  72 Level     OMAP UART0
156:          0      INTC  45 Level     OMAP UART4
157:       8053      INTC  46 Level     OMAP UART5
158:         99      INTC  70 Level     44e0b000.i2c
159:         37      INTC  71 Level     4802a000.i2c
160:         13      INTC  64 Level     mmc0
161:      10579      INTC  28 Level     mmc1
164:    **9213044**      INTC  55 Level     can1
174:      13906      INTC  41 Level     4a100000.ethernet
175:       5115      INTC  42 Level     4a100000.ethernet
177:          0      INTC  16 Level     TI-am335x-adc
180:          0      INTC 111 Level     48310000.rng
181:          0      INTC  18 Level     musb-hdrc.0.auto
182:       3705      INTC  19 Level     musb-hdrc.1.auto
Err:          0

it isn't easily reproducable

**Comment by mpvader** [comment]
never seen again
