### ISSUE TITLE
Multi RS: Firmware update breaks VRM data logging until reboot

### ISSUE THREAD

**Issue by jepefe** [victronenergy/venus#1105]
After updating the firmware of the Multi RS its related values on VRM are not updated anymore until Venus is restarted.

Happens every time so it is easy to reproduce by just updating the product firmware.

**Comment by jhofstee** [comment]
Unrelated, but we should check VE.Can for the same issue, it is on my long todo.. So I wouldn't mind if somebody else checks this.

**Comment by mpvader** [comment]
I don't understand what you mean @jhofstee , the Multi RS can only be connected over VE.Can.

**Comment by martinbosma** [comment]
@jhofstee You mean like disconnecting a VE.Can device/service when we see bootloader messages?

**Comment by jhofstee** [comment]
oh and that might actually be related, but for sure we should look at VE.Can for this issue and I never updated a Multi RS.

**Comment by izak** [comment]
This is fixed in Venus v3.10~23. It was related to the race condition that causes energy calculation to be lost if the AC input type is not known at the instant the dbus service comes up.

https://github.com/victronenergy/venus/issues/1126
