### ISSUE TITLE
v3.01: update translations

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1107]
In v3.00, the translations were missing.

**Comment by dirkjanfaber** [comment]
All translations have been done. Created the https://github.com/victronenergy/gui/compare/master...faberd/translations branch, containing the updated terms and translations.

**Comment by dirkjanfaber** [comment]
One more remark. There is a difference with the previous update of the translations, where only the `.po` files where updated. As both the `.po` and `.qm` files contain the translations, both have been updated in my commit. The `.qm` files however have been generated from the `.po` files. As that is also done when building the gui, I believe that the `.qm` files should be either removed from the repository all together or they should be kept up to date (which is what I've done in the commit).

**Comment by jhofstee** [comment]
no, the qm files should be updated from the po files, the po files are the temporarily ones, just to be compatible with poeditor. The*.po files can be deleted though...

**Comment by jhofstee** [comment]
This is also in v3.01 now.
