### ISSUE TITLE
PV Inverters Log MPPT tracker state (MPP vs limited) to VRM?

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1114]
having that will significantly improve the solar yield forecast.

Right now its not in vrmlogger; and also doesn't seem to be on the dbus, see https://github.com/victronenergy/venus/wiki/dbus.

Is that because it doesn't exist? Or is it in the sunspec, and is it something we could add?

```
'com.victronenergy.pvinverter': {
	'/ProductId': {'code': 'pM', 'whenToLog': 'configChange'},
	'/FroniusDeviceType': {'code': 'pF', 'whenToLog': 'configChange'},
	'/FirmwareVersion': {'code': 'pV', 'whenToLog': 'configChange'},
	'/DataManagerVersion': {'code': 'pdV', 'whenToLog': 'configChange'},
	'/Position': {'code': 'pL', 'whenToLog': 'configChange'},
	'/Serial': {'code': 'ps', 'whenToLog': 'configChange'},
	'/CustomName': {'code': 'pcn', 'whenToLog': 'configChange'},
	'/Ac/L1/Voltage': {'code': 'pV1', 'whenToLog': 'onIntervalAlways', 'precision': 1},
	'/Ac/L1/Current': {'code': 'pI1', 'whenToLog': 'onIntervalAlways', 'precision': 2},
	'/Ac/L1/Power': {'code': 'pP1', 'whenToLog': 'onIntervalAlways', 'precision': 0},
	'/Ac/L1/Energy/Forward': {'code': 'pE1', 'whenToLog': 'onIntervalAlways', 'precision': 2},
	'/Ac/L2/Voltage': {'code': 'pV2', 'whenToLog': 'onIntervalAlways', 'precision': 1},
	'/Ac/L2/Current': {'code': 'pI2', 'whenToLog': 'onIntervalAlways', 'precision': 2},
	'/Ac/L2/Power': {'code': 'pP2', 'whenToLog': 'onIntervalAlways', 'precision': 0},
	'/Ac/L2/Energy/Forward': {'code': 'pE2', 'whenToLog': 'onIntervalAlways', 'precision': 2},
	'/Ac/L3/Voltage': {'code': 'pV3', 'whenToLog': 'onIntervalAlways', 'precision': 1},
	'/Ac/L3/Current': {'code': 'pI3', 'whenToLog': 'onIntervalAlways', 'precision': 2},
	'/Ac/L3/Power': {'code': 'pP3', 'whenToLog': 'onIntervalAlways', 'precision': 0},
	'/Ac/L3/Energy/Forward': {'code': 'pE3', 'whenToLog': 'onIntervalAlways', 'precision': 2},
	'/Ac/Energy/Forward': {'code': 'pf', 'whenToLog': 'onIntervalAlways', 'precision': 2},
	'/StatusCode': {'code': 'pS', 'whenToLog': 'onIntervalAlways'},
	'/ErrorCode': {'code': 'pE', 'whenToLog': 'onIntervalAlwaysAndOnEvent'},
	'/Ac/PowerLimit': {'code': 'pLi', 'whenToLog': 'onIntervalAlways'}
},

```

**Comment by mpvader** [comment]
hm actually there is something available, its in the state:

> 2023-05-31 08:49:11	PV Inverter	20	pS (246)	Status	Running (Throttled)

**Comment by izak** [comment]
We added differentiation (between Throttled and flat-out/MPPT) in Venus 2.30. The existing `pS` attribute has these values:

```
11=Running (MPPT)
12=Running (Throttled)
```

This is a summary over ALL the trackers, for PV-inverters with multiple trackers. Individual status is probably not useful: There is only two reasons a PV-inverter would run limited: Either it is frequency-limited, or it is limited via sunspec/modbus.

And it is unclear how widely this is implemented. This is a mandatory field in Sunspec, but I seem to recall at least some SMA inverters playing a little loose with this field.

Fronius inverters (at least all that I have seen) does support individual tracker state (sunspec model 160), but dbus-fronius doesn't read that model yet. If useful, we can of course add that.
