### ISSUE TITLE
Hiawatha missing from Venus OS...?

### ISSUE THREAD

**Issue by OutsourcedGuru** [victronenergy/venus#1125]
I would like to add a nice REST interface as described [here](https://community.victronenergy.com/articles/48977/simple-jsonrestajax-interface-to-venus-d-bus-writt.html). The software **Hiawatha** is mentioned at the bottom of that post and I see a little evidence on my Venus OS installation that `hiawatha` was perhaps in the image in previous versions. I see an empty `/data/log/hiawatha` folder as well as a `/var/log/hiawatha` folder.

I don't see any processes called `hiawatha` nor is there an `/etc/hiawatha` folder nor config file for it. I don't see any evidence that it is called during boot.

I've created a `/var/www/venus/ui` folder and put the `dbus-get.py` file in it, marking it as executable. Attempting to call it as a CGI program, it doesn't execute and instead attempts to return the file contents.

Did Hiawatha get retired?

Firmware: v3.01
Hardware: Raspberry Pi 3B Rev 1.2

**Comment by mpvader** [comment]
Hi, yes its now nginx if I recall correctly.

please use community for further questions. This issue tracker is to track development, not for questions or problem solving - sorry.
