### ISSUE TITLE
generator start/stop: add option to skip warm-up when start is triggered by overload

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1134]
a screenshot is coming from a distributor who made something for that in node-red.

**Comment by mpvader** [comment]
ps. this is a nice to have, it is not necessary to take any risks wrt bugs in v3.10 release

**Comment by ReinvdZee** [comment]
@mpvader Is this still relevant?

If so, the idea would be to add a switch here to skip warm-up?
![image](https://github.com/user-attachments/assets/997d7fa7-ae24-433d-a4ac-336a41fc106c)

**Comment by philipptrenz** [comment]
I think this is really valuable. Systems that are dependent on the generator assisting in high load situations could otherwise not use warm-up at all.

**Comment by ReinvdZee** [comment]
I've added the setting:
![image](https://github.com/user-attachments/assets/73c08db7-02a1-47dc-8929-fc77eaf33783)

If enabled, warm-up will be skipped when start is triggered by the inverter overload condition. The cool-down time and generator stop-time are not skipped.

Should we make the setting only visible when the vebus system actually supports warm-up? (The warm-up & cool-down menu also won't be visible if it doesn't). I think it makes sense to hide this setting when there is no warm-up to skip.

@mpvader, @philipptrenz?

**Comment by mpvader** [comment]
yes perfect.
