### ISSUE TITLE
Alternations of venus-data.tgz

### ISSUE THREAD

**Issue by dirkjanfaber** [victronenergy/venus#1139]
[This](https://github.com/victronenergy/meta-victronenergy/commit/fcd755960a37147e24f9f415551636756a4f3ea1) commit made it possible to use more filenames on an inserted usb stick while booting. 

The following files need to be added to https://victronenergy.com/upload/software/venus-factory-default/ (and documented)
- [x] `venus-data-00-backup-data-partition.tgz` - copies all that is on the data partition onto the usb stick
- [x] `venus-data-20-signalk-reset.tgz` - wipes everything from `/data/conf/signalk/`
- [x] `venus-data-30-signalk-delete-data-logs.tgz` - removes all signalk loging
- [x] `venus-data-20-node-red-reset.tgz` - wipes all in `/data/home/nodered/`
- [x] `venus-data-90-reset-all.tgz` - reset all to defaults (remove everything from `/data/` besides `venus/`)
- [x] Document the working of this system (https://www.victronenergy.com/live/ccgx:root_access#hooks_to_install_run_own_code_at_boot).
- [ ] Update the [manual](https://www.victronenergy.com/media/pg/Cerbo-S_GX/en/reset-to-factory-defaults-procedure.html)
- [x] Upload the new `venus-data-*.tgz` files to a webserver.
- [x] Audible notification when script has finished.

Adding multiple files on a single USB stick should also work. The order of processing the files is alphabetical, which means that no new additions should be put before the **b**(ackup).

And when the script is ready with its tasks, the GX should give an (optional?) sound to notify the user that it has done its tasks.

**Comment by jhofstee** [comment]
Without looking into it, my bet is that venus-data-reset-all.tgz is venus-data-reset-settings.tgz, right?

**Comment by jhofstee** [comment]
Oh and please add a fixed length numbered prefix, so it is clear in which order things run.

**Comment by dirkjanfaber** [comment]
@jhofstee Can you review https://github.com/victronenergy/meta-victronenergy/compare/master...faberd/issue-1139 ?

**Comment by mpvader** [comment]
@dirkjanfaber : what is the minimum Venus OS version for these files to work? Is that the same version for which todays venus-data.tgz works, which is v2.12 ?

**Comment by mpvader** [comment]
And can you arrange uploading the files to the webserver as well?

**Comment by jhofstee** [comment]
isn't this working since v2.30?, see https://github.com/victronenergy/meta-victronenergy/commit/469760fef4ed2ee977f482c997ac24c2678222c5

**Comment by mpvader** [comment]
@dirkjanfaber wrt documenting:

these three should only go into the venus os large manual I think, right? you do that?

- venus-data-20-signalk-reset.tgz - wipes everything from /data/conf/signalk/
- venus-data-30-signalk-delete-data-logs.tgz - removes all signalk loging
- venus-data-20-node-red-reset.tgz - wipes all in /data/home/nodered/

Same for this one I suppose?

- venus-data-00-backup-data-partition.tgz

No normal user can do anything with what is on there. Its for backupping Node-RED flows - right?


Which leaves only this one:

- venus-data-90-reset-all.tgz

and that already exists, just with a different name.

**Comment by dirkjanfaber** [comment]
Uploaded the files to the webserver, accessible via https://www.victronenergy.com/upload/software/venus-factory-default/ + the file name. E.g.  https://www.victronenergy.com/upload/software/venus-factory-default/venus-data-00-backup-data-partition.tgz

Updated the [venus-os:large documentation](https://www.victronenergy.com/live/venus-os:large#backup_reset_to_factory_defaults) and the [root-access documentation](https://www.victronenergy.com/live/ccgx:root_access#hooks_to_install_run_own_code_at_boot).
