### ISSUE TITLE
beaglebone: move relay2 to TIMER_5 (P8.9)

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#115]
It used to be on TIMER_6 (P8.10), but that pin is only connected on the bbb: not on the bbe.

**Comment by mpvader** [comment]
TIMER_5 equals GPIO2_5 equals pin 69

**Comment by mpvader** [comment]
https://github.com/victronenergy/meta-victronenergy/commit/5de53ea3b6ff27a340014970ecff7f2cf4edfbdc

**Comment by jhofstee** [comment]
https://github.com/victronenergy/meta-victronenergy/commit/e45e00a51b48d27520e1b777528099934701eaeb in v2.01~3
