### ISSUE TITLE
Fischer Panda: Load % missing?

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus#1153]
Reported on community:
https://community.victronenergy.com/questions/231599/venus-os-v3202-available-for-testing.html?childToView=234667#answer-234667

![62388-img-1300-1](https://github.com/victronenergy/venus/assets/6614648/24c6a6fe-1920-49fb-9a7d-e569a8ad0b80)

**Comment by mpvader** [comment]
Is this solved in v3.20 @martinbosma ?

**Comment by martinbosma** [comment]
I was unable to reproduce this with the hardware we have here. Perhaps this was part of the generator start/stop bug we had in an earlier Venus version?

**Comment by mpvader** [comment]
I don't know, I'll close this issue and if there still is something we'll hear soon enough.
