### ISSUE TITLE
vrmlogger: Log current limit per solar charger

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#1154]
While the charge voltage is one voltage and is the same for all chargers, the current limit is split up over solar chargers, in an attempt to get to the total while there might be shading on one array, or different directions might mean one side has more capacity than the other.

For debugging, it would be good to also log this.

**Comment by beat** [comment]
Actually displaying it too on the Cerbo GX and graphing it in VRM would also be useful, even logging the *global* maximum MPPT power available would also be very useful in finding how much "capping"/"curtailing" or "underproduction" is made.

And while logging the global maximum found of MPPT scans, logging the I/V P/V curves of MPPT scans would be extremely useful in assessing the solar arrays' health.
