### ISSUE TITLE
Add evcharger role to energy meter drivers

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#1160]
Presently our Energy meters can measure grid, pvinverter, genset, or acload.

A useful addition for third-party EVCSs and energy measurement reporting, would be to use an energy meter to proxy for an EVCS.

TODO
- [ ] Add evcharger role to dbus-modbus-client (Izak, Mans or Phillip)
- [ ] Add evcharger role to dbus-cgwacs (Izak)
- [ ] Add evcharger role to vecan-dbus (Martin)
- [ ] Add evcharger role to VM-3P75CT firmware (Martin)
- [ ] Adapt GUI to deal with evchargers that are really energy meters (some paths missing).

**Comment by martinbosma** [comment]
I've updated the issue to add the role to the firmware of the VM-3P75CT as the role settings is stored in the device itself, not in vecan-dbus.

**Comment by izak** [comment]
This issue is now superseded by https://github.com/victronenergy/venus-private/issues/380.

Also, support for heat pumps and evchargers is now in dbus-cgwacs.
