### ISSUE TITLE
AC Loads calculation wrong when feeding to grid

### ISSUE THREAD

**Issue by mhin76** [victronenergy/venus#1169]
I have installed an EM540 as grid meter on my venos OS v3.11 on Raspberry Pi. On Inverter I am using Hoymiles with a plugin that converts it to a venus readable inverter. I noticed (per phase) that as soon as a phase is feeding power to the grid the AC Load is wrongly calculated, it just shows the same amount as the PV Inverter. I see that others have the same issue (https://community.victronenergy.com/questions/221827/venusos-ac-loads-calculation.html)
This leads to totally wrong number also on my VRM history and shows always 100% solar consumption.
Could you check the bug?
<img width="421" alt="image" src="https://github.com/victronenergy/venus/assets/49210075/b4c2a830-2bd7-4e69-b886-8c595d053724">

**Comment by DerJungeHerr** [comment]
Same Issue here! We need a fix soon 😔

**Comment by mpvader** [comment]
sorry but thats just a not supported configuration. Or is there even one Victron device in your system?

**Comment by mhin76** [comment]
apparently not. I was planning to create an ESS with a MultiPlus II. I know that hoymiles inverter are not supported and only show on my venus OS via dbus-opendtu. Apparently that integration is not sufficient to fully simulate a suported inverter.

**Comment by mhin76** [comment]
Important info from the dbus_opendtu creator: in case you use hoymiles to visualize the inverter figures: that is only supported up to version 3 (version <3) of venus OS. apparently once connected with a MultiPlus it should also work with version 3 and above. will close this issue (as it is not a bug).
