### ISSUE TITLE
add 'no AC-Out subsystem' setting

### ISSUE THREAD

**Issue by edevries-victron** [victronenergy/venus#118]
Add a setting that indicates there's is a subsystem connected to the vebus AC-out. Some ESS/hub-4 systems do not use the AC-Out (grid parallel system). We can use the settings to simplify the GUI.

- [x] Systemcalc: make Ac/ConsumptionOnOutput invalid if this setting is disabled. Also make sure AC-out power is not used in other computations. Systemcalc will create the setting at '/Settings/SystemSetup/HasAcOutSystem'. Default value is 1.
- [x] Hub4Control: check if we need to use AC-Out power if setting is active. The AC-Out power is now used to enforce max charge/discharge power. Conclusion: keep the service as it is now, if there is nothing on AC-Out, the reported power will be very low anyhow. So no need to add (even) more complexity here.
- [x] Check generator start/stop for use of ConsumptionOnOutput. It should be able to handle invalid values.
- [x] GUI: Add switch (ESS settings page) to enable/disable setting. 
- [x] GUI: Hide all visualizations based exclusively on consumption on output. (for example: over grid parallel, maybe also the tiles visualization).
- [x] Discuss: should PageVebus still show the AC-Out values? Conclusion: keep the page as it is. It may be useful for diagnostics.

**Comment by mpvader** [comment]
And then later we can add more functionality. In an ESS system the CCGX can switch the whole Multi off during inactive periods. Thereby doing a huge saving in standby power

For now though, @jepefe and @edevries-victron please complete above list of tasks.

**Comment by jepefe** [comment]
The gui part is done but I'm doubting to which page add this setting.

**SystemSetup page**
Makes sense to add the setting here because is a system setting. But on the other hand Hub-2 users will get wrong AC load values if they enable this option. Showing toast warning about this might help.

**ESS settings page**
Also makes sense to put the setting here because at this moment only applies to ESS/Hub-4 systems. I think this a more safe place for the setting.

My vote goes to ESS settings page.
@mpvader, what do you think?

**Comment by mpvader** [comment]
> But on the other hand Hub-2 users will get wrong AC load values if they enable this option.

I don't see that as a valid argument: there are plenty of things people can do to get themselves in trouble, this is just one of them.

Yes, I think ESS page is best. Please show it to me once you have it there, so we can have a look together.

**Comment by edevries-victron** [comment]
All changes have been released: 
* gui: feat_no_acout_setting
* dbus-systemcalc v1.37

**Comment by mpvader** [comment]
An update: dbus-systemcalc v1.37 was already released as part of Venus v2.01. But the gui branch is still pending. Its now on the todo for Venus v2.06.

**Comment by jhofstee** [comment]
gui branch included in v2.07~1
