### ISSUE TITLE
mk2-dbus & modbus: add boost factor & inverter output voltage settings

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1181]
### New dbus items

`Devices/#/Settings/AssistCurrentBoostFactor`
`Devices/#/Settings/InverterOutputVoltage`
`Devices/#/Settings/PowerAssistEnabled`

### Todo list

- [x] Add the function + dbus paths to mk2-dbus
- [x] Add it to the modbus register list

No need to add it to VRM

### Description

See https://secure.helpscout.net/conversation/2379896735/9630.

@vejpasop if I remember correctly then this is not a large change for you? Can you do it latest in three weeks from now?

**Comment by vejpasop** [comment]
The required dbus items are included in mk2-dbus V3.64

**Comment by mpvader** [comment]
Included per a v3.20~beta.

I’ve also informed the customer asking for this
