### ISSUE TITLE
v3.20 regression icm MPPTs and VictronConnect?

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1196]
Reported here: https://community.victronenergy.com/questions/249509/venus-os-v32034-available-for-testing.html

<img width="599" alt="image" src="https://github.com/victronenergy/venus/assets/5200296/30bb5713-7fca-44c8-bd29-872b33e50a87">

@ReinvdZee can you see if you can reproduce this? I'll take care of the communication on Community.

**Comment by ReinvdZee** [comment]
So far, I am unable to reproduce this issue. I've tested with firmware version v3.20\~35 and v3.20\~37 on a Cerbo GX. As far as I understand, the user is unable to see an MPPT under "Devices" when logging into VRM on the VictronConnect App. See the following screenshot:

![image](https://github.com/victronenergy/venus/assets/38864570/0aadc84b-b1f4-477b-8391-408117659b57)

- Firmware version V3.20~37.
- VictronConnect V5.101
- Tested on both Cerbo GX and Ekrano GX running Beta UI version (if that matters at all)
- Connected MPPT: BlueSolar MPPT 100/15. 
- Enabling/disabling the charger output and the load output makes no difference. 
- I also tried with multiple and different types of MPPTs, but all devices show up correctly in the "Devices" tab.
