### ISSUE TITLE
v3.20: crashes when changing the time?

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1201]
https://community.victronenergy.com/questions/249509/venus-os-v32034-available-for-testing.html?page=2&pageSize=50&sort=oldest

![image](https://github.com/victronenergy/venus/assets/5200296/66245609-c53c-48da-9619-a9c8ac5431a0)

@ReinvdZee can you triage / see if you can reproduce?

**Comment by ReinvdZee** [comment]
I tested this quickly on v3.20~37 and v3.20~40. On these versions, I am unable to reproduce the issue.

If someone points me to the location of the v3.20~35 release, then I can also test on this version.

**Comment by mpvader** [comment]
Hi @ReinvdZee , we don't keep those. Only official release are archived. I've answered on Community saying that we can't reproduce, and asking him for his URL and to enable Remote Support.

Lets await that.

**Comment by mpvader** [comment]
Received no report back from the user; closing.
