### ISSUE TITLE
Update bluez to v5.72 - fixes connection for Pixel 6

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1206]
Thiemo tested this (built the newer Bluez, installed that on a GX, etc.

**Comment by mpvader** [comment]
@ThiemoVanEngelen / @jhofstee fyi. Note that I've moved this to v3.30, and removed it from the todo wiki page.

**Comment by jhofstee** [comment]
Closing this, since @ThiemoVanEngelen can't reproduce the issue. It can be reopened if needed.
