### ISSUE TITLE
bug: VE.Bus BMS v2 not displayed on Cerbo GX as controlling BMS

### ISSUE THREAD

**Issue by mman** [victronenergy/venus#1208]
I am filing this because I believe Cerbo GX (Venus OS) does not properly handle presence of VE.Bus BMS v2. Feel free to close if inappropriate, I may have misunderstood the documentation.

This is Victron only system, no 3rd party components present.

### System Config

- 2x Victron Smart LiFePo 12V/100Ah
- VE.Bus BMS v2
- Multiplus 12/1600/70 (new version)
- SmartShunt
- SmartSolar MPPT 100/50
- Smart VE.Bus dongle
- Cerbo GX

All updated to the latest firmware versions as available in TestFlight VictronConnect, Cerbo on latest release candidate updated regularly automatically.

MPPT + SmartShunt connected via VE.Direct cable to Cerbo GX.

Multiplus and VE.Bus dongle connected over VE.Bus to VE.Bus BMS v2.

MPPT + SmartShunt + VE.Bus dongle interconnected via VE.Smart Networking, dongle reporting temperature sense.

Cerbo GX DVCC enabled with SVS and SCS on, STS off per installation manual.

## Problem Statement

DVCC screen does not detect controlling BMS. 

### Expected Outcome

VE.Bus BMS v2 listed as `Controlling BMS` on the DVCC screen.

### Current Outcome

`Controlling BMS: None`

### Multiplus indicates that VE.Bus BMS v2 is present and controlling the system

<img width="507" alt="Screenshot 2024-01-31 at 11 50 30" src="https://github.com/victronenergy/venus/assets/249814/ef9d037f-bf6c-495b-8bb0-533c1911769b">

### System setup correctly detects SmartShunt as battery monitor

<img width="509" alt="Screenshot 2024-01-31 at 11 49 45" src="https://github.com/victronenergy/venus/assets/249814/2b4a7ed5-9c38-4e39-b545-30047c258631">

### MPPT indicates that it is networked and controlled via BMS

<img width="503" alt="Screenshot 2024-01-31 at 11 50 48" src="https://github.com/victronenergy/venus/assets/249814/04ea77ec-bf53-4436-b95c-29634306d8d3">

### Yet DVCC screen indicates that there is no controlling BMS

<img width="502" alt="Screenshot 2024-01-31 at 11 50 05" src="https://github.com/victronenergy/venus/assets/249814/c2e24ef6-4774-4eba-938b-28991e70dbbb">

## Additional Info

I think this may be possibly related https://github.com/victronenergy/venus/issues/901.

More or less same information I outlined here: https://community.victronenergy.com/questions/256027/dvcc-with-vebus-bms-v2-cerbo-gx-mppt-smart-solar-1.html

**Comment by mman** [comment]
System available via VRM upon request.

**Comment by bergie** [comment]
Can reproduce on Cerbo with firmware 3.13 

![IMG_1348](https://github.com/victronenergy/venus/assets/3346/b5270bf6-2fa9-4a83-97b2-eebca881870d)

**Comment by izak** [comment]
I am not convinced that a Ve.Bus BMS is a "controlling BMS" in the same way as the third party BMSes that make up the voltage and the current (the middle V and C) in the acronym DVCC. A VE.Bus BMS is at best a two-signal BMS, indicating only that charge/discharge is allowed or not.

To avoid confusion though, it might be best to hide this part of the UI if there is nothing to select from, which will (almost?) always be the case in a system with a VE.Bus BMS.

I suppose you could have both a VE.Bus BMS on the primary battery and another BMS on a secondary battery, but I would think such a case fairly rare.

**Comment by mman** [comment]
@izak Thanks for the comments, I understand what you are saying on the low level engineering meaning :).

I think most confusion comes from the fact that the English term "controlling BMS" is used in two places with different meanings. 

In Venus the meaning of "controlling BMS" is that it is the main source of truth of DVCC data.

In MPPT "BMS controlled" means that BMS will enable/disable charge/discharge signal.

I do not know what the proper solution is, hiding in GUI v1 is probably a good short term fix - adding a paragraph into CerboGX documentation is even better, taking into account that the same problem will pop up soon in GUI v2 is another matter :)

**Comment by izak** [comment]
After thinking about it some more over the evening: The idea of selecting a different BMS when there is already a VE.Bus BMS in the system is one that will never work. If you send the ESS assistant a charge voltage while there is also a VE.Bus BMS, the Multi switches off and you get an error code.

The correct solution therefore is to take away this selection box, it makes no sense in this context.
