### ISSUE TITLE
Remove gui—v2 and its remote capability bit from vrmlogger

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1220]
- [x] Remove gui-v2 + the wasm version
- [x] Remove the related capability bit in vrmlogger

**Comment by izak** [comment]
I removed the logging of the wasm version and the capability bit. I'm unsure how to remove the wasm itself, so I did not tick that item.

**Comment by mpvader** [comment]
Ok thanks @izak . Removing the WASM itself is something for Jeroen or me to do, which we'll do right before building the official release.

**Comment by jhofstee** [comment]
This has been done.
