### ISSUE TITLE
Check that the Cerbo reset button resets the BLE pin

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1226]
it looks like it does that:

https://github.com/victronenergy/venus-button-handler/blob/master/venus-button-handler

But the manual doesn’t list it.

please double check and then ask Stefanie to update the manual:

https://www.victronenergy.com/media/pg/Cerbo_GX/en/configuration.html#UUID-67bdc257-9df9-7897-592e-76eb370de8d8

**Comment by ReinvdZee** [comment]
Can confirm, BLE pin is reset with the 'long press' of the button handler. I'll ask Stefanie to update the manual.
