### ISSUE TITLE
Add 'silent settings' to localsettings

### ISSUE THREAD

**Issue by edevries-victron** [victronenergy/venus#123]
It is sometimes useful to look in the logs of localsettings to see which settings have been changed by the user. Problem is that some services (generator start/stop, dbus-fronius, dbus-cgwacs, ... ?) use localsettings for persistent storage, causing the logs to fill quickly. So the logs of more interesting changes will be deleted soon after they have occurred.

This could be solved by adding a new flag ('silent') to each path in localsettings. If this flag is set, changes on that path will not be logged. The flag is set by a new D-Bus method: AddSilentSettings. The behavior of the existing method AddSetting will not change, so we will not break existing services.

Tasks: 
- [x] Add a new method to the localsettings D-Bus API: AddSilentSetting. Works like AddSetting, but flags the new setting as silent. If this function is called on an existing setting, it should set the silent flag.
- [x] Adjust AddSetting to reset the silent flag if called on an existing setting.
- [x] Use AddSilentSetting in dbus-fronius
- [x] Use AddSilentSetting in dbus-cgwacs
- [x] Use AddSilentSetting in hub4control
- [x] Use AddSilentSetting in generator start/stop
- [x] Find out if there are more services in need of this treatment.

**Comment by mpvader** [comment]
https://github.com/victronenergy/dbus_generator/commit/383ff5b47caf15bc5d2d9e2bd7a9be005d44898a

**Comment by mpvader** [comment]
In case there is anything else, we'll see it eventually when diagnosing a system.

**Comment by mpvader** [comment]
@edevries-victron the dbus-fronius task is checked in above list, but I still see energy updates in the localsettings log? Also nothing here: https://github.com/victronenergy/dbus-fronius/commits/master.

Perhaps a mistake? (non urgent).

**Comment by edevries-victron** [comment]
dbus-fronius & dbus-cgwacs have been fixed, but not yet released. I have unchecked them again.

**Comment by mpvader** [comment]
Both were added in v2.08~3
