### ISSUE TITLE
Feature request Teltonika EYE SENSOR

### ISSUE THREAD

**Issue by hypemedia** [victronenergy/venus#1236]
Teltonika has a series of cheap senzors compared to ruuvi that do the same thing.
They support ibeacon and eddystone protocol. https://wiki.teltonika-gps.com/view/EYE_SENSOR_/_BTSMP1

It will be nice to be able to get data from them in venus os.

**Comment by mpvader** [comment]
Hi, thanks for the suggestion -  perhaps some day - but for now we're not investing any time in more sensors ourselves.
