### ISSUE TITLE
BatteryLife: check if can live without the 5% hysteresis

### ISSUE THREAD

**Issue by edevries-victron** [victronenergy/venus#124]
If a system with BatteryLife enabled discharges to the dynamic SoC level, it will go to 'Discharge disabled' mode. Discharge will be allowed again if the actual state of charge exceeds the dynamic SoC level + 5%.

It would be nice to allow discharge again as soon as the dynamic SoC rises above the dynamic SoC level itself (so no 5% hysteresis). Check if this will not get us in situations where the BatteryLife state changes very often between 'Discharge disabled' and 'Self consumption'.

**Comment by mpvader** [comment]
old non-issue
