### ISSUE TITLE
feeds has a stale v3.30 entry

### ISSUE THREAD

**Issue by kwindrem** [victronenergy/venus#1247]
You might want to remove the v3.30 entry in http://updates.victronenergy.com/feeds/venus/. It's really out of date (v3.30~2).

I do like the latest beta being available while you do testing on a bug fix on the current release version so maybe this can be worked into your workflow.

**Comment by jhofstee** [comment]
These should be gone again. And yes, having more feeds can be useful, and also more confusing at the same time.
