### ISSUE TITLE
Naming of CAN ports on Cerbo GX MK2

### ISSUE THREAD

**Issue by dirkjanfaber** [victronenergy/venus#1248]
On the Cerbo GX MK2 (product-id `C012`), the ports on the device got changed, causing them to no longer match the naming in the remote console.

![image](https://github.com/victronenergy/venus/assets/3098947/5cb88f0e-be75-4dfe-b477-1031e83a1412)
![image](https://github.com/victronenergy/venus/assets/3098947/43cb72b6-b84f-4cca-984e-207671a3b47d)
<img width="339" alt="image" src="https://github.com/victronenergy/venus/assets/3098947/c2fd3b34-7f4e-4fd6-9495-8807c0622fd1">

What was VE.Can on the older Cerbo is VE.Can 1 on the MK2. What was BMS-Can on the older Cerbo is VE.Can 2 on the MK2.

**Comment by mpvader** [comment]
Cerbo MKII is the public name for the B series. 

For you to fix @jhofstee ?
