### ISSUE TITLE
issue with dbus or MQTT since Venus OS v3.3

### ISSUE THREAD

**Issue by schollex** [victronenergy/venus#1258]
Hi,

I wrote my [own service for providing a gridmeter via dbus](https://github.com/schollex/dbus-d0-smartmeter).
This dbus-gridmeter-service is running unmodified and stable for me since Venus OS v3.0 and on further releases. But since v3.3, I'm facing an issue.
My gridmeter's consumped energy and given energy counters are read by my script. This counters are written to dbus.
This values are publishde by mqtt and read via mqtt through my Home Assistant instance.
Within Home Assistant, I'm facing the problem that since Venus OS v3.3, for just a view seconds per day, wrong gridmeter-energy-values are received. This leads to wrong [Energy Management Statistics](https://www.home-assistant.io/blog/2021/08/04/home-energy-management/): if the correct gridmeter value of 1000 kWh is transmittted every second, then one faulty value of e.g. 900 kWh is transmitted and then again correct values of 1000 kWh, then Home Assistant claims 100 kWh of energy just being consumed.
I added debug-logging to my gridmeter-dbus-service. The result: every second the python-script is writting correct gridmeter-values to dbus.
After 2 weeks of malfuntion on Venus OS v3.3, I switched back to Venus OS v3.2 => the error is gone since 1 week.

So I think there must be any rarely occuring problem with value-transmission on dbus or mqtt with Venus OS v3.3.

Sorry I can't provide further details.

Regards,
Alex

**Comment by mpvader** [comment]
Hi, thats strange. I really would not know what could cause that.

I’ll keep it in mind in case we see something similar in our code in the future.

For any further help, please turn to the community (Mods section on https://community.victronenergy.com).

**Comment by schollex** [comment]
Of couse this sounds strange, but I "proved" that this issue only occurs with VenusOS v3.3.
I read you switched from mosquitto to another mqtt-broker, so this major-mqtt-change could be a reason for my problems.
I invite you to subscribe to ..../grid/0/Ac/Energy/Forward and .../grid/0/Ac/Energy/Reverse on Venus OS v3.3 and log every single value-transmission for some days to verify if there is really not one false value.

**Comment by schollex** [comment]
I updated to v3.31 where I cannot reproduce the issue.

**Comment by mpvader** [comment]
Hi again, ok good!
