### ISSUE TITLE
Connected gensets step 2: complete the UI/UX cleanup

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1287]
In v3.33 we are making, a few changes to improve the UI. Some things were left out to not delay releasing v3.33 any further.

This issue is to list the things we need to look into as a follow-up:

- [x] #1315 
- [x] There is no runtime reset button for the DSE controller (or is there @philipptrenz ? )
- [x] There are two error states, one in the top level menu, and one in the lower one (**fixed in v3.40 and backported to v3.33**).
- [x] The status of the Remote start option (in the genset panel) is now not visible in the GX menus; its only visible when its wrong. Consider fixing that (**fixed in v3.40 and backported to v3.33**).
- [x] #1316
- [ ] Make sure all UIs are aligned (gui-v1, gui-v2, VRM, html5-app)

**Comment by philipptrenz** [comment]
> There is no runtime reset button for the DSE controller (or is there?)
No, I think the generator runtime is like the odometer on a car, it should not be manipulable. 

One note to service interval: Some controllers have their own service interval counter with reset option, but I think it's fine that both systems provide that and it is up to the customer to decide which one to use.

**Comment by mpvader** [comment]
@philipptrenz , sorry, I wasn’t clear: I meant button to reset the service interval counter. Totally agree on the total runtime counter.

Does our system already use the DSE runtime counter for its own counting? Or if not the DSE status (running/stopped) in order to when when the counter needs to count and when not?

**Comment by philipptrenz** [comment]
@mpvader As far as I know, it does not use the reported runtime of the genset, but I think it initially uses the readings when a genset is first found, which still causes the values to drift apart.

**Comment by philipptrenz** [comment]
I want to propose to streamline this issue with additional tasks:

- [ ] Allow to enable Remote start mode via gui → see https://github.com/victronenergy/venus/issues/1273 
- [ ] Replace "Generator stop time" for connected gensets, as we know when they are actually stopped
- [ ] Replace "Generator stop time" when state is reported by digital input (see [here](https://www.victronenergy.com/media/pg/Cerbo_GX/en/digital-inputs.html#UUID-26968630-0052-21ca-cc8f-c15551e93406))

<img width="488" alt="Generator stop time" src="https://github.com/victronenergy/venus/assets/11627598/9342828d-f7e5-4e4a-8377-0c7974553afa">

**Comment by mpvader** [comment]
One more here. And for me its not necessary to fix that in gui-v1; lets just make sure its 100% in gui-v2.

![image](https://github.com/victronenergy/venus/assets/5200296/367eed93-229d-4f6c-88cf-454d72ab6613)

**Comment by mpvader** [comment]
Hey @philipptrenz ,

> I also have a stack of VRM issues related to generator, which El Niño asked to discuss next Wednesday with me and @ReinvdZee:

I went through those issues; finally - sorry for the delay. See my responses there - hope that helps!

**Comment by ReinvdZee** [comment]
I've added a todo item for the clear error gui button currently implemented. The current implementation was originally added for FP but is outdated. It does not do anything on the genset (possibly only on very old genset firmware versions, according to @martinbosma). Newer gensets support clearing errors via Modbus. 

We should offer the option to clear errors remotely only when that is actually supported by the genset.

**Comment by ReinvdZee** [comment]
I moved some of the tasks to separate issues to track them separately.

**Comment by philipptrenz** [comment]
Just noticed, that the error message says "Remote switch control disabled", but should now say "Remote start mode disabled". I suspect that this may have slipped through during path renaming.

![192 168 254 90_gui-beta_(Ekrano GX) (18)](https://github.com/user-attachments/assets/b1c3a963-98bc-4276-a03c-82519bb57db1)
<img width="481" alt="Bildschirmfoto 2024-09-06 um 15 23 59" src="https://github.com/user-attachments/assets/32758a58-5534-4c4e-aec4-2f5b2408a4db">

**Comment by ReinvdZee** [comment]
Most of the bullet points are checked. As per the UI alignment, gui-v1 and v2 won't be in sync since we're not doing all changes to v1 anymore. And the other UI-related items are tracked in different issues. (see this [one](https://github.com/victronenergy/venus/issues/1350) about VRM).

Closing this issue.
