### ISSUE TITLE
Connected gensets step 1: v3.33 changes

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1288]
- [x] Remove the "Mode" option on the genset toplevel; which had On/Off/Auto
- [x] Move the "Autostart functionality" and "Manual start" functionality from the "Autostart" submenu up to the toplevel.
- [x] Various more changes, see commit as well as picture below for the details.

**Comment by mpvader** [comment]
Here a picture showing the result:

![image](https://github.com/victronenergy/venus/assets/5200296/92a6365f-10c8-4282-9099-d35f0e7ab3a3)

**Comment by mpvader** [comment]
this work continues here: https://github.com/victronenergy/venus/issues/1287

**Comment by philipptrenz** [comment]
Added missing control statuses *Warm-up* and *Cool-down*:
![genset_new_ui](https://github.com/victronenergy/venus/assets/11627598/2cfb7dae-afdc-4c05-86e8-93fc6fd2ad91)
