### ISSUE TITLE
Improve 'storage contains a firmware image' handling

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#131]
In below toast, add info on how to start the update. Or even better, automatically switch to the Settings -> Firmware -> Offline updates menu when someone inserts an sdcard or usb stick that contains such a file. And do a check for updates. Or tell the user to do it.

![image](https://cloud.githubusercontent.com/assets/5200296/24095739/be5a630c-0d5e-11e7-81df-600dab9b04c2.png)

**Comment by jepefe** [comment]
Improved in improve_sdcard_notifications branch:
Show offline firmware update page when sdcard with swu file inserted . Updates checking is also automatically triggered.

**Comment by jhofstee** [comment]
included in v2.07~1
