### ISSUE TITLE
Connected genset: service & runtime counters

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/venus#1315]
- [x] There are now two runtime counters in the menu, (and on VRM etc.). The one by the genset panel is the one we want - the counter by dbus-generator needs to be hidden or otherwise not used.
- [ ] We need to make sure that runtime + service interval as visible on VRM uses the DSE one.

**Comment by ReinvdZee** [comment]
>There are now two runtime counters in the menu, (and on VRM etc.). The one by the genset panel is the one we want - the counter by dbus-generator needs to be hidden or otherwise not used.

The "Engine" menu of the connected genset shows the operating time as reported by the genset controller:
![image](https://github.com/user-attachments/assets/e5394468-0832-446e-9515-736b71503a14)

The "Auto start/stop" menu shows "Run time" "Total run time" and "Daily run time" metrics:
![image](https://github.com/user-attachments/assets/2c8142aa-b362-4537-bbe1-3c17ce454150)

When the operating time of the genset is available, the "Runtime" and "Total runtime" fields should be hidden because the values can be different (and then the operating time as reported by the genset is the most useful). 

"Daily runtime" contains historical data of the start/stop service: 
![image](https://github.com/user-attachments/assets/8b05aa67-30ec-4489-8563-a42c8aca1a6f)

AFAIK, connected gensets do not report this data (maybe some do, not sure), so it may still be useful for the user to display this, even though its data from a different source (startstop instead of genset). What do we do with this @mpvader ?

@philipptrenz Do you know if there are connected gensets which do report this? And does `dbus-modbus-client` also fetch this data? If so, we can also display historical data from the genset if present, or display it from startstop if not.

**Comment by philipptrenz** [comment]
@ReinvdZee  There's one more time-related page under "Auto start/stop" > "Settings" > "Run time and service":
<img width="481" alt="Bildschirmfoto 2024-07-16 um 16 53 44" src="https://github.com/user-attachments/assets/c18dc078-0aae-47d8-819d-fc829ac2496c">

**Comment by ReinvdZee** [comment]
@philipptrenz Oh thanks, We should definitely hide the "Generator total runtime" field there. And depending on what we do with the daily run time counter, the top one can be hidden as well.

**Comment by philipptrenz** [comment]
Mockup: 
![Frame 1023](https://github.com/user-attachments/assets/6a45ccd8-96a3-4655-9871-dce250b5cf2d)

**Comment by philipptrenz** [comment]
> @philipptrenz Do you know if there are connected gensets which do report this? And does dbus-modbus-client also fetch this data? If so, we can also display historical data from the genset if present, or display it from startstop if not.
Maybe some do, but definitely not all. Therefore, I wouldn't rely on that. I think it's fine if "Current run time" and "Daily run time" are tracked by `dbus_generator`, as long as "Total run time" is accurate and in sync with the reading from the genset controller.

**Comment by mpvader** [comment]
My two cents: daily run time counters are very useful; otherwise it seems all to be going in the good direction

**Comment by ReinvdZee** [comment]
@mpvader 
>My two cents: daily run time counters are very useful; otherwise it seems all to be going in the good direction

Thanks, I agree. We'll keep the daily runtime counter and the current runtime counter. Both use dbus_generator as source. The total runtime will use the genset as source if possible. 

@philipptrenz Thanks for you mockup, looks good!

> Maybe some do, but definitely not all. Therefore, I wouldn't rely on that. I think it's fine if "Current run time" and "Daily run time" are counted by dbus_generator, as long as "Total run time" is accurate and in sync with the reading from the genset controller.

Ok, we'll just use the dbus_generator counters for this then.

**Comment by ReinvdZee** [comment]
@philipptrenz See screenshot:

![image](https://github.com/user-attachments/assets/0bb8ae1c-0e27-4fdb-ac48-71ed2bc836b9)

The "Generator service interval" is not present in your mockup, would you expect it somewhere else? In settings perhaps? I think that if you're able to reset the service timer here, you should also be able to configure it.

**Comment by ReinvdZee** [comment]
Device page: 
![image](https://github.com/user-attachments/assets/aeb9b9ca-0452-4a1b-9d31-f6b7f6131fe1)

Run time and service page:

>We remove "Operating time" from the "Engine" page
Engine page: 
![image](https://github.com/user-attachments/assets/f874bd03-89d7-401e-8f03-8c18badca6b0)


>We sync "Total run time" of dbus_generator with /Engine/OperatingHours from the genset controller
"Total run time" in "Service 
>We introduce a new top-level entry, so that all runtime-related metrics are at one place
By this, we can move "Settings" to the top level and get rid of "Auto start/stop" → One level less in the hierarchy 🎉
We rename "Run time" to "Current run time" to prevent confusion
We show "Total run time" and "Time to service" always in full hours → Often requested by customers
Only for "Daily run time" and "Current run time" more resolution makes sense

**Comment by philipptrenz** [comment]
@ReinvdZee Yes, my idea was to have it in the settings. And actually, it's the same. I'm not sure how often service intervals have to be adjusted. Initially I thought the interval adjustment and resetting it should be located at the same place, but VRM also has the interval counter and reset option at the same place, so I moved only the reset functionality over to the counter to be consistent. But I'm not too set in my ways.

<img width="331" alt="Bildschirmfoto 2024-07-19 um 15 51 06" src="https://github.com/user-attachments/assets/e86e1553-de1a-4f53-9115-5dd3cba0fffa">
<img width="335" alt="Bildschirmfoto 2024-07-19 um 15 49 28" src="https://github.com/user-attachments/assets/fb05af74-31cc-45af-82c8-1aa08063a706">

**Comment by ReinvdZee** [comment]
@philipptrenz 
>Yes, my idea was to have it in the settings. 

Ok, I can agree with that. Settings will then look like this:
![image](https://github.com/user-attachments/assets/ff63a68d-6821-422b-9488-4a0669750cc7)

**Comment by ReinvdZee** [comment]
@philipptrenz 

>We rename "Run time" to "Current run time" to prevent confusion

For connected gensets, this field is currently not displayed. Its on `PageGenerator.qml`, only used for the Relay controlled generator start/stop in the main settings menu.

Would the Run time field be useful to show in the connected genset page? It will then hold the run time of the start/stop instance. This value is also used in the daily runtime, which **is** displayed for connected gensets.

**Comment by kwindrem** [comment]
Resetting the service time is done frequently, say when the oil is changed. The service interval is typically set on generator install and remains unchanged. It's a small point and having both in the same menu isn't a big deal.

**Comment by kwindrem** [comment]
You might take a look at the generator overview I did for GuiMods for some ideas. I display three times in the run times area: daily, accumulated and time till next service (if service interval is not 0). The current run time is shown in status along with why the run started. If it's a timed manual run the time till end is also shown.

For the main overview page, the generator tile should show if the generator is running or not. Maybe showing if it was manually started would be valuable to help avoid a generator running forever.

**Comment by ReinvdZee** [comment]
@philipptrenz @kwindrem thanks for your input. I'll add the current runtime to the run time and service menu for completeness.

**Comment by ReinvdZee** [comment]
@philipptrenz 

>@ReinvdZee Yes, my idea was to have it in the settings. 

I've moved the service interval setting over the the run time & service menu because it directs the user to the reset button after setting it, so it makes sense to have it in the same menu.

![Screenshot from 2024-07-31 10-38-39](https://github.com/user-attachments/assets/ba7c458b-25ed-4422-9a11-b7d4223efcb8)

**Comment by ReinvdZee** [comment]
And I also added "Current run time" to the main menu of the genset page: 

![image](https://github.com/user-attachments/assets/d421d1bc-3566-414d-8412-a0b2b4f8b71a)

It is hidden when startstop is not "Running", "Warm-up" or "Cooldown".

**Comment by ReinvdZee** [comment]
The "Run time and service" menu of the relay-controlled genset is also moved to the toplevel (was part of "Settings"):
![image](https://github.com/user-attachments/assets/5e629ff8-08b0-4cce-940f-d454caa33ba2)

**Comment by ReinvdZee** [comment]
Changes are also documented [here](https://docs.google.com/document/d/1NohCfWdM3Aj-FIk6D3GXrWsDlFFxs05h/edit#heading=h.fjr303kg6l60)

**Comment by ReinvdZee** [comment]
VRM does not display the correct runtime yet. VRM always looks at startstop instance 0 for its data. 
This is a known [issue](https://github.com/victronenergy/vrm-portal/issues/314#issuecomment-1980630339)

**Comment by ReinvdZee** [comment]
I came across the menu entry "Accumulated running time since last test run". It was in the setting menu, I relocated it to the "Run time and service menu": 

![image](https://github.com/user-attachments/assets/900c880c-5bbb-4b14-a578-04786602d67c)

**Comment by ReinvdZee** [comment]
We moved the "Settings" submenu of auto start/stop to the toplevel. However, for DC gensets, there is already a settings menu which holds settings related to the charging behavior:

![image](https://github.com/user-attachments/assets/a01fd935-2a84-47cb-a5c8-f56ce68b097a)
![image](https://github.com/user-attachments/assets/ea80f8a1-1bf7-44d6-a875-012463adb001)

Since the two settings menu's are meant to configure completely different things; I'd suggest to rename the settings menu for the DC genset to: "DC genset settings"

@philipptrenz, @martinbosma, agreed?

**Comment by philipptrenz** [comment]
How about moving the DC-related genset settings as a, for example "DC charging parameters" named, entry into the general "Settings" menu – hidden for non-DC gensets, of course?

**Comment by ReinvdZee** [comment]
@philipptrenz Sure we can do that. It does introduce a level of hierarchy, but keeps the top-level cleaner.
The same menu is also used for relay-controlled gensets, but the settings can be hidden there as well.

**Comment by martinbosma** [comment]
@ReinvdZee Sure, sounds good to me
