### ISSUE TITLE
HELLO  SOC VRM 1% 

### ISSUE THREAD

**Issue by Patrick197030100** [victronenergy/venus#1333]
Anglais

Hello on the vrm portal I can modify the minimum soc which goes from 5 to 5 can you change this percentage with a linux command to be able to put soc 1% thank you all

![Screenshot 2024-08-04 at 11-25-08 cerbo de patrick - VRM Portal](https://github.com/user-attachments/assets/df1d170e-ac6f-4bb9-9ff7-512f620205fd)

**Comment by mpvader** [comment]
Hi, this is not for support - sorry. See https://community.victronenergy.com
