### ISSUE TITLE
Move relay-controlled generator settings into device list

### ISSUE THREAD

**Issue by philipptrenz** [victronenergy/venus#1335]
NOTE: will be done in gui-v2 only

As planned in the GUI-v2 settings redesign project, all devices should appear in the device list. For gensets, this is already the case for connected ones. But the pages for relay-controlled ones are still located in the settings as "Generator start/stop".

<img width="481" alt="Bildschirmfoto 2024-08-20 um 13 19 28" src="https://github.com/user-attachments/assets/afbd2faf-5113-4f65-88aa-24fde3e84480">

Additionally, there is a function to track the generator state via a digital input using the "Generator" role. By this, a "Generator" will show up in the device list.

<img width="481" alt="Bildschirmfoto 2024-08-20 um 13 20 02" src="https://github.com/user-attachments/assets/381b29d8-b061-4fc5-8185-e6a970e40ec8">

To harmonize connected and relay-controlled gensets:

- Also the relay-controlled one should be displayed in the device list as soon as relay 1 is configured to "Generator start/stop"
- The device should be merged together with the one from the digital input "Generator" option to accurately display also the state within the same device representation

As it is planned to use the digital input for improving accumulated run time counters for relay-controlled gensets (see https://github.com/victronenergy/venus/issues/337), these two issues should be synced to provide the best user experience.

**Comment by philipptrenz** [comment]
@mpvader any objections?

**Comment by mpvader** [comment]
No objections; but, for gui-v2 pls have a good think how valuable it is there to have it in the device list, since the whole concept of device list is quite of less value than it is in gui-v1

**Comment by ReinvdZee** [comment]
We won't do this now, so this issue can be closed.
