### ISSUE TITLE
SmartSolar 150/100 Charger Short Circuit 20240822

### ISSUE THREAD

**Issue by Yoda101** [victronenergy/venus#1336]
Portal ID: f045da7d75b0
I observed the following overload condition on the SmartSolar Charger which caused the Solar Isolator to trip?
This have been observed a number of times, have limited the charging current 65A but this still occurs
Difficult to determine if the battery BMS or the SolarCharger is the source of the issue.
Any advice?
![image](https://github.com/user-attachments/assets/eaf06171-8d8e-41eb-9e9f-3666976abb41)

Additional Info: 
[Victron SmartSolar Charger Short Circuit_20240822.pdf](https://github.com/user-attachments/files/16723011/Victron.SmartSolar.Charger.Short.Circuit_20240822.pdf)

**Comment by mpvader** [comment]
Hi,

I’m sorry but this issue tracker is not the place to get support.

please contact your dealer or ask on the forum:

https://community.victronenergy.com
