### ISSUE TITLE
doublecheck that data is mounted with the sync parameter

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#134]
Like on the CCGX: it is done there for a reason.

**Comment by izak** [comment]
`meta-venus/recipes-core/base-files/files/ccgx/fstab` has:

```
ubi0:data            /data                ubifs      defaults,noatime,rw,sync    0 0
```

It's not done for the RaspberrryPi yet though.

**Comment by mpvader** [comment]
@jhofstee will do it for beaglebone tonight. We need it.

Makensure to do the same in your rpi branches.

**Comment by izak** [comment]
Fixed in source control, so it will make it into the next Rpi build.

**Comment by mpvader** [comment]
later we decided to no longer mount with the sync option, see here:

https://github.com/victronenergy/meta-victronenergy/commit/25be127d7ac99455283e34e703c774ed8935ef01
