### ISSUE TITLE
vebus updater: Fix error 122 when updating Multi/Quattro firmware in combination with a VE.Bus BMS V2

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#1341]
Error 122 description: " The MK2/MK3 did not respond"
Affected systems: All systems with a VE.Bus BMS V2 
Bug since Venus `v3.41~1 `and `v3.50~7` (vbdup version `v1.13`)
introduced by fix for https://github.com/victronenergy/venus/issues/1325

VictronConnect is also affected.

When updating a Multi/Quattro in a system with a VE.Bus BMS V2 the updater errors out after a time out while waiting for BMS response on a Multi/Quattro only command mistakenly being send to the BMS.

**Comment by vejpasop** [comment]
Fixed in vbdup v1.14 (on the Venus todo)

**Comment by mpvader** [comment]
fixed while ago, iirc in v3.42 or v3.41
