### ISSUE TITLE
Make the choice between gui-v1 and gui-v2 work well

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1342]
For the first official release of gui-v2, which will be part of v3.50, we'll keep gui-v1 to be the default onscreen display.
And it will show a popup for the user to switch to gui-v2 (on the platforms that support that, ie Cerbo and Ekrano).

What needs to be done is:
- [x] ~decide if we stick to the terms "gui-v1" and "gui-v2"~: we're not. Its `Classic UI` and `New UI`
- [x] gui-v1: remove the use of the word beta (@jhofstee )
- [x] gui-v2: remove the use of the word beta (Qinetic, see screenshots below for how it looks now )
- [x] fix wording and things in VRM (El Nino)
- [x] gui-v1: show a toast before stopping it, when switching to gui-v2. (@jhofstee )
- [x] gui-v1: show a popup to tell people about gui-v2 (@jepefe ). Some ideas: here is are new gui, scan this qr code to read the blog about it. and also somewhere note that in case there are issues, there is an option, for now, to still use the old one, and here is where to find that.

**Comment by mpvader** [comment]
![image](https://github.com/user-attachments/assets/fc4679e5-6860-4e93-a65c-60e47cc039fa)

**Comment by mpvader** [comment]
and this is how it now looks in gui-v1

![image](https://github.com/user-attachments/assets/23f8519f-d0bc-4f66-a0e4-b669c8459225)

**Comment by jepefe** [comment]
This is the proposal.

The pop-up shows right after the gui is loaded and asks the user to switch now to the new gui, then there are three possible scenarios
  1. Skip and do not make a choice -> The pop-up keeps showing on every gui restart (power cycle/fw update..)
  2.  Opt to do not switch to gui-v2 yet -> The pop-up is not shown anymore.
  3.  Decide to switch to gui-v2

For scenario #2, a new setting holds if the user has made a choice. We can use this setting on a future release to force the pop-up to be displayed again.

@mpvader Any comments? If you agree I will push the branch and add it to the todo.

https://github.com/user-attachments/assets/743041ee-2b2c-4c3f-97c6-824e2994e2f3

![Screenshot 2024-10-08 at 12 09 31](https://github.com/user-attachments/assets/2f8c7d71-a294-4b51-9b23-8d5bb872ae3b)
![Screenshot 2024-10-08 at 12 09 40](https://github.com/user-attachments/assets/21a77557-a786-4511-9979-36de6624f341)
![Screenshot 2024-10-08 at 12 09 51](https://github.com/user-attachments/assets/9bea27b3-ea63-4726-b667-797ab62534bc)

**Comment by jepefe** [comment]
Applied changes suggested by @mpvader 
Pushed an added to the ToDo.

![Screenshot 2024-10-09 at 11 58 45](https://github.com/user-attachments/assets/b8c5503b-fd89-445e-80d6-444bcd13e9d5)
![Screenshot 2024-10-09 at 11 58 56](https://github.com/user-attachments/assets/f35c3fe9-4861-4449-9845-cb5667900e30)

**Comment by mpvader** [comment]
nice @jepefe . Jeroen will include it in the build

**Comment by mpvader** [comment]
all done
