### ISSUE TITLE
Add warning when accessing html5 app on http:// while security profile is set to weak or secure

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#1351]
it should say that to access this page, user needs to change Settings -> General -> Access to unsecure.

**Comment by mman** [comment]
@mpvader Just as a side note... I have made the necessary underlying changes in the app itself to work correctly in either case, so even if you specify `Secure Profile` `Weak` or `Secure` the `/app` will actually work just fine as of the latest release in Firefox, Chrome, or any other https capable device that is able to enter the Venus password one time... on the MFD it does not make sense as we do not have a keyboard to enter the password, but elsewhere it already works...

**Comment by mpvader** [comment]
understood, nice that that works always @mman .

Still though, when accessed from an MFD, I'd like to give the user a tip on how to make it work.

Jeroen already has an option in mind I think, by serving a page on http://[IP]/app and https://[IP]/app.

Lets leave this to Jeroen for now.

**Comment by mpvader** [comment]
Nice!  One change in the last text

```
To make the Victron app work on such a display, change this setting on the Victron GX device (and not on this MFD):
(New line)
Settings -> …
```

**Comment by mpvader** [comment]
tested, works nicely

![image](https://github.com/user-attachments/assets/8de2b4d4-9c19-4fdb-8c5c-801fcccbb7d4)
