### ISSUE TITLE
Possible add n2k Tank sensor no name ?? 

### ISSUE THREAD

**Issue by carlosgaros** [victronenergy/venus#1355]
I am have 3 device this type one fuel and two tank 1 and tank 2 all good show mfd ray marine and CPN via wifi gateway  
<img width="1440" alt="Zrzut ekranu 2024-10-3 o 21 18 09" src="https://github.com/user-attachments/assets/044f71c4-c789-4213-ba5d-532dc82067e3">

**Comment by mpvader** [comment]
Hi,

could you ask this on https://community.victronenergy.com instead?

thank you!

**Comment by carlosgaros** [comment]
I can ask but no one will add supported device

**Comment by carlosgaros** [comment]
Maybe you need to add classes 80/150 for it to work ?
![fresh water](https://github.com/user-attachments/assets/d11a600f-8db9-47ea-8b74-0544039dc704)

**Comment by carlosgaros** [comment]
> Hi,
> 
> could you ask this on https://community.victronenergy.com instead?
> 
> thank you!

https://community.victronenergy.com/t/nmea2000-tank-sensor-cx5001-not-shown/6402

**Comment by carlosgaros** [comment]
done! Per v3.50~31
