### ISSUE TITLE
New Device: JSON for imitating a Orion XS

### ISSUE THREAD

**Issue by ak68-hub** [victronenergy/venus#1357]
Hallo together,

I´m using the following JSON`s to imitate a Battery/ Solar at Venus OS using the following scripas:
https://github.com/mr-manuel/venus-os_dbus-mqtt-battery?tab=readme-ov-file
https://github.com/mr-manuel/venus-os_dbus-mqtt-solar-charger

**enphase/battery:**
_{
  "Dc": {
    "Power": 0,
    "Voltage": 15,
    "Current": 0
  },
  "Soc": 100
}_

**topic/path/to/dc/pv/json:**
_{
  "Pv": {
    "V": 21.34
  },
  "Yield": {
    "Power": 0
  },
  "Dc": {
    "0": {
      "Current": 0,
      "Voltage": 14.98
    }
  }
}_

this works perfectly: 

![image](https://github.com/user-attachments/assets/24048602-570f-4b58-998f-0c55001cc772)

**Now I would like to imitate a Orion XS (mqtt-dates from a votronic booster !)
Does anybody know, WHERE (path ?) and HOW (format ?) to send the JSON-File ?**

I´ve tested that- but it seems not to be correct:
topic/path/to/dc/dc/json
{
  "Dc": {
    "0": {
      "Current": 0,
      "Power": 0,
      "Voltage": 15.03
    },
    "1": {
      "StVoltage": 14.76
    }
  }
}

**How can I add a device manually ?**

![image](https://github.com/user-attachments/assets/5d43df13-cd70-452e-9b84-3c55b52a5207)

**Must I use the https://github.com/victronenergy/dbus-flashmq for that additionally?**

Thank you
Andreas

**Comment by mpvader** [comment]
hi @ak68-hub please ask the community on https://community.victronenergy.com/, we use these trackers for development. Not support.

And especially for power electronics from other brands we're usually not very keen on spending time on that - I hope you understand.
