### ISSUE TITLE
Generator start/stop: State not reset to stopped when a minimum runtime is configured.

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/venus#1360]
When there is a nonzero minimum runtime configured, the `/State` is not reset to stopped after the condition that started the generator is resolved. The relay is opened, but the displayed state will remain "Stopping" instead of "Stopped".

**Comment by mpvader** [comment]
Introduced when @ReinvdZee ? During v3.50?

**Comment by ReinvdZee** [comment]
@mpvader Yes, this was introduced with the runtime counting improvements. 
It is already fixed an on the TODO
