### ISSUE TITLE
Instructions and removing files with read only filesystem

### ISSUE THREAD

**Issue by nezra** [victronenergy/venus#1376]
New to this whole endeavor, but he instructions that indicate they are updated on Mar 6 here:

https://github.com/victronenergy/venus/wiki/raspberrypi-install-venus-image

Provided instructions for things like the root password changing; and the option to remove the headless file to get the GUI on the screen don't work because the file system is read only. There's no mention anywhere on the page it's read only, or that this error will be encountered by following the instructions; or how to resolve it.

I was able to locate instructions for how to fix this under the modifications page; but since the average person may not be looking to modify it; some warning or something should be on the installation page and directions on how to circumvent it.

**Comment by mpvader** [comment]
Fixed, thanks
