### ISSUE TITLE
MQTT connection status paths Mqtt/Bridges/* incorrect

### ISSUE THREAD

**Issue by wiebeytec** [victronenergy/venus#1377]
I just saw an installation that said this on dbus:

```
 'Mqtt/Bridges/GXdbus/Connected': [],
 'Mqtt/Bridges/GXdbus/ConnectionStatus': 'deactivated',
 'Mqtt/Bridges/GXrpc/Connected': [],
 'Mqtt/Bridges/GXrpc/ConnectionStatus': 'deactivated',
```

While FlashMQ thought this:

``` 
$SYS/broker/bridge/GXdbus/connection_status Connected
$SYS/broker/bridge/GXdbus/connected 1
$SYS/broker/bridge/GXrpc/connection_status Connected
$SYS/broker/bridge/GXrpc/connected 1
```

The last note about the bridges in the FlashMQ log was about a reload with seemingly an unchanged config. So, that's the first thing to try.

Venus OS version v3.50~39.

**Comment by mpvader** [comment]
@wiebeytec this is still in the category “not confusing to users” so no need to hold the release over this?

**Comment by wiebeytec** [comment]
I haven't figured out yet if this can also mean it shows confusing info about actual connection problems.
