### ISSUE TITLE
Wiki Page: Install-venus-packages-on-Debian

### ISSUE THREAD

**Issue by m00str** [victronenergy/venus#1382]

**Comment by m00str** [comment]
On the wiki page https://github.com/victronenergy/venus/wiki/install-venus-packages-on-Debian there are informations provided on how to install Venus packages ontop of a Debian installation.
However, there is only the dunfell/ folder left, where VenusOS packages are provided. No more .deb files.

Is this obsolete or is there a plan to re-release .deb files?

**Comment by mpvader** [comment]
Hi, no plans at the moment. Sorry
