### ISSUE TITLE
Make dup accept multiple serial ports as an argument

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#148]
Will be used for #147.

Ready for review.

@ThiemoVanEngelen pls review these changes, thanks.

https://git.victronenergy.com/ve-apps/dup/commits/matthijs/serial-boost
https://git.victronenergy.com/ve-apps/dup/commits/matthijs/serial-qt

**Comment by ThiemoVanEngelen** [comment]
Looks ok. Maybe improve the comment such that it is clear that mutliple serial ports need to be mentioned between quotes?

**Comment by mpvader** [comment]
yes good idea. Changed and applied to master & the boost branch.

I'll close this issue now. Actual release of dup (& inclusion in Venus) will be done later.
