### ISSUE TITLE
vrmlogger: tank status is missing in the datalist

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#151]
See here for enum definitions:
https://github.com/victronenergy/dbus-adc/blob/a36327d6f733053f07840d3f2df33f93e075c307/software/inc/sensors.h#L98

and here how the gui uses them.
https://github.com/victronenergy/gui/blob/master/qml/PageTankSensor.qml#L68

**Comment by edevries-victron** [comment]
Fixed in vrmlogger v2.80 and dbus-modbustcp v0.9.11

**Comment by mpvader** [comment]
Added in v2.08~1
