### ISSUE TITLE
Device page for onboard tank level an temperature sensor input always shows "Connected Yes"

### ISSUE THREAD

**Issue by jepefe** [victronenergy/venus#154]
The device page for the onboard tank level and temperature sensors shows "Connected Yes" even when there is not any tank level/temperature sensor attached and this is confusing for the users.

![screen shot 2017-06-16 at 08 46 02](https://user-images.githubusercontent.com/6424631/27216796-7c34303a-5277-11e7-9b8f-2a8e89723e95.png)

Device page is generic and is used for all the devices, a possible solution could be add an "onBoardDevice" property and hide the "Connected" item when is set to true.

**Comment by mpvader** [comment]
(can be reopened if its becoming an urgent problem)
