### ISSUE TITLE
Raspberry Pi - Relay function doesnt show in menu

### ISSUE THREAD

**Issue by sascha-hemi** [victronenergy/venus#163]

**Comment by mpvader** [comment]
Hi Sascha, @jhofstee and @izak also answered [your question on the mailing list](https://groups.google.com/d/msg/victron-dev-venus/nqkpANtRCBU/nmYpv7NvBQAJ), did you look into that?

**Comment by mpvader** [comment]
Closing this, no response

**Comment by sascha-hemi** [comment]
I can't see any comments. :/

**Comment by mpvader** [comment]
Hi @sascha-hemi, this has no priority for us to fix in the main raspberrypi image.

You could still make it work yourself, on a certain gpio pin to which you wired a relay. See @jhofstee his instructions for that on the venus-dev mailinglist.
