### ISSUE TITLE
Add IP router support

### ISSUE THREAD

**Issue by Gussoh** [victronenergy/venus#164]
## Background
Many users of vehicles today require a networking and wifi router for handling their devices connectivity issues. In small installations a vehicle grade router is very expensive and adds another load to the list of battery consuming devices.

When cellular support is working ok, the Venus platform would be a great way to remove the router and let Venus handle it. This is especially great for the Venus-GX (and maybe Raspberry pi 3?) which both have wlan-support and could work as a wifi router.

## Features
Most users don't need all the features a "complete" router supports. Few people use features like port forwarding and such things. What most people need is just a dhcp-server and packet forwarding enabled. Some vehicles require some way of adding static leases for some devices but these are most likely quite few.

Here is a comment from a potential user (me):
> As a system designer it would be great for us to remove the router in all of our boats! Then we could also use the Venus platform for waking the rest of the system up from sleep if a user would like to turn their heater or refrigerator on remotely! - CTO of Yacht Defined

## Future
Future goals which perhaps should be good to know for consideration:
In the future we are also aiming for adding support for the ability to use one of the wlans as client to another network and route that to the local wifi. This is for vehicles which are sometimes parked in a driveway or harbour where there is wifi available and sometimes the vehicle is out driving and have to use the cellular network. This system requires some kind of interface for managing the system which makes it more complex.

**Comment by mpvader** [comment]
[venusRouter_5.pdf](https://github.com/victronenergy/venus/files/2188440/venusRouter_5.pdf)


closing, to much support. In case we ever will re-open this, look at above designs, flows & wireframes.
