### ISSUE TITLE
Improve remote console for kiosk mode

### ISSUE THREAD

**Issue by jepefe** [victronenergy/venus#167]
To make the remote console work properly in devices running in kiosk mode some changes needs to be done in the built-in javascript VNC client: https://github.com/victronenergy/javascript-vnc-client

- [x] Add reconnect button
- [ ] Add reconnection timer?   <-- will not be done in this iteration; see below.
- [ ] Add "Stay signed-in" checkbox when remote console is protected by password  <-- will also not be done
- [ ] Add full screen button   <-- will also not be done

**Reconnection**
A reconnection mechanism is necessary as the remote console only supports one session. In case that someone connects to the remote console via the VRM portal the LAN remote console session will be closed. 
This can be fixed by adding a "Reconnect" button when the connection is closed but we can also implement a configurable timer that will reconnect after X minutes.

**Comment by anilRghatikar** [comment]
Better is reconnection timer -  Only if No remote user is logged in otherwise He will get booted out .

Also Full screen ( without keys) will be a nice option

**Comment by mpvader** [comment]
This will be much easier if we have a different VNC server, see #292

**Comment by mpvader** [comment]
This is being picked up now. For Remote Console on LAN (html/js files on the Venus-device) and on Remote Console on VRM.

A reconnection timer will not be implemented, because of lock-out risks. Just a button is enough for now.

Once we have a new VNC server, that allows for multiple connections at the same time, we can look at auto-reconnecting.

**Comment by mpvader** [comment]
The reconnect button is in VRM for a while already.
I'm adding it for Remote Console on LAN now.

I'll leave the issue open; to be closed once its in a Venus build.

**Comment by mpvader** [comment]
The one out of four items that we agreed to implement have been implemented (a long time ago) in both Remote Console on VRM and Remote Console on LAN.

Other three are decided on to not be done. Closing.
