### ISSUE TITLE
cgwacs: et340 power and current measurements are not signed

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#174]
https://www.victronenergy.com/live/energy-meters:et340#comment-3428381148

**Comment by edevries-victron** [comment]
Issue confirmed: dbus-cgwacs should set the measurement type for ET340 meters. This does not happen, however. Consequence is that the power (and current) provided by the meter are always positive. 

This causes problems if the meters are used as grid meters in systems that are allowed to feed power back to the grid (for example ESS systems).

**Comment by edevries-victron** [comment]
Fixed with dbus-cgwacs v1.8.3

**Comment by mpvader** [comment]
@edevries-victron this not only causes wrong figures on VRM, but also quite weird, or totally bizarre? behaviour of ESS, right?

**Comment by mpvader** [comment]
@edevries-victron is below a good description for in the known issues?

ESS - There is bug when using the ET340 meter. Power measurements are not signed, because of which the system cannot make a distinction between selling and buying energy. As a result the ESS system might dump the contents of the entire battery into the grid. The problem was there since the start, and will be fixed in v2.08.

**Comment by edevries-victron** [comment]
>@edevries-victron this not only causes wrong figures and graphs on VRM, but also quite weird, or even totally bizarre(?), behaviour of ESS. Right?
Correct. Whenever there is feedback to the grid, the CCGX will instruct the Multi to discharge at maximum rate.
> @edevries-victron is below a good description for in the known issues?
Yes.

**Comment by mpvader** [comment]
Wat gebeurd er als je keep batteries charged als instelling hebt? werkt het dan wel goed?

**Comment by jhofstee** [comment]
included in v2.08~14

**Comment by edevries-victron** [comment]
Daar kan het ook mis gaan. Bijvoorbeeld als er een PV inverter in het systeem zit die meer vermogen levert dan de Multi kan gebruiken om de accu te laden. Je gaat dan alsnog terug leveren.

**Comment by edevries-victron** [comment]
Check with new grid meter: the default measurement mode is A (but we need B to measure feedback to grid).

**Comment by mpvader** [comment]
Fixed in v2.08
