### ISSUE TITLE
Temperature is always shown in Celsius

### ISSUE THREAD

**Issue by jepefe** [victronenergy/venus#178]
Temperature is published in Celsius on DBus whatever the unit set on the BMV display.

Some options are:
  * Make the BMV temperature unit setting available on DBus and then convert the temperature accordingly on the GUI.
  * Create new settings on Venus to define the unit to use for temperature but also for others like volume or speed. These settings can be added on the "Display & language" page.

**Comment by mpvader** [comment]
Note that there are other temperatures too, for example the temperature inputs on the Venus GX

**Comment by mpvader** [comment]
The solution is to have a system wide 'units' setting in Venus, out which Temperature is the only real important one I can think of.

The next one would be tank volume, but that we do already, but in a non-generic way.
