### ISSUE TITLE
Backlight remains off when using a touch screen

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#179]
Low priority issue, since we don't directly support touch-screen devices yet.

When using a touch screen interface on the Rpi, and enabling the screensaver in `/etc/venus/blank_display_device`, the screen does not come back on if you touch the screen later.

Fixing this should be as simple as catching the mouseEvent and doing the same thing we do now on a keypressEvent.

Untested (but compiling) code is in the `feature/touchscreen-wakeup` branch of the gui project.

**Comment by mansr** [comment]
That branch solves the problem on the CANvu500 device.

**Comment by mpvader** [comment]
ok thanks; I've listed the branch for inclusion in master.

**Comment by mpvader** [comment]
Fixed in gui v3.5.1, added in Venus v2.12~1
