### ISSUE TITLE
gridless octo: test bluetooth

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#191]
Its hard for this to not work, but before ordering the next PCB version it needs to be tested.

@mansr pls test this.

WiFi has been tested by Unipoin.

**Comment by mansr** [comment]
The built-in bluetooth is miserable in the same way as on Venus GX. With a USB bluetooth dongle it works fine.

**Comment by mpvader** [comment]
@mkrenzke miserable means that it has miserable Bluetooth reception like the Venus GX.

I hoped/expected it to be good, since you also reported that the wifi reception on the Gridless Octo is good. Unlike wifi on the Venus GX. Any ideas or comments?

**Comment by mkrenzke** [comment]
That's bad news. I had the same expectations.

@fhuebner is already looking into it.

**Comment by mkrenzke** [comment]
@mansr: How do you test bluetooth connectivity?

**Comment by mansr** [comment]
A basic check of reception can be done with these commands:
```
hciconfig hci0 up
hcitool -i hci0 lescan
```
If there are any devices transmitting nearby, their MAC addresses and names are printed.

**Comment by mkrenzke** [comment]
@mansr: Thank you!

With `btmon` we see signal strength of -74 dB even for devices in 10 meters distance with the built-in module. Which is not too bad.

Which antenna do you use? The one we sent or any other?
What is your testing scenario?

**Comment by mansr** [comment]
I didn't receive an antenna, so I tried with a couple I had lying around. The transmitting device is less than a metre away, so I'd expect it to work even without a proper antenna.

**Comment by mkrenzke** [comment]
When I scan for BLE networks (with advertising on) with my mobile phone I get -35 dB in 1 meter.

![image](https://user-images.githubusercontent.com/31248358/30642070-9dea6180-9e09-11e7-81b6-f09587b3ba19.png)

Without antenna it is about -80 dB in 1 meter.

**Comment by mpvader** [comment]
discussion is continued here https://github.com/victronenergy/venus/issues/207
