### ISSUE TITLE
Tank volume is limited to 1000 liters, 219 gallons or 264 US gallons

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#209]
On the Venus GX, you cannot set tank volume larger than 1000 liters or the associated conversions in other units.

**Comment by izak** [comment]
The tank capacity is limited to one cubic meter in [code][1]. It should be easy enough to change it, but first I'd need to know if there was a specific reason for choosing 1 cubic meter.

[1]: https://github.com/victronenergy/dbus-adc/blob/master/software/inc/sensors.h#L51

**Comment by mpvader** [comment]
@izak Lets increase the max to some huge number

**Comment by izak** [comment]
The NMEA2000 packet has 4 bytes for this, with a resolution of 0.1, which pegs the maximum at a little over 400 million liter. A small tanker starts at 10 000 DWT, which is ten million liters assuming it is water. I think we should be fine setting it to 1 million liters, or 1000 cubic meter.

**Comment by mpvader** [comment]
Ok

**Comment by izak** [comment]
Just bumping up the maximum seems to work perfectly. I'll make a pull request for inclusion into the main release.

![selection_012](https://user-images.githubusercontent.com/851549/31811470-fc6dc700-b57f-11e7-87e0-fe0a3c437f53.png)

**Comment by mpvader** [comment]
You've full access now, please make the release of dbus-adc yourself. See previous tags for how it's done

**Comment by mpvader** [comment]
In v2.12~5
