### ISSUE TITLE
VRM App: battery historical data is not shown

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#210]
bug was introduced in venus v2.09, vrmlogger v2.84, when I changed the send-type of the ActiveBatteryService from `configChange` to `AlwaysAndOnEvent`:
* datalist: change system/ActiveBatteryService to AlwaysAndOnEvent. Reduces the number of config changes.
* https://git.victronenergy.com/ccgx/dbus_vrm/commit/b9e2617eff76ea1b6ff100db1e6a9a4797b98c0a

As discussed with @wiebeytec: we'll fix it by making the backend always handle the value, ie not only when part of a config change.

**Comment by wiebeytec** [comment]
Fix  [committed](https://git.victronenergy.com/venus-remote-systems/vrm-log-backend/commit/6f9730343e3183fad8d156c1b2569c1ed40c58df) and deployed.
