### ISSUE TITLE
Add GlobalSat MR-350PS4 (5Hz) Serial GPS Receiver Support

### ISSUE THREAD

**Issue by MikeShipp** [victronenergy/venus#221]
The MR-350PS4 (5Hz) only appears to work at 115200baud.

This could be resolved by adding "start $args -b 115200" to the end of /opt/color-control/gps-dbus/start-gps.sh

**Comment by mpvader** [comment]
https://groups.google.com/d/msg/victron-dev-venus/1Hgh1BQuVYY/S0xN0aCaCwAJ

**Comment by mpvader** [comment]
in v2.12~11
