### ISSUE TITLE
update to linux 4.9 on ccgx

### ISSUE THREAD

**Issue by mansr** [victronenergy/venus#223]
Issues to be resolved, list from OE recipe:
- [x] Splashscreen
- [x] Backlight
  - Fixed with new driver
- [x] CAN-bus phy driver power enable
- [x] Test USB stability
  - Reading an entire 8GB flash stick works without problems
- [x] Check which modules are not needed and which ones are
- [x] Update gpio-export package
- [x] Update ccgx.conf with new backlight name

**Comment by jhofstee** [comment]
mans/linux-ccgx-4.9 is included in v2.20~3

**Comment by mpvader** [comment]
🎉
