### ISSUE TITLE
gpio: change & use symlinks created by gpio-export

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#228]
- [x] change gpio export to make symlinks to gpio instead of gpio/value (jeroen)
- [x] rework [mkx_pins.sh](https://github.com/victronenergy/meta-victronenergy/blob/mans/linux-ccgx-4.9/meta-venus/recipes-bsp/gpio-export/files/ccgx/mkx_pins.sh) accordingly (mans)
- [x] change systemcalc to access & enumerate relays via gpio-export symlinks (izak)
- [x] drop VE_RELAYS from the machine.conf files (jeroen)
- [x] update digital inputs, it needs to add /value itself (izak)

**Comment by mpvader** [comment]
the systemcalc change needs to be done in two branches, bol & master ..

**Comment by mpvader** [comment]
gpio_pins.sh change:
https://github.com/victronenergy/meta-victronenergy/commit/6ea89fc2cad4d80ad53137785c21182c6070d4af

**Comment by mansr** [comment]
mkx_pins.sh done:
victronenergy/meta-victronenergy@57a1378ef7e2c8bf9851a47d497f2fb7c1ac9e7f

**Comment by izak** [comment]
digitalinputs done:
izak/dbus-digitalinputs@79826a1763dd0aa25bba3baa2d5cbc406f15b81a

**Comment by izak** [comment]
dbus-systemcalc-py done:
victronenergy/dbus-systemcalc-py@3ab4170da390c3bb5d7f7aa8e5f8d307bad9f056

dbus-systemcalc-py-bol done:
victronenergy/dbus-systemcalc-py@2a7ec7a8115eaf6783432303c5ca04fc174951ad
