### ISSUE TITLE
/data/venus informational tree is missing on Raspberry Pi

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#236]
On the other machines we store information in files, for example `venus/installer-version` stores the version in use when this system was installed.

We should add `/data/venus/image-version` for the Raspberry Pi and similar architectures.

- [x] Add `/data/venus/image-version` for the Raspberry Pi (izak)
- [ ] Add `/data/venus/image-version` for the NanoPi (@mansr)

**Comment by izak** [comment]
I made this change for the Rpi in victronenergy/meta-victronenergy@3d17b541241fa2a41156fb203279b9db0fd0d4e1. It can possibly be used almost as-is for the nanopi.

**Comment by mpvader** [comment]
@mansr this no longer applies to nanopi, right?

**Comment by mansr** [comment]
No, the new version with eMMC doesn't need this.
