### ISSUE TITLE
gui ESS reason codes: small improvements

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#239]
- [ ] box should be moved forward
- [ ] change the color, red indicates an error. there is no error, lots of systems will show these reason codes every day
- [ ] also on a more general note the layout can be a bit improved I think, @jepefe  ?

![image](https://user-images.githubusercontent.com/5200296/34297632-98217992-e719-11e7-9039-6f8730e24dae.png)

Reason codes:

* #1: SoC is low
* #2: BatteryLife is active
* #3: BMS disabled charging
* #4: BMS disabled discharge
* #5: Slow Charge in progress (part of BatteryLife, see manual)
* #6: User configured a charge limit of zero.
* #7: User configured a discharge limit of zero.

**Comment by jepefe** [comment]
I've made some changes and pushed to improve_overview_ess_codes branch. 
![screen shot 2018-01-29 at 17 49 37](https://user-images.githubusercontent.com/6424631/35567510-9dd6e4b0-05c5-11e8-8689-e60a42061437.png)

**Comment by mpvader** [comment]
@izak, pls check and when you agree schedule this for inclusion for v2.12
