### ISSUE TITLE
mqtt: from some machines the first messages after subscription have payload with {value: null}

### ISSUE THREAD

**Issue by sztupi** [victronenergy/venus#248]
A weird issue we're having: 
On a new connection (with random-generated client session id, so there should be no previous state) we subscribe to a few channels of a portal, and we expect the first notifications to have value of the last known value of the topic.
This works exactly as expected on our development machines, but running the same code (same docker binary, same parameters), on production system (EC2 nodes on AWS) result in the first messages to be '{"value": null}';
Also, it seems no subsequent notification (of the correct value) arrives if the underlying value doesn't changes. Also, trying to trigger a notification by sending an empty message to the corresponding "R/<portal-id>/<subtopic>" topic doesn't work either.

Did anyone seen this or similar behaviour?

**Comment by mpvader** [comment]
@wiebeytec pls look into this.

**Comment by mpvader** [comment]
For chatting with sztupi and his colleagues, see venus-moixa in slack. We're running a project together.

**Comment by wiebeytec** [comment]
@sztupi did you see my messages in Slack? If possible, I would like to do some interactive debugging.

**Comment by wiebeytec** [comment]
We discussed this in Slack. There are non-ascii bytes included in topic path names.

@sztupi said:

> I'm about 90% sure it's the Haskell->libmosquitto FFI binding we use; actually I traced the problem to a few lines of code that probably are the culprit. will try to reproduce / fix / send a pull request to the binding in next few hours. will update you (and will close the issue it solves it) as I know more.

**Comment by sztupi** [comment]
As mentioned above, the issue was with the C bindings (not marshalling strings properly), nothing to do where the code was running from.
