### ISSUE TITLE
mqtt-rpc: are the files in the cache also deleted?

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#250]
or does the /data partition eventually run out of space

**Comment by wiebeytec** [comment]
I'll write an auto-clean, in start-up and daily timer or something, deleting files order than x.

**Comment by wiebeytec** [comment]
I pushed a fix to the mva/various3 branch.

**Comment by mpvader** [comment]
all this is in mqtt-rpc v1.04. waiting for inclusion in Venus
