### ISSUE TITLE
Capabilities for hdmi / or other LCD on own hardware?

### ISSUE THREAD

**Issue by neoneddy** [victronenergy/venus#251]
I haven't seen any information on that.  Or is the screen options only for the CCGX ?

**Comment by mpvader** [comment]
hi you could use hdmi, at least on a raspberrypi it works fine. Please use the developers mailing list for questions like this: we prefer to keep this issue list for real issues, not questions.

thanks!

**Comment by neoneddy** [comment]
My apologies, I just stumbled onto this, I didn't know there was a mailing list.

**Comment by mpvader** [comment]
no problem!

https://groups.google.com/forum/#!forum/victron-dev-venus
