### ISSUE TITLE
installing additional python modules on Venus GX doesn't work

### ISSUE THREAD

**Issue by mrabbah** [victronenergy/venus#260]
Hello
following the wiki : installing additional python modules, on Venus GX, its seem doesn't work, because opkg need space and / is fully used, even if specify another directory: -d scratch and a volatil cache: --volatile-cache, it install package but when we run: python ez_setup.py, it will not work with the message: ImportError: No module named distutils
Perhaps you must update documentation for Venus GX

Thanks

**Comment by mpvader** [comment]
Duplicate with https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!msg/victron-dev-venus/12pSOUSx_qA/rJTnF_BYBgAJ
