### ISSUE TITLE
Fronius device type is no longer reported

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#264]
For v2.11 and beyond, Venus would report the Fronius device type. On VRM as in screenshot below, and probably also somewhere in the gui:

![image](https://user-images.githubusercontent.com/5200296/36199355-9fd12a4a-1179-11e8-81c7-14f297f8274f.png)

In v2.12 its no longer shown transmitted to VRM.

Perhaps because we switched from JSON to ModbusTCP and now this parameter is missing?

If not easy to get back, we can also just accept this as the new status quo.

In parallel, right now the VRM Portal shows `Fronius device type: False` for v2.12. VRM Portal code will be changed to simply hide that line instead.

**Comment by izak** [comment]
The `/FroniusDeviceType` path was removed in October 2017 when version 1.2.0 of dbus-fronius was released by my predecessor, in commit `09f47f`. That coincided with modbus/sunspec work. From a cursory inspection of the code it seems the Inverter object was simplified to also handle sunspec models and the Fronius Specific path was therefore removed. I suspect the ProductName was deemed to be sufficient.

It appears fairly trivial to get it back. Just a bit of inheritance magic. Should we do it?
