### ISSUE TITLE
color control backlight sometimes set too bright

### ISSUE THREAD

**Issue by jhofstee** [victronenergy/venus#266]
The 4.9 linux kernel correctly sends a pulse train to the lt3593. When a nsleep is interrupted for more the 128us the lt3593 interprets that as two different pulse trains and the backlight becomes two bright. This is relatively easily reproduced, just try  echo 4 > /sys/class/backlight/backlight/brightness multiple times while watching the screen.

**Comment by mpvader** [comment]
is this solved by this commit?

https://github.com/victronenergy/linux/commit/693f9eadf6b923fe30b4a09207ba14ca959136d7
