### ISSUE TITLE
Question/Issue

### ISSUE THREAD

**Issue by stevebit** [victronenergy/venus#269]
Hi guys,
I'm new to this.  I was wondering if it is possible to set the Generator start/stop AC Load conditions from a raspberrypi3 and if so would you be able to point me in the direction of where the documentation is for those commands.

If it can't be done through the Pi is it possible to do it another way.  I am trying to dynamical charge/discharge a battery.

Cheers,
Steve

**Comment by mpvader** [comment]
Hi Steve, I see that you also asked this on the mailing list, which is the better place for such a question: then community can answer. I'll close this issue, thanks.
