### ISSUE TITLE
mqtt-rpc: no connected devices found wording

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#294]
Replace `No connected devices found` with `No devices found that can be firmware updated remotely`.

![image](https://user-images.githubusercontent.com/5200296/42712056-6a1ada72-86ea-11e8-98cc-4e5853aec162.png)

Seen on https://vrm.victronenergy.com/installation/1039/settings/firmware-update, which has devices, but no VE.Can and VE.Direct devices.

**Comment by mauritsvdvijgh** [comment]
Will be in master with the other changes, addressed here: https://gitlab.trimm.nl/fronteers/victron-gonzales-frontend/commit/6a3015cbe7d9ed8fbdcafd897f9b5c2a17fcb564

**Comment by mauritsvdvijgh** [comment]
This change is live on production so this issue can be closed.

**Comment by mpvader** [comment]
![image](https://user-images.githubusercontent.com/5200296/42804922-a73fd002-89aa-11e8-8e2c-20931385e929.png)
