### ISSUE TITLE
Raspberry Pi 3 B wifi dropouts

### ISSUE THREAD

**Issue by raindog1906** [victronenergy/venus#297]
Having issues with a RPI 3 B running Venus. 
The wifi drops out easily and doesn't reconnect - this is a pain for remote monitoring. 
Would it be possible to slap some code onto it to reboot when the wifi drops out? I found this post that seems relevant:

https://weworkweplay.com/play/rebooting-the-raspberry-pi-when-it-loses-wireless-connection-wifi/

Many Thanks
Gareth

**Comment by jhofstee** [comment]
you can add ping = <ip-addr> to watchdog.conf, see https://www.systutorials.com/docs/linux/man/5-watchdog.conf/

**Comment by jhofstee** [comment]
This is also available in the gui since a long time, settings -> VRM online portal -> Reboot device when no contact.
