### ISSUE TITLE
mqtt-rpc: empty scan after successful update

### ISSUE THREAD

**Issue by jhofstee** [victronenergy/venus#299]
After a successful update there are sometimes no products found. Rescanning makes them appear again.

**Comment by mauritsvdvijgh** [comment]
If it happens again, please update this issue with some details (when it happened and on which site it happened), so I can investigate.

**Comment by mpvader** [comment]
@mauritsvdvijgh try on 
https://vrm.victronenergy.com/installation/13535/overview

We released a new firmware version for the MPPTs just now: you can try 10 orso times without having to resort to manual file selection.

**Comment by mauritsvdvijgh** [comment]
seems offline today.

**Comment by mauritsvdvijgh** [comment]
Updated them all, did not notice any weird behavior/emtpy device lists.

Used macos and firefox.

Did you perhaps have multiple tabs open on the firmware-update page or something?

**Comment by mpvader** [comment]
Closing; we'll re-open this when we see it again.
