### ISSUE TITLE
Complete canvu500 support

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#310]
- [x] The splash screen thats usually loaded by the bootloader (?) is missing.
- [x] The splash screen shown by the gui is not shown in right resolution, (you see it four times).
- [x] VE.Direct & VE.Bus on Expander board (does this need any work at all?)
- [x] IO on Expander board (Relay out, Digital in only. Analog in will not be implemented now)
- [x] Add ftdi_sio module to the image
- [ ] Test it to the [things to test document](https://github.com/victronenergy/venus-private/wiki/things-to-test)

**Comment by mkrenzke** [comment]
What about optimizing user experience of touch gestures?

**Comment by mansr** [comment]
For the splash screen, can someone provide a render at 800x480 pixels?

**Comment by mpvader** [comment]
> For the splash screen, can someone provide a render at 800x480 pixels?

I asked Marianka.

**Comment by mpvader** [comment]
Closing. Its all done; product is selling.
