### ISSUE TITLE
QA for CCGX kernel 4.14

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#322]
Another extensive QA, this time because switch to kernel 4.14. There are no other changes to test.

### Other machines

- [x] Other machines (briefly login to Venus GX, check that it boots / updates.

#### general check on various test systems:

- [x] svstat
- [x] vrm
- [x] gui
- [x] remote console on LAN
- [x] remote console on VRM

#### WiFi:

- [x] Zyxel NWD2105 - BPP900100100 - USB 0586:341e - RT chipset 3070, rev 0201, RF chipset 0005
- [ ] Startech USB300WN2X2D - BPP900200100 - USB 148f:3572 - RT chipset 3572, rev 0223, RF chipset 0009
- [ ] Nano USB - BPP900100200 - USB 148f:5370 - RT chipset 5390, rev 0502, RF chipset 5370
- [ ] Gembird WNP-UA-002 - BPP900200200 - USB 148f:3072 - RT chipset 3071, rev 021c, RF chipset 0008

Venus GX & similar only:

- [ ] WiFi Access point

#### Other USB:

- [ ] Helmsjlund RS485 isolated USB:
- [x] GX GSM Modem in menu
- [x] GX GSM Internet connection / ppp
- [x] GX GSM GPS

#### USB & sdcard automounting & storage

1. Insert media 
2. disconnect network (ethernet/wifi)
3. check in Settings -> VRM Logger that it recognizes the stick and writes to it

- [ ] USB stick
- [ ] SD card

- [x] check consequences of: ubifs_read_superblock: on-flash format version is w5/r0, but software only supports up to version w4/r0

#### External interfaces
CAN:
- [x] CAN In general (ie. connects to solar charger)
- [ ] CAN Baudrate switching
- [ ] CAN load test

VE.Bus:
- [x] VE.Bus mk3
- [x] VE.Bus panel detect
- [x] VE.Bus standby

IO:
- [ ] Relays
- [ ] Digital inputs
- [ ] Analog inputs

Other:
- [x] Built-in VE.Direct ports
- [ ] Built-in RS485 port(s)

#### Updating
- [x] Update online (change the build date in `/opt/victronenergy/version` to an earlier one; to trick system to accept a downgrade).
- [ ] Update offline (sdcard)
- [x] Boot into the backup image

#### RTC
- [x] reading time from rtc (check boot log)
- [x] writing time to rtc

#### Other
- [ ] Crond: automatic update
- [x] Diskspace
```
root@ccgx:~# df
Filesystem           1K-blocks      Used Available Use% Mounted on
ubi0:rootfs1            190680     97608     93072  51% /
devtmpfs                110780         4    110776   0% /dev
tmpfs                   119484       188    119296   0% /run
tmpfs                   119484       268    119216   0% /var/volatile
ubi0:data                29032      4460     23080  16% /data

```

#### Watchdog
- [x] `killall watchdog` should lead to a reboot. If not, check CONFIG_WATCHDOG_NOWAYOUT kernel config.
- [x] `killall -9 watchdog` should also lead to a reboot.
- [ ] Minimum time between killing the watchdog, aka stopping the userland -> kernel watchdog resets, and the reboot should be enough for the system to shutdown properly. See [this commit](https://github.com/victronenergy/meta-victronenergy/commit/7e48c8182dac8f0b57b7decfabcb0f858a7cff41)
- [x] boot reason is to be stored in /var/tmp/last_boot_type, and comply with [this list](https://github.com/victronenergy/venus/wiki/watchdog#boot-type-codes-as-sent-to-vrm)
- [ ] watchdog should be enabled already early in boot (u-boot?)

There is more information about the watchdog in the [watchdog page](https://github.com/victronenergy/venus/wiki/watchdog).

#### Special images
- [ ] Installer image
- [ ] Upgrade image (ccgx only)

**Comment by mpvader** [comment]
Seen om Matthijs CCGX (not reproducable, and WiFi did still work):

A quick google search yielded this link, might be related, or not:
https://lkml.org/lkml/2018/8/21/396

```
[   25.812164] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   30.079192] 
[   30.079285] ======================================================
[   30.079327] WARNING: possible circular locking dependency detected
[   30.079374] 4.14.67 #1 Not tainted
[   30.079404] ------------------------------------------------------
[   30.079443] wpa_supplicant/782 is trying to acquire lock:
[   30.079480]  ("%s"wiphy_name(local->hw.wiphy)){+.+.}, at: [<c0142268>] flush_work+0x180/0x280
[   30.079582] 
[   30.079582] but task is already holding lock:
[   30.079623]  (&local->mtx){+.+.}, at: [<bf0d5124>] ieee80211_request_scan+0x20/0x44 [mac80211]
[   30.080645] 
[   30.080645] which lock already depends on the new lock.
[   30.080645] 
[   30.080701] 
[   30.080701] the existing dependency chain (in reverse order) is:
[   30.080750] 
[   30.080750] -> #2 (&local->mtx){+.+.}:
[   30.080835]        mutex_lock_nested+0x1c/0x24
[   30.081355]        ieee80211_scan_work+0x20/0x744 [mac80211]
[   30.081424]        process_one_work+0x2a0/0x74c
[   30.081464]        worker_thread+0x50/0x5a8
[   30.081504]        kthread+0x15c/0x164
[   30.081548]        ret_from_fork+0x14/0x20
[   30.081580] 
[   30.081580] -> #1 ((&(&local->scan_work)->work)){+.+.}:
[   30.081654]        worker_thread+0x50/0x5a8
[   30.081690]        kthread+0x15c/0x164
[   30.081724]        ret_from_fork+0x14/0x20
[   30.081753] 
[   30.081753] -> #0 ("%s"wiphy_name(local->hw.wiphy)){+.+.}:
[   30.081825]        flush_work+0x1a8/0x280
[   30.081860]        __cancel_work_timer+0x100/0x1d4
[   30.082258]        __ieee80211_start_scan+0x4e0/0xc54 [mac80211]
[   30.082612]        ieee80211_request_scan+0x2c/0x44 [mac80211]
[   30.083500]        nl80211_trigger_scan+0x6cc/0x960 [cfg80211]
[   30.083587]        genl_rcv_msg+0x2d8/0x3a4
[   30.083628]        netlink_rcv_skb+0x9c/0xe8
[   30.083666]        genl_rcv+0x24/0x34
[   30.083702]        netlink_unicast+0x16c/0x1f0
[   30.083739]        netlink_sendmsg+0x358/0x39c
[   30.083787]        sock_sendmsg+0x14/0x24
[   30.083824]        ___sys_sendmsg+0x204/0x214
[   30.083864]        __sys_sendmsg+0x40/0x6c
[   30.083906]        ret_fast_syscall+0x0/0x28
[   30.083938] 
[   30.083938] other info that might help us debug this:
[   30.083938] 
[   30.083993] Chain exists of:
[   30.083993]   "%s"wiphy_name(local->hw.wiphy) --> (&(&local->scan_work)->work) --> &local->mtx
[   30.083993] 
[   30.084101]  Possible unsafe locking scenario:
[   30.084101] 
[   30.084143]        CPU0                    CPU1
[   30.084173]        ----                    ----
[   30.084202]   lock(&local->mtx);
[   30.084238]                                lock((&(&local->scan_work)->work));
[   30.084291]                                lock(&local->mtx);
[   30.084335]   lock("%s"wiphy_name(local->hw.wiphy));
[   30.084378] 
[   30.084378]  *** DEADLOCK ***
[   30.084378] 
[   30.084428] 4 locks held by wpa_supplicant/782:
[   30.084458]  #0:  (cb_lock){++++}, at: [<c05cdcc8>] genl_rcv+0x14/0x34
[   30.084528]  #1:  (genl_mutex){+.+.}, at: [<c05cde34>] genl_rcv_msg+0x14c/0x3a4
[   30.084601]  #2:  (rtnl_mutex){+.+.}, at: [<bf030d9c>] nl80211_pre_doit+0xec/0x180 [cfg80211]
[   30.085126]  #3:  (&local->mtx){+.+.}, at: [<bf0d5124>] ieee80211_request_scan+0x20/0x44 [mac80211]
[   30.085904] 
[   30.085904] stack backtrace:
[   30.085956] CPU: 0 PID: 782 Comm: wpa_supplicant Not tainted 4.14.67 #1
[   30.086000] Hardware name: Generic AM3517 (Flattened Device Tree)
[   30.086071] [<c010e13c>] (unwind_backtrace) from [<c010c6a8>] (show_stack+0x10/0x14)
[   30.086140] [<c010c6a8>] (show_stack) from [<c01699f4>] (print_circular_bug.constprop.20+0x2e0/0x2e8)
[   30.086206] [<c01699f4>] (print_circular_bug.constprop.20) from [<c0167ce4>] (__lock_acquire+0x15d8/0x1a08)
[   30.086270] [<c0167ce4>] (__lock_acquire) from [<c0168a28>] (lock_acquire+0xe0/0x214)
[   30.086336] [<c0168a28>] (lock_acquire) from [<c0142290>] (flush_work+0x1a8/0x280)
[   30.086397] [<c0142290>] (flush_work) from [<c0144300>] (__cancel_work_timer+0x100/0x1d4)
[   30.086887] [<c0144300>] (__cancel_work_timer) from [<bf0d3944>] (__ieee80211_start_scan+0x4e0/0xc54 [mac80211])
[   30.087589] [<bf0d3944>] (__ieee80211_start_scan [mac80211]) from [<bf0d5130>] (ieee80211_request_scan+0x2c/0x44 [mac80211])
[   30.088581] [<bf0d5130>] (ieee80211_request_scan [mac80211]) from [<bf032a74>] (nl80211_trigger_scan+0x6cc/0x960 [cfg80211])
[   30.089051] [<bf032a74>] (nl80211_trigger_scan [cfg80211]) from [<c05cdfc0>] (genl_rcv_msg+0x2d8/0x3a4)
[   30.089141] [<c05cdfc0>] (genl_rcv_msg) from [<c05cd0c4>] (netlink_rcv_skb+0x9c/0xe8)
[   30.089206] [<c05cd0c4>] (netlink_rcv_skb) from [<c05cdcd8>] (genl_rcv+0x24/0x34)
[   30.089266] [<c05cdcd8>] (genl_rcv) from [<c05cc890>] (netlink_unicast+0x16c/0x1f0)
[   30.089326] [<c05cc890>] (netlink_unicast) from [<c05ccd38>] (netlink_sendmsg+0x358/0x39c)
[   30.089399] [<c05ccd38>] (netlink_sendmsg) from [<c057dba8>] (sock_sendmsg+0x14/0x24)
[   30.089463] [<c057dba8>] (sock_sendmsg) from [<c057e638>] (___sys_sendmsg+0x204/0x214)
[   30.089527] [<c057e638>] (___sys_sendmsg) from [<c057f3e8>] (__sys_sendmsg+0x40/0x6c)
[   30.089595] [<c057f3e8>] (__sys_sendmsg) from [<c0107ce0>] (ret_fast_syscall+0x0/0x28)
```

**Comment by mpvader** [comment]
previous comment can be ignored: its a known issue and has been there forever.

**Comment by jhofstee** [comment]
https://lkml.org/lkml/2018/8/22/205 suppressed this, but it is harmless

**Comment by vejpasop** [comment]
VE.Bus Standby line tested OK (tested on CCGX and Venus GX).
VE.Bus Panel detect is connected to GND or controlled by the MK3. No Linux kernel dependency here.

**Comment by mpvader** [comment]
GX GSM: Various users are testing the GX GSM including gps. I have heard no more complaints since pushing. v2.20~60

**Comment by mpvader** [comment]
Superseded by #395
