### ISSUE TITLE
wifi not automatically connected if ethernet is connected

### ISSUE THREAD

**Issue by jhofstee** [victronenergy/venus#330]
If the ethernet is used to connect to a product and a wifi dongle used for internet access, the wifi doesn't connect after a reboot, but it must be manually enabled again from the menu.

**Comment by mpvader** [comment]
Its been 50% fixed: first it didn't reconnect to wifi automatically. that is fixed already. 

Remaining issue is that (in such case) the state icon doesn't properly show that wifi is connected.
