### ISSUE TITLE
Add sending gen. running hours as a delta to VRM

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#338]
Probably same for Inverter mode & Grid mode.

to be further defined later.

**Comment by mpvader** [comment]
Possibly (hopefully!) the integral() function in Influx makes it not necessary to add this in Venus

**Comment by mpvader** [comment]
@izak is this done?

**Comment by izak** [comment]
Yes, included in Venus v3.00~15 as attribute `Tga`.
