### ISSUE TITLE
vup: fix unescaped device description

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#351]
- [ ] fix it
- [ ] inform Maurits about what version fixes it; for his monitoring tool

 ```<device nad="0x00" man="273" serial="164066" description="NMEA 2000<->0183 Gateway (NGW-1)" settingsMigration="False">```

the <-> in the description breaks xml parsing/should be escaped to make this valid xml. The worker returned a 1300 less than an hour ago when it encountered this.

Site 25175.

Most probably, this line needs to use the escape function:
https://git.victronenergy.com/can/vup/blob/master/software/xml_output.c#L190

**Comment by jhofstee** [comment]
forgot to mention the issue, for v2.20 it is here https://github.com/victronenergy/meta-victronenergy-private/commit/d26bba897380cb3341ff77ab6fa845d22f484453, included in v2.20~65 (building at the moment)

**Comment by jhofstee** [comment]
also tested now:  | vlink <> | 0x08 | N/A | N/A | Not updatable (1341) -- | -- | -- | -- | -- | --
