### ISSUE TITLE
MPPT state shows ESS when DVCC is enabled?

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#354]
The question mark is there because I haven’t seen it myself yet.

Needs confirmation, and if so, then urgent fix. Rename to `Ext. control` for example. Better wordig welcome

**Comment by Wholistic** [comment]
I can confirm this is the case. It is confusing for customers.

Reported again today in VicCom:
https://community.victronenergy.com/answers/2716/view.html

**Comment by jhofstee** [comment]
The whole menu is confusing afaiac if you don't know what it is about. But anyway, this part is done, https://github.com/victronenergy/gui/commit/a309274ac23c6afcf7a29fffc47e727d2b1ee70c so closing it.
