### ISSUE TITLE
ModbusTCP: better handle non-existing dbus paths and dbus-invalid values

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#362]
**Current situation** when requesting a data from a register that maps to a non-existing path via ModbusTCP; the returned value will be 0. Same will happen when requesting a register that has dbus-invalid: a 0 will be returned.

**Desired situation** Don't use 0 as an invalid value; since that can also be valid. Raising an address error is not acceptable: customers can then no longer request a range of registers in a single query. An alternative is needed. Perhaps return MAX-INT or something similar?

-----

This can be easily reproduced by fetching register 259 from a BMV, and then changing the dbus path in `attributes.csv` to something that doesn't exist.

There is presently no known user-visible bug related to this, but it is incorrect behaviour and masks other bugs. What is more, the user is often unaware of it, because a zero result is often an acceptable result (for example for flags).

**Comment by mpvader** [comment]
Back in the days 🙃; when this project started, care was taken to not create gaps in the mappings.

Do we have services with paths not the sometimes while being there are others?

How does it handle dbus-invalid?

**Comment by izak** [comment]
A gap sometimes exists because something is not supported in a particular configuration. For example, on a BMV there might be a hole at register 260 (/Dc/1/Voltage) if the BMV is configured to use the auxiliary for something other than a starter battery, and similarly 262 (/Dc/0/Temperature) if configured as anything other than a temperature sensor. If you fetch the entire range from 259, as you might, then there is a difference in behaviour:

 * Presently it will return zero for the unsupported registers
 * Under the implementation suggested above, it will return an error.

Dbus-invalid is handled the same way as a non-existent path.

 * Presently it returns 0
 * Under the new implementation it will return an error.

My suggestion is to leave this one out of 2.20, as it is at least not a regression.

**Comment by izak** [comment]
I'm closing this as a won't-fix, because we've had no actual complaints (I found the bug while working on victronenergy/venus#360). We're leaving the existing behaviour so that ranges can be fetched.
