### ISSUE TITLE
canvu: icons don't scale

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#363]
If you can't manage yourself, or need sources or something like that, ask Jesus in #venus-gui.

We used to make icons in png. The solution is to redo them all in svg.

**Comment by mpvader** [comment]
Jesus can you do this in the coming weeks?

**Comment by jepefe** [comment]
Yes, I can.

**Comment by jhofstee** [comment]
@jepefe mind it that Venus expects a viewport in ccgx coordinates!

**Comment by jhofstee** [comment]
done
