### ISSUE TITLE
complete the support of the inverters

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#365]
Both VE.Bus and VE.Direct inverters.

- [x] devicelist in the gui (no need to fix overviews)
- [x] Vrmlogger (already done in 2017)
- [x] modbustcp
- [x] systemcalc (see below)
- [ ] more?

**Comment by mpvader** [comment]
I haven’t seen myself yet that there is an issue with it; Andre mentioned it

**Comment by izak** [comment]
vrmlogger and modbus-tcp support was already present (since 2017), so this item is now complete.
