### ISSUE TITLE
CanBus errors during Venus GX hardwire reboot

### ISSUE THREAD

**Issue by wilcop85** [victronenergy/venus#369]
When the Venus GX is booting from power reset it produces CAN-bus errors and a bus heavy message.
In the attachment there are CAN-bus dumps from different booting procedures.

As you can see in the software reboot there are not problems, but in the hardwire reboot with or without any other communication devices connected there are error's.

Venus GX 
PN: BPP900400100
SN: 1721GUG8E
Firmware version: 2.20 20181016112144

[VenusGXHardwireReBootWithLynxIonBMS.txt](https://github.com/victronenergy/venus/files/2495566/VenusGXHardwireReBootWithLynxIonBMS.txt)
[VenusGXHardwireReBootWithoutDevices.txt](https://github.com/victronenergy/venus/files/2495567/VenusGXHardwireReBootWithoutDevices.txt)
[VenusGXSoftwareReBootWithLynxIonBMS.txt](https://github.com/victronenergy/venus/files/2495568/VenusGXSoftwareReBootWithLynxIonBMS.txt)

**Comment by mpvader** [comment]
You also tested with a ccgx, right? What happened there?

**Comment by mpvader** [comment]
And thanks for the report of course 👍👍

**Comment by wilcop85** [comment]
Yes also tested with the CCGX and there are no problems.

[CCGXHardwareReBootWithoutDevices.txt](https://github.com/victronenergy/venus/files/2495676/CCGXHardwareReBootWithoutDevices.txt)

**Comment by jhofstee** [comment]
closing this, since this can't be fixed software...
