### ISSUE TITLE
Add VE.Bus battery temperature

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#374]
- [x] Add to mk2-dbus: in Venus per v2.30~11
- [x] Add to ModbusTCP
- [x] Add to vrmlogger
- [x] Add to shared temperature sense? How much work is that?
- [x] Decide to add it to gui; or not, because too imprecise; leads to questions.
- [x] Updated modbus spreadsheet on main website

Details:
- is available in VE.Bus firmware since version 412.
- RAM ID 21.
- when no sensor is connected, 0xFF is returned in the high byte
- no difference visible between a remotely received temperature and a self-measured temperature
- temperature reading has been designed (a long time ago) for temperature compensation, which doesn't require accuracy up to the single degree celcius. Which this measurement also is not. How precise it is doesn't matter for our use case.

**Comment by vejpasop** [comment]
Added to mk2-dbus v2.73

**Comment by izak** [comment]
# Shared Temperature Sense

## Present implementation
* Only the Active Battery Service is considered as a source of both voltage or temperature
* If the Active Battery service is a Multi, temperature is assumed to be unavailable
* If temperature is available from the selected battery service, it is copied to the solar chargers and to the Multi

## Modified implementation
* It should be possible to use temperature and voltage from different devices
  * Example: BMV-700 is used as battery service, but temperature comes from vebus
* If the temperature comes from the Multi, don't write it back to the same Multi

**Comment by mpvader** [comment]
@vejpasop you wrote: `is available in VE.Bus firmware since version 512.`.  That should be 412? Or?

And can the issue be closed now? Please discuss with Izak if there are any open last things.

**Comment by vejpasop** [comment]
That should be 412 indeed.
The issue can be closed. (discussed with Izak)

**Comment by mpvader** [comment]
thanks; closed. And I see now I wrote that 512; not you ;-)
