### ISSUE TITLE
Python urllib and/or Requests doesn't respect DNS TTL properly

### ISSUE THREAD

**Issue by wiebeytec** [victronenergy/venus#377]
Recently there were domain issues, and the IP address of ccgxlogging.victronenergy.com briefly changed. Some Venus devices subbornly kept posting vrmlogger data to this IP, even though when 'ping ccgxlogging.victronenergy.com' was run, it showed the correct address.

This has been confirmed in Venus 1.71 and 2.20. Looking at server stats, we saw a drop of about 10% in posts per second, and it took several days to slowly correct (perhaps because people rebooted).

This temporary IP address had a short TTL (300s), so Python urllib should have expired it.

**Comment by mpvader** [comment]
Its not urgent; and will be fixed by itself if we move to newer versions of Python and or Requests; which we do now and then; closing.
