### ISSUE TITLE
BMV-702 / 712: allow giving a custom name for the starter battery

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#387]
Relates to the [Navetta issue](https://github.com/victronenergy/venus-private/issues/77); and is needed by the HTML5 app to show a sensible overview of all available battery voltages.

**Comment by jhofstee** [comment]
well at least we should consider if it isn't a different com.victronergy.battery.*, I guess?

**Comment by mpvader** [comment]
Yes. @heeboA would be happy.

I’m fine with that; could be a bit of a mess in vrm (its device oriented). lets discuss next time we talk.

**Comment by mpvader** [comment]
Superceded by https://github.com/victronenergy/venus/issues/388
