### ISSUE TITLE
mqtt-rpc: add DeviceInstance to vreg-device-list response

### ISSUE THREAD

**Issue by ThiemoVanEngelen** [victronenergy/venus#405]
This would allow a user of vreg-device-list to also connect to the dbus-mqtt topics to get on change updates for the devices in the response.

**Comment by mpvader** [comment]
Izak; pls do this the coming days as part of your ‘clean up the small things’ actions

**Comment by ThiemoVanEngelen** [comment]
This is needed for [async data updates in VictronConnect](https://github.com/victronenergy/victronconnect/issues/26)
