### ISSUE TITLE
dnsmasq shouldn't spam syslog

### ISSUE THREAD

**Issue by jhofstee** [victronenergy/venus#407]
Feb  4 19:22:37 ccgx daemon.info dnsmasq[591]: using nameserver 192.168.4.11#53
Feb  4 19:23:07 ccgx daemon.info dnsmasq[591]: read /etc/hosts - 6 addresses
Feb  4 19:23:07 ccgx daemon.info dnsmasq[591]: using nameserver 192.168.4.11#53
Feb  4 19:23:38 ccgx daemon.info dnsmasq[591]: read /etc/hosts - 6 addresses
Feb  4 19:23:38 ccgx daemon.info dnsmasq[591]: using nameserver 192.168.4.11#53
Feb  4 19:24:08 ccgx daemon.info dnsmasq[591]: read /etc/hosts - 6 addresses
Feb  4 19:24:08 ccgx daemon.info dnsmasq[591]: using nameserver 192.168.4.11#53
Feb  4 19:24:39 ccgx daemon.info dnsmasq[591]: read /etc/hosts - 6 addresses
Feb  4 19:24:39 ccgx daemon.info dnsmasq[591]: using nameserver 192.168.4.11#53
Feb  4 19:25:09 ccgx daemon.info dnsmasq[591]: read /etc/hosts - 6 addresses

**Comment by mansr** [comment]
Fixed in https://github.com/victronenergy/meta-victronenergy/commits/mans/dnsmasq
Now only changes to the nameservers are logged.

**Comment by mpvader** [comment]
added to v2.23. pending for v2.30 as well.
