### ISSUE TITLE
GX GSM: gps doesn't work without simcard?

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#408]
A customer complained about this

**Comment by dewitpj** [comment]
FYI - some SIM802 (if I have that model number right) and the likes uses AGPS for quicker start up - this might be a timing issue since normal GPS takes much longer to then sync ?

**Comment by mpvader** [comment]
Thanks! I think its something else though; we simply never tested this or considered it.

If indeed the modem can do gps while there is no simcard; or other sim/pin issue, then it should be easy to fix.

**Comment by imval** [comment]
I tried and indeed the GPS does not work without the sim card. Even after several hours, no fix established.

**Comment by dewitpj** [comment]
May I ask what AT commands you are sending ?

**Comment by mpvader** [comment]
Its in the dbus-modem repo on our github.

Most likely its really easy to fix. We haven’t looked at it yet because of priorities. (And the simple solution: put in a (working) simcard.

**Comment by dewitpj** [comment]
My suggest (I don’t have the hardware to test etc)

At line 186 (from the current repo) add:

‘AT+CGPSPWR=1’,
‘AT+CGPSRST=1’,

This is taken from memory so it might be wrong - following this the GPS should start (unless your SIMCOM needs something else, but this was from the 8xx or 9xx)

Once locked, the GPS will spit out locations.

HTH !

**Comment by dewitpj** [comment]
If you bored :)

https://cdn-shop.adafruit.com/datasheets/SIM808_GPS_Application_Note_V1.00.pdf

**Comment by mpvader** [comment]
Yes, we’re familiar with those docs.

Thanks for the suggestion! Its a SIM5360E btw.
