### ISSUE TITLE
dbus-canbusbms: detect Freedom Lite battery

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#409]
![714656b7-aa80-45e8-9725-6b5177786cf4](https://user-images.githubusercontent.com/5200296/52323133-2746b500-29dc-11e9-8b86-40d47eef2805.png)

**Comment by mpvader** [comment]
This fixes VRM portal telling the user that its a LG Chem resu. And prepares for showing a Freedom Lite icon/logo on the overview.

**Comment by jhofstee** [comment]
on the site I checked there is no manufacturer info available on the CAN-bus

**Comment by mpvader** [comment]
I’ve asked Freedomwon for information.

**Comment by mpvader** [comment]
@jhofstee, There is a site available now. They’ve done an update in the bms to send out the string.

https://vrm.victronenergy.com/installation/33717/overview

![3707CEDC-71B9-4154-859C-123D90E8F183](https://user-images.githubusercontent.com/5200296/55274905-411abf00-52de-11e9-9d4b-3971a168edca.jpeg)
