### ISSUE TITLE
gui: show Freedom Won logo on battery icon

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#410]
Depends on #409.

**Comment by mpvader** [comment]
[Logo FreedomWon (White).pdf](https://github.com/victronenergy/venus/files/3952474/Logo.FreedomWon.White.pdf)

@jepefe can you make a logo out of that for on the gui overview? If its not the right format, let me know.

**Comment by jepefe** [comment]
> [Logo FreedomWon (White).pdf](https://github.com/victronenergy/venus/files/3952474/Logo.FreedomWon.White.pdf)
> 
> @jepefe can you make a logo out of that for on the gui overview? If its not the right format, let me know.

Yes, the logo in the pdf is a vector image so it is valid.

**Comment by mpvader** [comment]
@jepefe pls arrange this (though only after all urgent Vc things for current release in progress are done). Thank you

**Comment by jepefe** [comment]
@mpvader Do you only need the logo or also want me to place it in the overview?

**Comment by jepefe** [comment]
@mpvader The logo is too long to place it on the battery. I see they use a different logo on their Linked in profile:

**Comment by mpvader** [comment]
yes

**Comment by jepefe** [comment]
Done, added to the v2.60 todo.

The short icon version is used,  the larger one doesn't fit in a way that looks good and is readable on a CCGX screen.

![overview_freedomwon_logo](https://user-images.githubusercontent.com/6424631/88032648-8c458a80-cb3e-11ea-94f7-322f2656b2b6.png)
