### ISSUE TITLE
watchdog: verify new kernel watchdog option

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#418]
Newer kernels have a new watchdog feature, telling the kernel what to do when the watchdog is already running when the kernel loads.

The default of that setting is not good for us: it keeps the watchdog happy until the userland watchdog daemon takes over. Which leaves the system with a vulnerable time in case something goes wrong in userland.

Docs: https://github.com/victronenergy/venus/wiki/watchdog

- [x] beaglebone
- [x] canvu500
- [x] ccgx
- [x] sunxi

**Comment by mansr** [comment]
canvu500 fixed in v4.14.71-canvu500-5, pending release.

**Comment by mpvader** [comment]
For the beaglebone, kernel needs to be upgraded for this issue. Which will be done once there is a good moment (not now; v2.30 needs releasing)

**Comment by mansr** [comment]
All machines run a new kernel with correct configuration since v2.70~8.
