### ISSUE TITLE
Systemcalc: make sure /dc system power logic is in place - needed for html5 app

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#424]
#12 in the html5 slack.

Systemcalc needs to look at the has dc system setting; and based on that either publish data on that path or not. Html5 app will within a few days contain logic to show/hide its DC Loads box; depending on that path.

So it (the html5-app) will no longer itself look at the related setting.

**Comment by mpvader** [comment]
https://victrondevelopment.slack.com/archives/CDBK9A71S/p1554363919011400?thread_ts=1549978966.021800&channel=CDBK9A71S&message_ts=1554363919.011400

**Comment by izak** [comment]
This was fixed by restarting systemcalc in the simulations. systemcalc always comes up after localsettings in a real setting, so the same was done in simulations.
