### ISSUE TITLE
mqtt-rpc: add support for xupc

### ISSUE THREAD

**Issue by WrdVictron** [victronenergy/venus#427]
xupc is the same as vup: a commandline tool to update firmware; but then for devices, connected to VE.Can, that have a xup bootloader.

- [x] Add xupc commandline tool to Venus - done in v2.30~27 
- [x] (@elnino-ict ) Add xupc to [mqtt-rpc](https://github.com/victronenergy/mqtt-rpc)
  - not for scanning; only for updating. Scanning doesn't need any changes; `vup` will also find xup-devices. For updating, mqtt-rpc needs to select between xupd and dup commandline tools by filename extension (`.xup` vs `.vup`).
  - once done; ask Izak to review and release to Venus.
- [x] Add support for .xup files to the firmware library: [issue](https://github.com/victronenergy/venus-private/issues/84)
- [x] (Wiebren) Add .xup files to Dropbox
- [x] (Wiebren) Add error codes to [internal mqtt-rpc documentation](https://github.com/victronenergy/venus-private/wiki/mqtt-rpc-and-vrm)
- [x] (Wiebren) Check & amend [customer documentation](https://www.victronenergy.com/live/vrm_portal:remote-firmware-update) where necessary
- [x] (@mauritsvdvijgh) vrm-mqtt-rpc: add support for xupc: https://github.com/victronenergy/vrm-mqtt-rpc/blob/master/vrm_mqtt_rpc/client.py#L430
- [x] (@AlexImb) VRM: modify popup text: change `.vup` to `.vup or .xup`; see image below (dup example)
- [x] (Wiebren) Test end-to-end functionality with update using a file from the library
- [x] (Wiebren) Test end-to-end functionality with manually selecting a file

Background info:
- Similar issue for adding xupd support (VE.Direct xup updater): #389
- For more details see: #389 

![image](https://user-images.githubusercontent.com/35060325/49932895-8e5b5800-feca-11e8-8da2-9b630f33715e.png)

**Comment by mauritsvdvijgh** [comment]
I need access to a venus device running v2.30~27 or higher with a device attached to it that has a xupc bootloader to test mqtt-rpc.py changes.

Somehow the Venus GX we have updated to v2.23 instead of v2.30~xx though "update to" is set to "Latest Release candidate". Even if I had the latest release candidate I still do not have a device with a xupc bootloader attached to it for testing however.

**Comment by WrdVictron** [comment]
The firmware for the xupc product is not yet available. It is expected March 15th. 
Once released, I will make it available on Dropbox.
Then I will also give you access to a venus running v2.30~27 or higher, with the corresponding xupc product connected.

**Comment by WrdVictron** [comment]
@mauritsvdvijgh: Release files are available on Dropbox (SmartSolar MPPT VE.Can)

**Comment by thlassche** [comment]
I deployed `vrm-mqtt-rpc` and `vrm` with .xup support. Thiago tested it using a MPPT: It worked. So all that's left is the end-to-end tests and the .xup files in the Dropbox I think

**Comment by jhofstee** [comment]
@WrdVictron can you update or close this one..
