### ISSUE TITLE
16  out mkx_rst not working on victronenergy,easysolar

### ISSUE THREAD

**Issue by jhofstee** [victronenergy/venus#431]
The mkx_rst pin doesn't work on the easysolar. One issue seems that it is not muxed properly. Trying to force that:

```
+&pio {
+    mk2reset: mk2reset {
+        pins = "PA16";
+        function = "gpio_out";
+    };
+};
+
 &reg_usb2_vbus {
     gpio = <&r_pio 0 11 GPIO_ACTIVE_HIGH>; // GPIOL11 / VUSB_ENABLE
     status = "okay";
@@ -76,7 +83,7 @@
 
 &uart1 {
     pinctrl-names = "default";
-    pinctrl-0 = <&uart1_pins>;
+    pinctrl-0 = <&uart1_pins &mk2reset>;
     status = "okay";
 };
 
```

doesn't seem to help either.

**Comment by mansr** [comment]
There is an error on the PCB. Resistors R325 and R328 have been swapped.

**Comment by mansr** [comment]
Compare schematic and PCB layout:
![image](https://user-images.githubusercontent.com/322231/54119903-66f32900-43ee-11e9-873b-c4782734e61c.png)
![image](https://user-images.githubusercontent.com/322231/54120015-9ace4e80-43ee-11e9-973a-c98d47b36056.png)

**Comment by mkrenzke** [comment]
@mansr Yes, you seem to be right. Felix will take care on Wednesday.

**Comment by jhofstee** [comment]
thanks, fixed
