### ISSUE TITLE
Show VE.Direct inverter state on Tile Overview

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#433]
Support for VE.Direct inverters [already completed][1] in systemcalc. This mostly works correctly, except that the State is indicated as "Off". This should ideally show "Inverting".

For the other values there is not much that can be done. We have no DC current measurement, so neither that or the derived power can be shown. There is also no SOC value.

![Selection_148](https://user-images.githubusercontent.com/851549/54196529-5912d600-44ca-11e9-9c97-4fbbecf87336.png)

![Selection_149](https://user-images.githubusercontent.com/851549/54196538-5f08b700-44ca-11e9-9cb2-49aef592c684.png)

[1]: https://github.com/victronenergy/venus/issues/365

**Comment by Wholistic** [comment]
VicCom is asking about this issue:
https://community.victronenergy.com/comments/14778/view.html
