### ISSUE TITLE
Warn when DVCC is enabled and there is more than one battery

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#439]
- [x] implement it
- [ ] add a number to the warning
- [ ] document it in the user manual (and use the number there)

If you have two batteries; each with an mppt; both mppts to the gx device. One BMV (or intelligent battery witb canbus bms) and then you enable dvcc.

* Both SVS and STS is enabled by default.
* The lowest-instance battery is auto-selected as battery monitor
* Both MPPTs immediately follow battery 1.

That might be a problem that should be warned against.

**Comment by mpvader** [comment]
ok, put it in systemcalc (& gui & vrmlogger) just like that other warning you're making.

**Comment by jhofstee** [comment]
I changed the milestone, almost all alarms have no number and I think there is some effort going on to at least make charger errors unique, so we like want to know what they are doing before adding more random numbers...

**Comment by mpvader** [comment]
There are also systems that are designed to have multiple batteries:

![image](https://user-images.githubusercontent.com/5200296/69790435-c682a600-11c2-11ea-8048-d458ded18b8c.png)

So lets back this out.

**Comment by mpvader** [comment]
After removing it from the gui back in 2019, it was left enabled on VRM (as part of the automatic alarms monitor)

Which is shouldn't be: the final purpose of this parameter was decided to be diagnostics just for ourselves, to help troubleshooting a site that behaving strange.

So I removed the alarm flags on this attribute just now in the vrm database; and expect that any sites with that alarm raised will automatically have it closed as soon as a new data-transmission comes in.
