### ISSUE TITLE
Add setting to disable low-pass filter for tank level sensors

### ISSUE THREAD

**Issue by aeneby** [victronenergy/venus#440]
Although this "anti-slosh" feature may be helpful on a boat, for installations where the tank is stationary it is unnecessary, and in some cases problematic. The ability to disable this feature would be useful in such cases.

**Comment by webmasterkai** [comment]
The filter is too extreme and is so slow to react that it prevents over filling the tank.

**Comment by aeneby** [comment]
In case it's of any interest, I recompiled the ADC binary to disable the low-pass filter and see if behaviour improved. It is an improvement, in that the sensor reads 100% roughly when it should, and avoids overflowing the tank. However the movements are still quite coarse, i.e. there are big jumps between readings.

I'm still not sure why, I haven't had the time to investigate. It could be an issue with the ADC code, or it could be a hardware limitation. It could also be something weird happening in my tank, for example the incoming water creating waves while filling or something. But using a multimeter and actuating the sensor manually, the changes in resistance are quite smooth.

**Comment by mpvader** [comment]
Hi @aeneby we did a major rewrite of dbus-adc recently; and fixed a bug that made it veeerryy slow in intialising at start-up in some conditions.

It will be part of Venus OS (test) versions only a few weeks from now, after first officially releasing v2.40 without it. But would be great if you could give it a good test.

We didn't change the intention of the filter mechanism; so probably its still slow in reacting; definitively if you want to use it to prevent over filling a tank; indeed.

**Comment by aeneby** [comment]
Hi @mpvader thanks for the update. My intention was to be a bit more helpful than I have been but life keeps getting in the way :) I will keep an eye out for the test release.

Since it is a major rewrite, is the dbus-adc binary still ABI compatible with older versions of Venus? Or would I need to reinstall the whole OS?

Have you had much feedback on how well the filter works in practice (including boats)?

**Comment by mpvader** [comment]
Hi A, only feedback I ever heard was the feedback in this issue.

Yes still ABI compatible. You should be able to compile and run it.

But waiting a bit works too :-).

Thanks for the quick reply!

**Comment by mpvader** [comment]
Hey @aeneby , took quite a while, but this is close to being solved and part of https://github.com/victronenergy/venus/issues/699.

**Comment by aeneby** [comment]
@mpvader great work! Can't wait to try it out.
