### ISSUE TITLE
systemcalc: When the ESS MinSOC is set to 0%, discharge might stop prematurely in some cases

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#441]
When the SOC of a battery is out of sync, and the user wants to discharge it all the way to zero, it is possible to reach a reported 0% SOC before the battery is really empty. In the ESS algorithm we stop when the SOC is **equal** or lower than the configured minimum. This makes the logic simpler in many places, but a special case needs to be added for 0%, so that the battery is never considered to be discharged unless the multi is in sustain (which indicates the voltage dipped too low).

**Comment by mpvader** [comment]
Setting the MinSOC to 0% should disable the check.
