### ISSUE TITLE
dvcc: fixup warning text

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#453]
1. some people think that it only requires or allows enabling if you have a solar charger.
2. text is wrong, now that we have the new VE.Can MPPTs coming into stock soon.

![image](https://user-images.githubusercontent.com/5200296/57249154-7b495000-7044-11e9-909e-e378c920879f.png)

**Comment by izak** [comment]
This text also shows up on its own (without the DVCC switch below it) when the access is set to "User", which is confusing to users. The text should follow the same `show` logic as the switch below it.

**Comment by izak** [comment]
Suggested by Matthijs, and I agree, implement checking for old firmware in systemcalc. The GUI then only need to look in one place.
