### ISSUE TITLE
PV inverters disappear from VRM when set to Multiphase.

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#458]
The problem appears to be that overall power is not logged to VRM, only the per-phase values. When a single-phase PV-inverter is set as Multi-phase, it does not report per-phase values, only an overall power value. This means nothing is logged to VRM unless the state or the power level changes, which means for long periods nothing is logged for a PV-inverter, causing VRM to think it's been removed.

The issue is Multi-layered.

# Why would you use a single-phase inverter in a Multi-phase system?

This is done (mostly?) in North America. The supply could be two phases pi radians apart, with 240V across them, or two-out-of-three phases with 208V across them. A single phase 208/240V PV-inverter can then be connected across the phases, just like the stove or the dryer might be connected in such homes.

# Systemcalc & vrmlogger/vrm

Systemcalc and vrmlogger wants per-phase values. The overall power is not logged.

# Sunspec, and our implementation thereof

For a Multiphase inverter sunspec model 102/103 (intsf) or 112/113 (float) is published. This contains:
* Overall power value (across all phases)
* Overall energy made (across all phases)
* Per-phase voltage and current measurements

To translate the overall power- and energy values to per-phase values, we use the voltage and current of each phase (and a calculated VA and overall power factor) to determine the split. This allows us to calculate fairly accurate per-phase power and energy values.

# Proposed solution

## What we have- and don't have to work with:
* Overall power
* Overall energy
* Current
* Overall voltage
* We don't know the voltage per actual phase, only across the phases.
* We don't have the current per phase (but it is reasonable to assume it will be equal, since there is no Neutral center connection).
* We don't know (not without referencing the Multi) how many phases there **really** are, we see only one on the PV-inverter.
* Hence the existing way of splitting will not work

## Solution
* Split the overall power and energy in two
* Report only per-phase power and energy, not voltage and current.
* This should be sufficient for systemcalc and vrmlogger to do their thing.

## Remaining obstacle
How do we detect this situation? Is it sufficient to *assume* that a single-phase inverter (as detected from the phase count, derived from sunspec) that is configured as Multiphase (in localsettings) must necessarily be such a cross-phase installation?

**Comment by izak** [comment]
A simple implementation that makes a single-phase inverter pretend to be split-phase if configured as Multiphase.

https://github.com/victronenergy/dbus-fronius/tree/american-cross-phase-connection

@mpvader I would appreciate your thoughts. It's a fairly simple change, it simply makes the assumption that when a single-phase inverter is configured as Multi-phase, then it implies that it sits across L1 and L2.

We can complete the functionality by removing the lock-out in the GUI.

**Comment by izak** [comment]
A change in the gui is still required, reopening.

**Comment by izak** [comment]
Selecting MultiPhase is now an option for single-phase inverters.

![Selection_343](https://user-images.githubusercontent.com/851549/64695102-a41e9d80-d49b-11e9-92ae-cfb490c3fe34.png)

**Comment by mpvader** [comment]
Allowing three phase sounds weird?

**Comment by skumancer** [comment]
Hey guys, I'm having an issue where if I chose Split-phase (L1+L2), I'm losing the Fronius PV Inverter from the VRM display. Any clues?
