### ISSUE TITLE
CCGX IO: Vebus firmware updater broken due to inverted io lines

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#459]
On CCGX devices, with MK2 or MK3,  the following IO line levels are inverted compared to other Venus devices.

1. /dev/gpio/mkx_rst/value
2. /dev/gpio/vebus_standby/value 

Currently (since ???) vbdup is build without "TARGET=ccgx".  The inverted IO line levels cause vbdup to fail due to lost VE.Bus power during updates.

mk2-dbus is unaffected since for the CCGX it is still build with "TARGET=ccgx", thus using the old `/sys/class/gpio/....` path to toggle the vebus standby and mkx reset lines.

**Comment by mpvader** [comment]
Fixed as part of v2.40~41; closing.
