### ISSUE TITLE
mqtt-rpc: add VE.Bus firmware versions to device-list

### ISSUE THREAD

**Issue by thlassche** [victronenergy/venus#472]
- [x] Add VE.Bus devices to the device-list call with their firmware version and with a flag indicating that they can't be updated remotely.
- [x] Check that VRM shows them as not updatable with their firmware version in the device list
- [ ] Add capability flag to vrmlogger; so that VRM knows it can use the device-list function; rather than the two dup & vup functions that its still using now.
- [x] Fix VE.Bus firmware version notation (v4.59 is wrong, should be 459); fixed by calling GetText, and then doing no further conversions.
- [x] Fix productid; 9746 is  wrong; should be 2612: the hexadecimal equivalent.

The reason to do this, is that people don't understand that not every class of devices is updatable through mqtt-rpc (https://github.com/victronenergy/vrm-portal/issues/119)

*Note:* It was also discussed that it is an option to show the Venus device itself in this list. It was decided that that was not necessary for now, but might become relevant again in the future (e.g. for updating the Venus device itself through mqtt-rpc)

**Comment by mpvader** [comment]
@thlassche is this one we can finish up and close next wednesday and thursday? would be nice.

**Comment by thlassche** [comment]
@mpvader Sure! I'll dive into it before wednesday so I'm prepared

**Comment by mpvader** [comment]
Whats this waiting for, @thlassche ?

**Comment by thlassche** [comment]
@mpvader Testing (which I just did on Hub-1) and a capability check, , already going quite well:

<img width="1015" alt="Screenshot 2019-11-28 at 16 30 30" src="https://user-images.githubusercontent.com/2959888/69818316-c901f180-11fc-11ea-9739-54beceda3816.png">

Let's quickly go through the remaining steps together tomorrow than I can wrap it up

**Comment by mpvader** [comment]
As discussed just now: wrt planning this is not for v2.40; but hopefully we can include it in v2.50. Few small more changes are necessary; see above updated todo.

**Comment by jhofstee** [comment]
Closing this, since it included quite some time ago.
