### ISSUE TITLE
systemcalc: store the relay state

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#476]
Right now a reboots resets them to off.

Even if only switched off for a little while (because the SoC resets its gpio maybe/probably - I did not check), its better than now: reboot resets them to off.

When changed this way; perhaps the gui should control them via local settings rather than through systemcalc? Maybe, maybe not, but do make sure to reconsider the architecture when starting on this one.

**Comment by izak** [comment]
There are 4 ways in which the relay can be used:

* Alarm relay, controlled by the GUI
* Generator start/stop, controlled by dbus-generator
* Tank pump, controlled by dbus-pump
* Manual

Upon a reboot, the first three will set the relay state correctly according to present circumstances, so this only affects the last manual case.

**Comment by izak** [comment]
Released in v2.40~19.
