### ISSUE TITLE
Remote VEConfigure: Add grid info readout support

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#479]
Upcoming Multi firmware will contain grid code information to be used by VEConfigure.
This data block provides information about the supported Grid code settings,

Todo: 
- [x] mk2vsc: Add grid code information readout support
- [x] VRM Remote VEConfigure:  Add new mk2vsc status and error code
      - ```#define MK2VSC_ST_READ_GRID_INFO 24```
      - ```#define MK2VSC_ERR_GRID_INFO_READ 72```
- [x] Release VEConfigure tooling supporting grid info

**What happens when using older versions of Venus with Multi firmware supporting grid info?**
 VEConfigure can not be used with these Multi firmware versions and will show the following error message:

![afbeelding](https://user-images.githubusercontent.com/10847324/60513600-f8f1ab00-9cd7-11e9-8da0-b7c4ce96cb38.png)

_Note: CCGX should be replaced by Venus OS_

**Comment by thlassche** [comment]
Related `mqtt-rpc` pull request, which adds support for the new states to VRM:

https://github.com/victronenergy/mqtt-rpc/pull/10

**Comment by mpvader** [comment]
Added in v2.40~something, and will be backported to v2.33
