### ISSUE TITLE
Remote Console for LAN doesn't work on Firefox?

### ISSUE THREAD

**Issue by Basazababo** [victronenergy/venus#48]
We are trying to use Beaglebone Controller, we connected it to our LAN, we get its IP but we are facing this issue.
![ccgx remote control](https://cloud.githubusercontent.com/assets/15770523/17730435/fa894860-6468-11e6-8242-95290030c052.jpg)

Can you  enable remote console for LAN automatically?

**Comment by mpvader** [comment]
which version of the bbb image are you using? Remote Console on LAN is already enabled by default on the BBB.

Details of required networking is in [this section](https://www.victronenergy.com/live/ccgx:ccgx_faq?&#what_type_of_networking_is_used_by_the_color_control_gx_tcp_and_udp_ports) of the VRM FAQ. Look for Remote Console on LAN.

**Comment by Basazababo** [comment]
The Latest image 1.70
I check VRM FAQ but it does not help.

Any idea why this is disabled?

**Comment by Basazababo** [comment]
Thanks Mpvader for your help;
I use google chrome and it works.
Seems it fails to connect on Mozilla Firefox browser.

**Comment by mpvader** [comment]
which OS are you using, and which version of Firefox?

**Comment by mpvader** [comment]
ps, please send an email with the details to support@victron.zendesk.com. Since this is at first really a support question. Not an issue for the developers. I'll see your email coming in that support box. Thanks. Matthijs
