### ISSUE TITLE
ESS: No ESS Assistant found. 

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#482]
Venus V2.40~8

After Multi firmware update to 2608459 and installation of ESS assistant (137) 

GUI shows:
![afbeelding](https://user-images.githubusercontent.com/10847324/60586110-a674c500-9d91-11e9-887d-45f58f2500b5.png)

While an ESS assistant is installed

mk2-dbus info.
![afbeelding](https://user-images.githubusercontent.com/10847324/60586236-f5225f00-9d91-11e9-9c76-4d0246f80f6b.png)

**Comment by jhofstee** [comment]
@mpvader Systemcalc is crashing on this line https://github.com/victronenergy/dbus-systemcalc-py/blob/master/dbus_systemcalc.py#L490. 

```
@400000005d1c937614ba8a9c Traceback (most recent call last):
@400000005d1c937614c3f0dc   File "/opt/victronenergy/dbus-systemcalc-py/dbus_systemcalc.py", line 921, in <module>
@400000005d1c937614e02784     systemcalc = DbusSystemCalc()
@400000005d1c937614e63264   File "/opt/victronenergy/dbus-systemcalc-py/dbus_systemcalc.py", line 275, in __init__
@400000005d1c937614f063c4     self._updatevalues()
@400000005d1c937614f549ac   File "/opt/victronenergy/dbus-systemcalc-py/dbus_systemcalc.py", line 490, in _updatevalues
@400000005d1c93761502b344     newvalues['/Dc/Pv/Power'] = v * (i + l)
@400000005d1c937615093354 TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'
```

**Comment by mpvader** [comment]
Closing this one; #483 is the real bug.
