### ISSUE TITLE
update dup to v1.0.18

### ISSUE THREAD

**Issue by rvanzundert** [victronenergy/venus#493]
The boost version of dup (v1.0.18) contains a fix that re-transmits the frame if it got back a frame error response (same behavior as the checksum error response).
The issue was discovered when using dup extensively while running CI tests on ve.direct products.

**Comment by jhofstee** [comment]
Hello @rvanzundert,

Can you comment what the impact of this is? From the comment above I guess an update failed, while there was no reason to??

**Comment by jhofstee** [comment]
and please add fixed issues here https://github.com/victronenergy/venus-private/wiki/todo, instead of creating issues. The reason it is included it that I put it there on you behave.
