### ISSUE TITLE
VE.Bus: Add readout of network quality counters

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#494]
VE.Bus network quality counters can be readout since Multi firmware version 460. 

These counters can be useful for debugging VE.Bus communication problems

The network quality counters register the number of VE.Bus frame retransmissions that took place after one or more connected "VE.Bus" devices failed to receive a valid frame. The counter is read from the Multi. After a system reset the counters will be cleared.

Note. The counters are implemented on protocol level, not on application level. When in a parallel  system  the VE.Bus cable  connection between two units is removed, the counters in both units will not increment.  In this case on protocol level frames are being send correctly to all connected devices. There are no checksum errors and therefore also not retransmissions required. 
On application level however, when a Multi in a parallel system is missing  the system will automatically be switched off and a corresponding VE.Bus error will be published. It is imported to keep in mind that these occurrences will not necessarily be represented in the network quality counters.

The network quality counters can be viewed in the VE.Bus diagnostics menu  (Multi->Advanced->"VE.Bus diagnostics")

![afbeelding](https://user-images.githubusercontent.com/10847324/66382089-d6e48480-e9ba-11e9-8a47-36dc36d3b2a5.png)

The counters are updated upon initialization of mk2-dbus, after a VE.Bus error and approximately every 5 minutes.

Dbus path:
```Devices/#/ExtendStatus/VeBusNetworkQualityCounter```

Todo:

- [x] Add to VRM logger
- [x] Add to GUI

**Comment by mpvader** [comment]
Hi Jos,

screenshot please. And when do they reset to 0? And these are the counters in the devices themselves, right? Ie not the counters from the MK3 in the GX Device?

And in what event(s) does the counter increment?

**Comment by vejpasop** [comment]
Hi @matthijs,

I added the screenshot and story to the description above. 
Indeed these are the counters in the devices themselves, and not in the MK3.

We did not implement these counters in the MK3 firmware (yet)
