### ISSUE TITLE
2.33 CCGX firmware bug - static DNS validation does not allow last number to be greater than 5 in final field.

### ISSUE THREAD

**Issue by Wholistic** [victronenergy/venus#497]
A new CCGX installation on firmware 2.33 and are trying to manually configure the ethernet DNS settings to x.x.x.206 in remote console.

There's a bug which prevents setting the third digit of the final octet to 6, 7, 8 or 9 if the first digit of the final octet is 2. This prevents the final octet from being set to any of the following numbers: 206, 207, 208, 209, 216, 217, 218, 219, 226, 227, 228, 229, 236, 237, 238, 239, 246, 247, 248, 249.

When attempting to set the last digit to 6, 7, 8 or 9 I get the message "Only numbers up to 5 are valid on this location"

As reported on community by scottb - https://community.victronenergy.com/questions/25437/233-ccgx-firmware-bug-static-dns-validation-wrong.html?childToView=25485#answer-25485

**Comment by izak** [comment]
This affects all IP addresses, not just DNS. For example, it also affects the manual IP assignment for PV inverters.
