### ISSUE TITLE
DVCC+ESS: User limit for battery discharge current

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#498]
Way back with Venus 2.06, there was a brief experiment with including the PV power into the ESS maximum discharge power so that the result would be the maximum power taken from the battery. This had some undesirable side-effects, so the previous behaviour was restored and the setting was renamed to "Maximum inverter power".

Occasionally we still get requests for a way to limit the discharge from the battery. This is normally from people with smaller battery banks who still want to use the full available PV power for loads.

We already have a maximum charge current setting under Settings -> System Setup. This is DVCC specific, but *not* ESS specific. It is also used in non-ESS systems to limit the charge current. A maximum discharge current setting will however by definition be ESS specific.

A maximum discharge current setting will hook into the same mechanism now used for intelligent batteries and allow the user to set a maximum discharge current. As with BMS limits, it will be approximate.

**Comment by mpvader** [comment]
Closing; double with #356
