### ISSUE TITLE
VE.Bus: Error 11 split-up

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#505]
In upcoming VE.Bus firmware (version 464??) VE.Bus error 11 will split-up in to two different error codes.

- Error 8 = GNDRelayTestError
- Error 11 = BFRelayTestError

The error reason from both errors can still be read from the ```Devices/#/ExtendStatus/GridRelayReport/...``` items.

Note:  The current Venus release only updates the ```GridRelayReport``` only upon initialization and after an error 11.  From Venus OS 2. 40~17 (mk2-dbus v2.94) onward the ```GridRelayReport``` always gets updated after any vebus error and every 5 minutes.

Todo:
- [x] mk2-dbus add Error 8 definition and description
- [x] GUI Add error 8 description and update "VE.Bus Error 11 report" text 
- [x] update https://www.victronenergy.com/live/ve.bus:ve.bus_error_codes
- [x] Add error 8 to VRM (maybe consider showing undefined VE.Bus error codes in the alarm logs also)

See here for final wording:
https://www.victronenergy.com/live/ve.bus:ve.bus_error_codes#error_8_-_ground_relay_test_failed

**Comment by mpvader** [comment]
https://www.victronenergy.com/live/ve.bus:ve.bus_error_codes#error_8_-_ground_relay_test_failed

**Comment by mpvader** [comment]
I (a) defined error 8 in the database and (b) added lots of others too; so they do show up in logs even if not named yet.

![image](https://user-images.githubusercontent.com/5200296/68129330-a6d8c480-ff19-11e9-80ed-b418b4850011.png)
