### ISSUE TITLE
VE.Bus: Show "ESS Relay test pending (and therefore no feedback)" information

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#513]
Todo:

- [x] mk2-dbus: Add "waiting for relay test" status to dbus
- [x] GUI: Visualize "No-feedback mode"
- [x] VRM: Add status

**Info from MVa:**
Procedure when the AC relays can’t be tested at powerup
Every time the relays have been opened, they must be tested before they can be closed again. The tests can only be done if there is both DC voltage and AC Mains available.

A unit will do the test whenever it is cold started (power off -> power on, using the rocker switch), or after a mains failure (connected -> switches to inverter mode -> mains restores -> test is performed -> switches back to mains).

But. When the DC voltage is too low to invert, or when there is another reason why the unit can’t start inverting, for example its been set to Charge Only, it will, after a delay of 1 to 2 minutes, close its backfeed relays, connect to mains, and then start. It then powers the AC loads in passthru, and (when permitted) will charge the battery. Because the relay test wasn’t performed, its in a special ‘No-feedback’ mode. In that mode, it will first charge for 15 minutes. Then it will continuously check the battery voltage: when above 14V it will switch to inverter mode, do the relay test, and switch back to mains. The reason for the 15 minutes is to make sure the battery has actually been charged a while, to have enough power to operate in inverter mode during the tests.

**Details:**
**required versions**
- mk2-dbus v2.96
- Multi firmware >= 454

**dbus-path (mk2-dbus):**
`Devices/#/ExtendStatus/WaitingForRelayTest`

**Comment by mpvader** [comment]
Izak, in the gui, put it the advanced page (see below).

The item needs to be shown only when its an ESS system.

Name and values: `ESS Relay test            Pending|Completed`

![image](https://user-images.githubusercontent.com/5200296/69791142-30e81600-11c4-11ea-9d89-ccd96c2451b2.png)

And then we'll have to document it somewhere too.
