### ISSUE TITLE
Improve GX GSM Manual

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#517]
While helping someone with a GX GSM problem, I improved the manual. The most important chapter is chapter 5, Troubleshooting. Pls review how it is now. If there is any other intel available for customers, we should add it; it will be appreciated.

@mansr / @jepefe pls review; & make changes if you see any, or let me know; then I'll change it.

https://www.victronenergy.com/live/venus-os:gx-gsm

btw, the badly rendered table with the icons (its clipped at the right), is being fixed.

**Comment by mkrenzke** [comment]
After fix of numbering "Trouble shooting" is point 6 now.

Also I've added a list of SIM card states to the "Status" chapter and did some improvements in formatting.

**Comment by mpvader** [comment]
Thanks!

**Comment by mpvader** [comment]
good enough
