### ISSUE TITLE
Cleaning up the Settings -> System setup menu

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#520]
Its has grown a bit out of control, see below.

- [ ] Grid loss alarm -> Rename to Monitor for [grid failure|shore disconnect]; and hide when there is no AC input configured as grid or shore.
- [ ] Move all four status items (Synchronize VE.Bus SOC with battery, Use solar charger current to improve VE.Bus SOC, Solar charger voltage control, Solar charger current control) into a sub menu, called "Status" at the bottom, and visible only when access level is Super user. Why? Since by now we know the code works well and this is all about very old firmware versions etc.
- [ ] Move all DVCC Items in its own menu: Settings -> DVCC. 
- [ ] Shorten the explanatory text to "Read the manual before enabling this feature". (And we'll be making #519 also in v2.40)
- [ ] Only show the `Temperature Sensor`, and `Used temperature sensor` in case `Shared Temperature Sense` is enabled.
- [ ] Delete the BMS Control item, its no longer necessary.
- [ ] Rename `Battery measurements` to `Marine MFD App configuration`, or `Marine MFD App config` to be shorter.
- [ ] Move limit charge current to top of dvcc page, right under the dvcc enable/disable item.

![image](https://user-images.githubusercontent.com/5200296/66340385-58013480-e945-11e9-90e0-d36c952a7b95.png)

**Comment by mpvader** [comment]
## Preview of the new System setup menu:

![image](https://user-images.githubusercontent.com/5200296/66342465-c7792300-e949-11e9-81e2-4a3811d3d443.png)

## Preview of the new DVCC menu:

![image](https://user-images.githubusercontent.com/5200296/66342677-4a9a7900-e94a-11e9-9db1-9cc35c43b096.png)

**Comment by jhofstee** [comment]
gui v4.2.1 includes this
