### ISSUE TITLE
mqtt-rpc: is it reallly necessary to have error codes 998 and 999?

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#530]
Since the rest is in 700 to 799 range.

https://github.com/victronenergy/venus-private/wiki/mqtt-rpc-and-vrm

**Comment by thlassche** [comment]
@mpvader Not necessary. Created a pull request here: https://github.com/victronenergy/mqtt-rpc/pull/12

**Comment by thlassche** [comment]
It's merged and on the todo: https://github.com/victronenergy/venus-private/wiki/todo#v250---done---waiting-for-recipe--venus-maintainer-add-new-ones-at-the-top-of-this-list

**Comment by jhofstee** [comment]
seems a reference to the issue to be closed is missing
