### ISSUE TITLE
Send custom names to VRM

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#539]
Now that we no longer send all config dataAttributes when one of them changes (see recent vrmlogger improvement), we can start sending the custom name to VRM.

As the /CustomName path only contains data when a user has set it up; also vrmlogger will only send it when a user has entered a custom name. Which is fine: the VRM Portal will automatically use the data when configured; and will show the product name matching the productid if there is no custom name set up.

More details in /CustomName here: https://github.com/victronenergy/venus/wiki/dbus-api#object-paths

There is one possible issue: when a user would clear the custom name, then on the GX device the name shown will immediately revert to the product name. But since vrmlogger is not transmitting any invalid paths; also not once; the custom name will remain on VRM. Until the GX device is rebooted that is; since a reboot will make VRM flush out all old data. Which fine; we're not now going to put in any extra code to fix this.

**Comment by izak** [comment]
Attributes added to VrmLogger v2.157.
