### ISSUE TITLE
Fix possible MPPT load output issue related to DVCC shared current sense

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#540]
Thiago is working on this.

**Comment by mpvader** [comment]
Issues were found. And are being fixed:

- a new MPPT v1.47 candidate release (still pending).
- updated vedirect-interface (already included v2.40~43; already built; but not yet in candidate.

**Comment by tabreu** [comment]
Release candidate vF1.47 for ve.direct MPPTs has been sent to testers.

**Comment by mpvader** [comment]
Hi @tabreu do you consider this issue as closed? Then we can close it.

**Comment by tabreu** [comment]
Yes, we can close it
