### ISSUE TITLE
make dbus-mqtt connect to different mqtt server based on the VRM portal id

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#543]
For load balancing, we’ll host multiple mqtt servers.

There is a defined algorithm on how to know which one to connect to. That algorithm takes the vrm portal id as an input.

The affected mqtt link is dbus-mqtt. Not mqtt-rpc.

### Required before official release of v2.40:

- [x] prepare the dns records (which for now point all to the same old broker: nothing really changes yet)
- [x] implement in dbus-mqtt
- [x] implement in mqtt-rpc
- [x] inform customers that are using mqtt (such as Alliander) about this breaking change
- [x] update public mqtt documentation (dbus-mqtt readme)
- [x] update networking question in ccgx faq

### Required before releasing VictronConnect or VRM changes that will lead to many people enabling MQTT on VRM:

- [x] Make VictronConnect use the load-balanced servers
- [x] deploy new mqtt servers - planned for mid December

### Related:

- [x] adapt venus-docker-grafana to use new server scheme
- [x] adapt VRM realtime functions to use the new broker: https://github.com/victronenergy/vrm-portal/issues/168

**Comment by mpvader** [comment]
Either Teun or Wiebe can make the (I suppose small) change in the python code. Who of you two makes it doesnt matter to me :-)

**Comment by thlassche** [comment]
First proposal of an implementation over here: https://github.com/victronenergy/velib_python/pull/20/files
@wiebeytec @mpvader

**Comment by wiebeytec** [comment]
> The affected mqtt link is dbus-mqtt. Not mqtt-rpc.

Just for completeness here: the submodule velib_python _does_ need to be updated in mqtt-rpc, because otherwise they will overwrite each-other's result.

**Comment by thlassche** [comment]
Merged and tagged it in mqtt-rpc and dbus-mqtt.

Added it to the v2.40 todo: https://github.com/victronenergy/venus-private/wiki/todo-v2.40#v240---done---waiting-for-recipe--venus-maintainer-add-new-ones-at-the-top-of-this-list

Happy to know if I did something wrong in the tagging and listing it on the todo

**Comment by mpvader** [comment]
I’ve informed community: https://community.victronenergy.com/questions/35016/edit.html

**Comment by mpvader** [comment]
Added to Venus in v2.40~44

**Comment by wiebeytec** [comment]
It's in the works to make VictronConnect use the new servers (I added it to the checklist). I already tested it using `/etc/hosts` (together with a test site), and it works (as do VRM live updates).

What's the status of the Venus Docker Grafana? Once VictronConnect is done, that would be the only block, as far as I can tell.

**Comment by mpvader** [comment]
Venus docker grafana is already dine and released. I ticked the box

**Comment by mpvader** [comment]
All done - closing this.

Welcome to reopen @wiebeytec or @thlassche if necessary.
