### ISSUE TITLE
dummy issue to hold pictures

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#55]
in case you want to add a picture to the wiki, just paste it here and grab the url.

**Comment by mpvader** [comment]
![image](https://cloud.githubusercontent.com/assets/5200296/18631933/122fa330-7e75-11e6-8c8a-9e9f56680b77.png)

**Comment by mpvader** [comment]
![image](https://cloud.githubusercontent.com/assets/5200296/18631955/3a7beeac-7e75-11e6-9a7e-6f26289780ab.png)

**Comment by jepefe** [comment]
![screen shot 2016-09-28 at 10 14 07](https://cloud.githubusercontent.com/assets/6424631/19261188/bf5e8d48-8f8f-11e6-9190-8800de8a83fa.png)
![screen shot 2016-09-28 at 10 00 22](https://cloud.githubusercontent.com/assets/6424631/19261189/c0ff9d36-8f8f-11e6-9b95-a96d3a72251f.png)

**Comment by jepefe** [comment]
![screen shot 2016-10-11 at 08 52 42](https://cloud.githubusercontent.com/assets/6424631/19261252/21e61e90-8f90-11e6-8bfa-284960639d2c.png)

**Comment by mpvader** [comment]
![image](https://cloud.githubusercontent.com/assets/5200296/23941379/e3985b6e-0968-11e7-96d5-31c446dedc04.png)

**Comment by mpvader** [comment]
![image](https://user-images.githubusercontent.com/5200296/34422232-857a9102-ec14-11e7-9517-65986e46ad04.png)

**Comment by 3dGrabber** [comment]
![image](https://user-images.githubusercontent.com/3806963/35797316-9de8f670-0a5f-11e8-838f-56a12a0b3280.png)

**Comment by 3dGrabber** [comment]
![image](https://user-images.githubusercontent.com/3806963/35797721-dbb4e134-0a60-11e8-9093-887f292b5222.png)

**Comment by 3dGrabber** [comment]
![image](https://user-images.githubusercontent.com/3806963/35797836-473532ce-0a61-11e8-891b-9222a9a7b873.png)

**Comment by 3dGrabber** [comment]
![image](https://user-images.githubusercontent.com/3806963/35798637-b05aeba2-0a63-11e8-8b46-734aa3444c1f.png)

**Comment by 3dGrabber** [comment]
![adjust kit for velib](https://user-images.githubusercontent.com/3806963/35802057-e063438e-0a6e-11e8-86f3-7dfcfa025e77.png)

**Comment by mpvader** [comment]
![image](https://user-images.githubusercontent.com/5200296/36118033-fa83a614-103b-11e8-84f4-1d500c27118d.png)

**Comment by AlexImb** [comment]
![image](https://user-images.githubusercontent.com/4534299/47568515-99195800-d931-11e8-8a8f-ee821b955b95.png)
