### ISSUE TITLE
gui: bug in vrmlogger 12h and 24h interval settings 

### ISSUE THREAD

**Issue by thlassche** [victronenergy/venus#550]
See: https://community.victronenergy.com/questions/34901/vrm-log-interval-12h-and-24h.html

> when I select the 12-hour registration interval the interval is 2 hours and when I select 1 day the interval is 4 hours. I could check the graphs and the system summary.

Checked it on VRM:

<img width="1837" alt="Screenshot 2019-11-30 at 09 07 57" src="https://user-images.githubusercontent.com/2959888/69897789-11cabf00-1351-11ea-894f-900a3bfe4f33.png">

**Comment by thlassche** [comment]
It's a bug in the GUI, only for 12 hours and 1 day, see: https://github.com/victronenergy/gui/blob/37d3cd6044fc8be5920c4afd8d6cffe63798d7fd/qml/PageSettingsLogger.qml#L39

- 12 hour is set at 7200s which should have been 43200s
- 1 day is set at 14400s which should have been 86400s

FYI @wiebeytec

**Comment by mpvader** [comment]
Teun wrote:

> Only affects the 12h and 24h setting.

I checked 1 minute and 15 minute interval on v2.40; and they work fine. 1 minute = 60 seconds, and 15 minute = 900 seconds (duh)

**Comment by jhofstee** [comment]
reopen since this can go in v2.41 as well

**Comment by mpvader** [comment]
In v2.41, closing
