### ISSUE TITLE
WiFi reconnect issues

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#553]
(simple cut & paste from the todo)

  * What the user sees is Failed (in the GUI), and it will not ever retry again.
  * Reproduceble by making the associating always fail (in the kernel)
  * Its not a regression; what might be different is that its more likely to happen on the newer builds, when comparing the v2.17.
  * David Alsina reported this, or a similar, problem when running 4.14. And after downgrading to V2.17 he had the same problem.
    * https://vrm.victronenergy.com/installation/4133/dashboard
    * 2018-sept-14: installed v2.17
  * Report on Venus-dev mailing list
    * https://groups.google.com/d/msg/victron-dev-venus/VIVWxGuOyT8/xSu9g1eFEQAJ
  * related or not issue on community by blokl https://community.victronenergy.com/questions/19181/venus-gx-dont-reconnect.html
  * Matthijs saw it as well, 20190603. Logging into the GUI (on another medium..) and it showed failed. And then simply connecting the Connect item there made it go again. Cron job or something similar?
  * Related, or not, issue: https://github.com/victronenergy/venus/issues/467

**Comment by jhofstee** [comment]
included in v2.60~4
