### ISSUE TITLE
ESS: Ignore the grid meter if "Grid Meter installed" is turned off

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#554]
The current situation is that hub4control (the heart of ESS) will always use a grid meter if it can find one, even if the "Grid meter installed" switch is off.

The switch was formerly called "Ignore missing meter". Power values from the Multi's input is used when a meter is not found.

We will change this by making the existing setting `Grid meter installed` work as people expect it to work: disabling that setting should make the system operate without grid meter; even if a grid meter is installed.

![Selection_423](https://user-images.githubusercontent.com/851549/72263814-4a350c80-3622-11ea-8ec1-804f1f075655.png)

**Comment by mpvader** [comment]
As discussed, this will be implemented by making the existing setting `Grid meter installed` work as people expect it to work: disabling that setting should make the system operate without grid meter; even if a grid meter is installed.
