### ISSUE TITLE
v2.40: red led blinking on Venus GX?

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#556]
> I saw the red LED blinking all the time, but no notifications in Venus OS. I've done hard reboot but the LED is always blinking red.

https://community.victronenergy.com/questions/32924/venus-os-v24037-available-for-testing.html?childToView=32940#comment-32940

(this issue is just as a reminder for me to look into what this is about; if anyone knows, welcome to explain & close the issue)

**Comment by jhofstee** [comment]
The red led is visible when the host access point is not available. It is also blinking when the host access point is disabled on purpose.
