### ISSUE TITLE
make dbus-valence filter on canbus type (11 vs 29 bit)

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#56]
Example of the code that needs to be added into the main taskUpdate() function:

```
    while (veCanRead(&msg))
    {
        VeStream canIn;

        /* ignore all 29 bit / extended messages */
        if (msg.flags & VE_CAN_EXT)
            continue;
```

**Comment by mpvader** [comment]
and maybe the motordrive service as well. But that one works for two brands (piktronic & sevcon). And one of those works on 29bit and the other on 11bit

**Comment by jhofstee** [comment]
perhaps we should limit the Oceanvolt profile to valence and motordrive so we can finally close this issue?

**Comment by jhofstee** [comment]
closing this, if issue are reported we just disallow combination with 29 bit busses
