### ISSUE TITLE
dbus-vecan: add /Status path for tank senders

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#563]
### What needs to be done?

Add a /Status path, hardcoded to OK (0) to vecan-dbus for tank senders.

### Why?

The VRM Portal needs one dataAttribute to be sent always. It uses it to show the age of last receiving data from the device to the user. And uses it for the list on the Device List page.

For tank senders, it currently uses the tank level field. But for Venus GX and Cerbo GX, that field is invalid in case dbus-adc suspects a wiring issue; causing the tank sender to disappear from / not show up on the device list on VRM. Which makes sense.

For most other device types it uses a status field, one thats always there (see below list) but for the tank levels it currently can't do that, since there is no status field on D-Bus for the canbus tank senders.

This is the status path that dbus-adc has:

```
'0', 'OK', '0', NULL
'1', 'Disconnected', '0', NULL
'2', 'Short circuited', '0', NULL
'3', 'Reverse Polarity', '0', NULL
'4', 'Unknown', '0', NULL
```

Adding /Status, hardcoded to OK to vecan-dbus, and then in the vrm database changing the keyIdDataAttribute for tank senders from level to status fixes the Venus GX / Cerbo GX built-in tank senders not showing on the device list on VRM in case they're having issues.

Temperature is handled the same: keyIdDataAttribute is the status, not the actual temperature.

For info, the key-dataAttributes for the other devices are:

![image](https://user-images.githubusercontent.com/5200296/70847687-639e3980-1e67-11ea-8630-a9e02ca39cbb.png)

**Comment by mpvader** [comment]
(slightly updated above text)

**Comment by jhofstee** [comment]
The can bus change is in v2.60~9. Keep in mind that the VRM should look at level OR status for backwards compatibility.

**Comment by mpvader** [comment]
note that above is changed a bit: when the tank level comes from the canbus (N2K), dbus-vecan will look at the level and set /Status to 5 (= Error) in case the level as received is invalid. In N2K, invalid is sent as MAX-INT minus one, or something like that.

**Comment by jhofstee** [comment]
The error state is included in v2.60~29, VRM seems to cope with that as well.

**Comment by jhofstee** [comment]
reopening this, since VRM doesn't seem to display it in the Device List when in an error state.

**Comment by thlassche** [comment]
@jhofstee Fixed
