### ISSUE TITLE
Fix CI issues and add Cerbo to CI

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#564]
- [x] Make venus-tests/.gitlab-ci.yml such that it doesnt start running CI upon a commit. Fixes pipelines like this: https://git.victronenergy.com/venus-ci/venus-tests/pipelines/8827. There is likely to be some easy flag that can be added in to the yml file for that.
- [x] Update the test-venusgx-relays-and-digital-and-analog-inputs.py script, because the new dbus-adc thats in v2.50 no longer postfixes the dbus name with `_di0 / _di1 / etc`. Or, even better make the script such that it doesn't depend on that last bit. But if that has disadvantages, just remove them, like I did here: https://git.victronenergy.com/venus-ci/venus-tests/tree/matthijs/fix-venus-gx-not-passing-the-relay-and-io-test. Fixes v2.50 not passing the tests.
- [x] ~Add the Cerbo GX relays, digital inputs & analog inputs to CI~ See #575

**Comment by evandromr** [comment]
- all jobs on venus-tests will only trigger if the BRANCH variable is set. It can be done manually via the GitLab gui, or as an option to git push with `git push -o ci.variable="BRANCH=master"` (see [documentation here ](https://docs.gitlab.com/ee/user/project/push_options.html)about git push options) 
- Fixed `test-venusgx-relays-and-digital-and-analog-inputs.py` : Use the new dbus-adc paths by default, and on failure, tries the old-style address to maintain backwards compatibility.
