### ISSUE TITLE
Add Maretron tank sender to CI

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#570]
Margriet will order one, delivery Groningen for Evandro

**Comment by mpvader** [comment]
@evandromr is this done? yes right?

**Comment by evandromr** [comment]
No (or at least not by my doing), I never got a Maretron delivered and eventually forgot about it. CI has one Navico (#558) and one Victron (#571) tank sender, connected to the CerboGX.

**Comment by mpvader** [comment]
Margriet will order a new one as discussed by mail today & yerterday. The end result should be that we have one in R&D and one in CI.

**Comment by mpvader** [comment]
I tried quite hard, but its impossible to buy that tank sender & Maretron is not responding to emails. I'm closing this.
