### ISSUE TITLE
Decommission Pubnub

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#584]
We were / are still paying for Pubnub; though its no longer functional:

It was only used for remote firmware updates & remote veconfigure; from back in the days that we did that with VE Power Setup. And the currently available VE Power Setup version no longer offers those functions. Trying to use the old features shows this notice:

![image](https://user-images.githubusercontent.com/5200296/72224697-88c4bb80-357d-11ea-912a-7ad3be425a2a.png)

Edit: also note that older VE Power Setups also don't work, because Juice has been taken down (https://github.com/victronenergy/vrm-portal/issues/5).

Before stopping Pubnub entirely; we need to make sure that the old Venus devices out there won't go all 'crazy' (ie 100% cpu load or some similar thing) if we do so.

Wiebe, do you have time to look into that the coming days?

**Comment by wiebeytec** [comment]
I tested with a Venus 1.74. With invalid keys, it fails with:

`ERROR:__main__:Error sending to pubnub :HTTPSConnectionPool(host='pubsub.pubnub.com', port=443): Read timed out.`

Interestingly, when I block port 443 and start vrmpubnub, it doesn't retry after removing the block. The process seems to stop doing anything. 

So:

- No CPU use
- Static RAM use
- No constant error message to the log

I'll keep an eye on it some more today.

**Comment by wiebeytec** [comment]
I also monitored traffic to Pubnub, and there is no increase, from repeated retries, for instance. In fact, there is no traffic at all anymore.

I suggest we disable the keys.

**Comment by mpvader** [comment]
Ok go for it

**Comment by wiebeytec** [comment]
Keys removed and subscription stopped.
