### ISSUE TITLE
dbus-cgwacs: report phase sequence if supported

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#586]
- [x] implement and release this in the driver (dbus-cgwacs)
- [x] add it to the gui
- [x] Add it to vrmlogger

The EM24 and ET340 meters have registers that indicate when your Phase Rotation is incorrect. Exposing them on dbus and showing them on the GUI will be useful to installers and should help cut down on support.

**Comment by mpvader** [comment]
@izak pls add some wording on the todo explaining what goes wrong when its installed in the wrong sequence.
