### ISSUE TITLE
Fronius: improve serial number & firmware version visualisation

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#589]
Details have been sent to us by Fronius, details here:

https://secure.helpscout.net/conversation/1054669255/3158?folderId=1462833

Not for now though.

**Comment by izak** [comment]
Device screen now shows correct firmware version. Settings still stored using the SolarAPI `uniqueId`.

Before:

![Selection_702](https://user-images.githubusercontent.com/851549/96593166-7ab08200-12e9-11eb-9a4d-369b338260d6.png)

After:

![Selection_703](https://user-images.githubusercontent.com/851549/96593188-7edc9f80-12e9-11eb-85e1-335286f49f63.png)
