### ISSUE TITLE
Tank setting capacity not saved

### ISSUE THREAD

**Issue by RobDuthie** [victronenergy/venus#593]
Version 2.40-46 testing tank capacity not saved.
All other settings for tanks saved OK

**Comment by mpvader** [comment]
Hi Rob, thanks. Though this bug was fixed on v2.41, released within days of releasing v2.40?

**Comment by RobDuthie** [comment]
Note:
Just tested again with the added extra relay file, and it has stopped again, i will reload the software from scratch again and reload the files in order to see why it effects the tank capacity saving?
