### ISSUE TITLE
Question regarding MIPS and openwrt

### ISSUE THREAD

**Issue by Viss** [victronenergy/venus#596]
So there's a company called gl.inet and they make a bunch of really amazing, really powerful little wifi routers. They run openwrt out of the box, and have a usb port with gadget mode enabled. I've connected an ftdi rs232 serial adapter and watched it come to life. 

What I'd like to attempt is to extract the relevant libraries and scripts from venus in an attempt to save having to run another device off the battery setup. I've seen the videos and screenshots showing how capable and powerful venus is - and it's something I intend to invest the appropriate time and effort in once I get all my troubleshooting out of the way. For now, I just want to see if it's possible to use an openwrt device to get some simple text output from a victron device in an effort to measure battery voltage, and current coming off of a single solar panel.

**Comment by jhofstee** [comment]
I think you are better of posting your question here, https://community.victronenergy.com/spaces/31/index.html. Venus is arm only and hence copying binaries won't work.
