### ISSUE TITLE
Add a driver & gui qml page for the car charging station

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#599]
CCS = Car Charging Station

Required functionality:

- auto detect it (on the Ethernet or Wifi network)
- read values (ModbusTCP) and publish on D-Bus
- have an entry in the Device list menu in the gui; showing the values
- controls:
  - Change the mode (5009) between 0-manual and 1-auto
  - Change the charging current (5016) between 6 and 32 Amps
- firmware update it (requires adding it into mqtt-rpc.py, Lucian and Nikolay have already tested proper working of updating the device, doing a http call using curl on a GX Device, see Slack)

For later:
- add it to the overview page as part of the system.

Tech implementation:

- D-Bus service name: com.victronenergy.carchargingstation (anyone with a better idea can comment :-) ).
- For the list of modbus parameters, see below. Can easily be changed, see people in the Slack Channel.
- Product id has already been reserved: `0xC024`
- Discovery: Nikolay has implemented upnp to make the device discoverable by Venus OS

![image](https://user-images.githubusercontent.com/5200296/73753702-603a7680-4763-11ea-81b3-5b2a4a2680be.png)

**Comment by mpvader** [comment]
Included in v2.62~2

**Comment by c4software** [comment]
Hi,

Sorry to resurect this old issue, but, I have a silly question… If I implement this modbus register with my own charging station (ESP32 and VE-Tronic), my device should be available on my venus installation ?

PS: I know it's not the best place to ask. But I don't know where to ask this kind of specific question (related to specific register).

Best regards,
