### ISSUE TITLE
dbus-vecan: add reading gps data from the N2K network

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#610]
Note that we’re not going to transmit gps data out on N2K. People that need gps in their N2K network should buy a proper n2k gps. Not a usb thingie on a gx device.

**Comment by aaronsb** [comment]
This is cool. Accepting NMEA over UDP (gpsd style) without shell configuration would also be helpful.

**Comment by jhofstee** [comment]
@aaronsb that is indeed a seperate process, see https://github.com/victronenergy/dbus_gps/commits/master.

**Comment by mpvader** [comment]
This issue was waiting for a real nmea2000 gps; which was ordered and received in the mean time.

**Comment by jhofstee** [comment]
gps support is added in v2.60~17. The gui part in v2.60~19.
