### ISSUE TITLE
CANVU does not support USB GPSes

### ISSUE THREAD

**Issue by SturmUDrang** [victronenergy/venus#615]
Tested with a number of devices that work flawlessly on CCGX build of Venus, on CANVU 2.51 they are listed as USB devices but don't get a tty. 

A few examples:

P:  Vendor=1546 ProdID=01a7 Rev=01.00
S:  Manufacturer=u-blox AG - www.u-blox.com
S:  Product=u-blox 7 - GPS/GNSS Receiver

P:  Vendor=1546 ProdID=01a8 Rev=03.01
S:  Manufacturer=u-blox AG - www.u-blox.com
S:  Product=u-blox GNSS receiver

**Comment by mpvader** [comment]
thank you for the concise report @SturmUDrang , we'll look into it.

**Comment by mpvader** [comment]
Closed in v2.60~somewhere

**Comment by mpvader** [comment]
Hey @SturmUDrang , please try with the Venus OS candidate that we’ll release later tonight. That will have fixed it. Thanks again for reporting
