### ISSUE TITLE
CAN / NMEA2000 UI improvements

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#617]
- [x] Rename `Send data to VE.Can` to `NMEA2000-out`
- [x] Rename `Unique device number for VE.Can` to `Unique identity number selector`
- [x] Add a text below it: `Above selector sets which block of unique identity numbers to use for the NAME Unique Identity Numbers in the PGN 60928 NAME field. Change only when using multiple GX Devices in one VE.Can network`.
- [x] Rename `Check unique numbers` to `Check Unique id numbers`
- [x] Reword the CAN unique number test result: add `OK` in front. Or something else, the goal is to make it clear that the result means that everything is OK.
- [ ] Make it impossible to change the CAN-bus Device Instance of the GX Device (by setting a writeable flag to 0). Reason: a customer changing that can only break things (ESS for example).
- [x] ~Add the Unique number to the list in Settings -> CAN-bus -> Devices (see screenshot below).~ cancelled - too much
- [x] On that same list, prefix the numbers, with UN & DI, for example.
- [x] Add the Unique identity number to the page after that as well.
- [x] Add a warning for Solar chargers & Chargers to the detailed page that allows changing a Device instance: `Careful, for ESS systems, as well as systems with a managed battery, the CAN-bus device instance must remain configured to 0. See GX manual for more information.`

Screenshots of current functionality:

**Settings -> CAN-bus:**
![image](https://user-images.githubusercontent.com/5200296/77918586-600ab300-729c-11ea-912d-0e1cca15a92d.png)

**Settings -> CAN-bus -> Devices:**
![image](https://user-images.githubusercontent.com/5200296/79466690-345a2d80-7ffd-11ea-8c4b-1ea8786be59d.png)

**Details of one device in that list:**

![image](https://user-images.githubusercontent.com/5200296/79466810-5e135480-7ffd-11ea-8be9-60f900a791f9.png)

**Comment by mpvader** [comment]
@jhofstee I added some more rewording above.

I took `Unique ID Number` from the NMEA2000 document chapter 8.3 Device Information; see screenshot which I took from internet somewhere below.

![image](https://user-images.githubusercontent.com/5200296/78302434-14c20000-753b-11ea-9a70-1aadc2381e6e.png)

**Comment by vanbergeijk** [comment]
Please be aware that only the entire NAME is required to be unique. The Unique Identity Number has a dependency on the Manufacturer Code. If other NAME fields are different, e.g. the Function value is different, then it is possible that the same combination of a Manufacturer Code and Unique Identity Number is used by multiple devices. The dependency graph is:

![image](https://user-images.githubusercontent.com/14980900/78321166-dc1d2900-7530-11ea-9adf-639412b36f4d.png)

**Comment by mpvader** [comment]
Hi @vanbergeijk , yes absolutely we're aware. Thanks. Changing that setting is only necessary when a users installs multiple GX Devices on one VE.Can network. The issue its solving is quite simply that back when we started producing the GX Devices, we did not program them with a unique number - yet.

**Comment by jhofstee** [comment]
@vanbergeijk despite being a nice image, it is unfortunately incorrect for NMEA2000. See 8.3.1.4 of this number across multiple products **of the same function** ... Since this is public information I am tempted to remove above posts to prevent spreading incorrect information. It is correct for J1939 afaik though.

**Comment by vanbergeijk** [comment]
@jhofstee, I think we're saying the same: if the function of 2 devices is the same then yes, the manufacturer has to ensure that the identity numbers of those devices are unique. The opposite case of this logic is: when you have 2 devices with different functions, then the same identity number could reoccur in those devices. That's why just an identity number is not enough, the rest of the NAME is required to get to a unique identity.

**Comment by mpvader** [comment]
Hi @vanbergeijk and any future readers, FYI all details of how it works with NAME and such in Venus OS are now documented here: https://www.victronenergy.com/live/ccgx:start#nmea2000-out_technical_details
