### ISSUE TITLE
Fix custom names for BlueSolarchargers and Smart Solarchargers

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#619]
**Current situation:**

Implementation per Solar charger type:
- Our Bluesolar chargers (Roys code stack) doesn't support custom names at all (and never will; code size limitations)
- Our Smartsolar chargers with Roy his code stack that don't have VE.Can support the custom name in a limited manner: the custom name is stored in the BLE chip, and  therefor not available to Venus OS/VRM as well as the Remote feature in VictronConnect. (and never will; code size limitations)
- All Solar chargers with Thiago his code stack, both with only a VE.Direct port as well as the models with VE.Direct *and* VE.Can fully support custom names. Both on their VE.Direct interface as well as on their VE.Can interface. Note that we ship SmartSolar Chargers with Thiago his code stack, but also BlueSolar models.

In  Venus OS, there is a fallback (only for VE.Direct devices) where the vedirect-interface driver will automatically store custom names in localsettings (= Flash on the GX Device) in case the VE.Direct product doesn't support the custom name VREG.

And note that for Smartsolar chargers with Roy his code stack, you can now have two different custom names: one on BLE, and one on Venus OS/VRM.

**fix:**

Update vedirect-interface to support the custom names (stored in local settings) in the VregLink D-Bus interface. Currently vedirect-interface only supports this fallback in the normal D-Bus interface (ie. the paths interface). This is a small change, can be done by Thiemo, and fixes most confusion when working with VictronConnect remotely.

**Comment by tabreu** [comment]
About: properly fixing custom names in Roy his MPPT code stack is impossible, due to limited code size

**Comment by mkuiken** [comment]
The dongle will prioritize the custom name of the attached SmartSolar (if it has one) over any locally stored custom name. If the name is changed via BLE then the dongle will make a copy and use that copy when the attached SmartSolar indicates that it does not support VE_REG_DESCRIPTION1.

If the name is changed via any other interface on the SmartSolar then there will be a difference with the name stored in the dongle. But as long as the SmartSolar announces its new name to the dongle, then the dongle will prioritize this new name over its locally stored name.

The only situation in which the name stored in the dongle is "lost", is when the SmartSolar was _not_ supporting custom name and then _starts_ supporting it. But as far as I understand from Thiago is this not the case as the VE.Can has been supporting it from the beginning.

**Comment by tabreu** [comment]
Good to remember that the SmartSolar VE.Direct also do not support custom names. Only the VE.Can and the new VE.Direct only models will.

**Comment by jepefe** [comment]
I noticed that when changing the custom name for example of a VE.Can MPPT from VictronConnect via MQTT, `/CustomName` on DBus doesn't change and Venus has to be restarted to get the new name in the gui. Changing the name via BLE works fine and the name in the Venus GUI is updated immediately.

**Comment by tabreu** [comment]
I afraid that is because the PGN 1F016 Configuration Information needs to be sent, when the custom name is changed on mppt, and it is not on the latest FW release. That is a known issue that will be fixed on the next release.

**Comment by ThiemoVanEngelen** [comment]
In this case, the MPPT was connected via VE.Direct. What happens is that the messages triggered via mqtt do not follow the normal handling so the answer is only sent back to mqtt not handled internally. This will also be fixed by me.
