### ISSUE TITLE
Add Solarchargers to NMEA2000-out

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#622]
here are the PGNs transmitted by our canbus Solarchargers

![image](https://user-images.githubusercontent.com/5200296/79231338-32119b00-7e66-11ea-99d4-0335b191cb29.png)

from: https://www.victronenergy.com/upload/documents/Whitepaper-Data-communication-with-Victron-Energy-products_EN.pdf

**Comment by jhofstee** [comment]
included in v2.60~26
