### ISSUE TITLE
GPS afterwork

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#631]
Since we now support reading gps data from NMEA2000, there can be multiple GPS-es on the dbus. Because of that, our serial gps driver, dbus-gps (or gps-dbus) used to publish on com.victronenergy.gps, is now updated to now have a fourth segment in its dbus service name. And it publishes a /DeviceInstance path. That /DeviceInstance path is a VrmInstance: a number reserved through local settings starting at 0.

VRM, for its location & geofence services, needs to know one set of GPS data, which it expects at instance 0.

The gui also needs to know one set of GPS data.

The new plan:

- [x] (ibu) Update systemcalc to publish the service name of the selected GPS: out of the list of available GPS-es with a fix, take the one with the lowest /DeviceInstance.
- [x] (ibu) Update vrmlogger to take care of that indirection and take the data from that selected gps service and push it to VRM on instance 0.
- [ ] Restore the GUI status bar functionality related to gps (mobile overview & status bar); see [this commit](https://github.com/victronenergy/gui/commit/93c1b7099f1b7a21fcba0de1db1ebb25c8221d1f).

**Comment by mpvader** [comment]
I updated above to the new plan

**Comment by jhofstee** [comment]
include in v2.60~19, https://github.com/victronenergy/gui/commit/129df42a96cebae9e220b58dd5319302c34e4732
