### ISSUE TITLE
improve overviews

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#64]
The different things that can be improved are:
## General:
- during grid failures it would be great to gray out the active-in field and corresponding lines. And, for grid-parallel, also gray out the unprotected AC-load box.
- the multi has 8 leds, not 6. (MultiCompact only has 3)
- make the multi leds blink? led status is already available on the d-bus.
- for three phase systems, vertically align the L1/L2/L3 in all the boxes
## No PV:

![screen shot 2016-10-11 at 08 52 42](https://cloud.githubusercontent.com/assets/6424631/19261252/21e61e90-8f90-11e6-8bfa-284960639d2c.png)
## Hub-1
- is not showing ac-coupled PV
  ![screen shot 2016-09-28 at 10 14 07](https://cloud.githubusercontent.com/assets/6424631/19261188/bf5e8d48-8f8f-11e6-9190-8800de8a83fa.png)
## Hub-2
- is not showing dc-coupled PV:
  ![screen shot 2016-09-28 at 10 00 22](https://cloud.githubusercontent.com/assets/6424631/19261189/c0ff9d36-8f8f-11e6-9b95-a96d3a72251f.png)
## Hub-4
- only shows PV on ac input: DC coupled PV and PV on AC output are missing. also systems with only dc-coupled pv are using the hub-4 assistant now.
- is no indication of loads on the output: some people will have those, others don't.
- there will also be hub-4 like systems without pv at all
  ![image](https://cloud.githubusercontent.com/assets/5200296/19261141/5e1b97a6-8f8f-11e6-9298-cc0690b1f345.png)

**Comment by mpvader** [comment]
The gui has several diagrams, and on the diagram certain blocks are shown/hidden based on the a config:
- dc system is shown/hidden based on the user setting
- pv blocks are shown/hidden based on their presence

The diagram selected based on com.victronenergy.system/Hub, determination is done in [delegates.py](https://github.com/victronenergy/dbus-systemcalc-py/blob/master/delegates.py#L84):
```
		hub = None
		vebus_path = newvalues.get('/VebusService')
		if self._dbusmonitor.get_value(vebus_path, '/Hub4/AcPowerSetpoint') != None:
			hub = 4
		elif self._dbusmonitor.get_value(vebus_path, '/Hub1/ChargeVoltage') != None or \
			newvalues.get('/Dc/Pv/Power') != None:
			hub = 1
		elif newvalues.get('/Ac/PvOnOutput/Total/Power') != None:
			hub = 2
		elif newvalues.get('/Ac/PvOnGrid/Total/Power') != None or \
			newvalues.get('/Ac/PvOnGenset/Total/Power') != None:
			hub = 3
		newvalues['/Hub'] = hub
```

Note that that also has a hub = 3, which might need to be removed. Depends on how many different diagrams we'll be using in the new implementation

**Comment by mpvader** [comment]
@jepefe: on v2.00~2, there seems to be something wrong with the LED aligment:

![image](https://cloud.githubusercontent.com/assets/5200296/20113700/c9418c5c-a5f1-11e6-8e80-dab9e8296838.png)

Matthijs Thuis / 1495.

(really cool by the way, a pleasant surprise after updating my bbb!)

**Comment by mpvader** [comment]
And this is really cool too:

![image](https://cloud.githubusercontent.com/assets/5200296/20113729/ef3aac68-a5f1-11e6-9e64-61b103bfc986.png)

**Comment by mpvader** [comment]
@jepefe: also I see this error in the gui log (gui v3.02)

```
2016-11-08 19:48:31.308150500 
2016-11-08 19:48:31.308153500 QVNCServer No password configured, accepting connection
2016-11-08 19:48:34.200090500 file:///opt/color-control/gui/qml/OverviewSolarCharger.qml:47:2: QML Image: Failed to get image from provider: image://theme/overview-victron-logo-small
2016-11-08 19:48:42.243668500 QVNCServer disconnected from "127.0.0.1" 
```

**Comment by jepefe** [comment]
@mpvader Theme on this build is outdated so the new "live" leds are drawn over the old icon.
Just added the themes repository to the todo so @jhofstee can include it on the next build.
