### ISSUE TITLE
some dbus data are only published one time in mqtt

### ISSUE THREAD

**Issue by dm3ts** [victronenergy/venus#644]
The dbus-Provider: com.victronenergy.vebus.ttyO5 -> "Ac/Out/L*/S" and "Ac/Out/S" are changing recently, but the mqtt transfer are only published one time.

If I restart the "dbus-mqtt/dbus_mqtt.py", the value is pubished one time with the right values.

**Comment by vejpasop** [comment]
This is a feature. Signals to the /S paths where disabled in mk2-dbus v2.42 (12-2016) in order to reduce D-Bus load.

**Comment by mpvader** [comment]
Hi, I added above information in [the documentation](https://github.com/victronenergy/venus/wiki/dbus), thank you for noticing this @dm3ts , closing this issue.
