### ISSUE TITLE
v2.60 - ModbusTCP issue on digital inputs?

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#646]
https://community.victronenergy.com/questions/51615/venus-os-v26025-available-to-be-tested.html?childToView=51677#answer-51677

**Comment by izak** [comment]
Cannot reproduce. Tested modbus-tcp with android app, works fine, except that you only see the integer part of the number (which is expected). No obvious bug.

I contacted the customer to investigate further.

**Comment by izak** [comment]
Tested at customer site using an Android app and port-forwarding: Works correctly.
