### ISSUE TITLE
invalid services

### ISSUE THREAD

**Issue by jhofstee** [victronenergy/venus#65]
hub1 has these invalid service (getty is enabled on ttyO0, which likely causes this)

/service/dbus-cgwacs.ttyO0: unable to chdir: file does not exist
/service/gps-dbus.ttyO0: unable to chdir: file does not exist
/service/vedirect-interface.ttyO0: unable to chdir: file does not exist

**Comment by mpvader** [comment]
Perhaps related to point 1 of the [startapp.sh issue](https://git.victronenergy.com/mirrors/venus/issues/8) ?

**Comment by jhofstee** [comment]
serial-starter removes them now at startup
