### ISSUE TITLE
grid alarm is raised when multi is switched off

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#658]
Looks to be a regression in v2.60, probably since we moved this function from systemcalc to mk2dbus

https://community.victronenergy.com/questions/53096/venus-os-v26028-available-for-testing.html?childToView=53487#answer-53487  ( the comment by Mark)

**Comment by vejpasop** [comment]
Issue description:

The grid lost alarm did not work in combination with the safety switch assistant.

Grid lost alarms where canceled when the Multi switch mode was off. The safety switch assistant does not change the switch position state to "off" when triggered (instead it shows charger only mode). However by checking the VeBusMain state we can see that the Multi is switched "off"  by the assistant, and cancel the alarm.

Note: The assistant does not turn off the power of the device.  Only the AC output is switched off.
It does this by switching to charger only mode and enabling ignore AC input
