### ISSUE TITLE
swupdate: log switching to the backup rootfs

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#66]

**Comment by mpvader** [comment]
@mansr: hi, this is probably something super small to arrange? Please take care of it. thanks.

**Comment by mansr** [comment]
Pushed to branch swupdate in meta-victronenergy.

**Comment by mpvader** [comment]
https://github.com/victronenergy/meta-victronenergy/commit/2217e65e1384b1f3a3fd4fc9583bf6eac975b0ed
