### ISSUE TITLE
Port python projects to python3

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#667]
Python projects that need porting to python3

- [x] velib-python
- [x] systemcalc
- [x] dbus-characterdisplay
- [x] dbus-digitalinputs
- [x] dbus-modbus-client
- [x] dbus-mqtt
- [x] dbus-recorder (handle unicode on dbus correctly)
- [x] dbus-tools
- [x] vrmlogger
- [x] localsettings
- [x] mqtt-rpc
- [x] dbus-generator
- [x] dbus-modem
- [x] [dbus-imt-si-rs485tc](https://github.com/victronenergy/dbus-imt-si-rs485tc)   (  <--- modbus, so perhaps best integrated into dbus-modbus-client instead)
- [x] venus-button-handler
- [x] dbus-paygo
- [x] dbus_vebus_to_pvinverter
- [x] dbus-fzsonick-48tl
- [x] dbus_pump
- [x] vesmart-server
- [x] dbus-bornay-windplus

Add others to the list.

Until merging, the python3 version lives on a branch called `p3`.

[1]: https://github.com/victronenergy/victronconnect/issues/331

**Comment by izak** [comment]
Note for packages required to run this on venus 2.70.

```
opkg install python3-modules python3-pygobject python3-dbus python3-requests
```

**Comment by jhofstee** [comment]
I will add my own checkboxes here as well...
Python projects that are included in a venus develop version...

- [x] velib-python
- [] systemcalc
- [] dbus-characterdisplay
- [] dbus-digitalinputs
- [] dbus-modbus-client
- [] dbus-mqtt
- [] dbus-recorder (handle unicode on dbus correctly)
- [] dbus-tools
- [] vrmlogger
- [] localsettings
- [] mqtt-rpc
- [ ] dbus-generator
- [ ] dbus-modem
- [] [dbus-imt-si-rs485tc](https://github.com/victronenergy/dbus-imt-si-rs485tc)   (  <--- modbus, so perhaps best integrated into dbus-modbus-client instead)
- [] venus-button-handler
- [ ] dbus-paygo
- [ ] dbus_vebus_to_pvinverter
- [ ] dbus-fzsonick-48tl
- [ ] dbus_pump
- [ ] vesmart-server (Done, but needs [UTF8 improvements][1] to VictronConnect)

**Comment by mpvader** [comment]
CLosing. Part of v2.80; all in; apart  from some bugfixing for which we don't need this issue.
