### ISSUE TITLE
ModbusTCP - make sure all available for ESS is available

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#668]
Now that we have this nice clean user interface:

![image](https://user-images.githubusercontent.com/5200296/86464066-05677400-bd2f-11ea-935c-2ae5ce6760e9.png)

Make sure the ModbusTCP registers are complete. And also make sure they are named properly in the ModbusTCP excelsheet.

Also, in the ESS mode 2 & 3 manual, add above screenshot or whatever to have this properly documented: https://www.victronenergy.com/live/ess:ess_mode_2_and_3

That manual is *the* place for that: its also where our [GX Modbus-TCP manual](https://www.victronenergy.com/live/ccgx:modbustcp_faq) refers to when it comes to ESS.

**Comment by izak** [comment]
Missing registers that could be useful:
```
com.victronenergy.settings:

/Settings/CGwacs/OvervoltageFeedIn
/Settings/CGwacs/PreventFeedback
```

One register for reading (so external processes know whether the limiter is active):
```
com.victronenergy.hub4
/PvPowerLimiterActive
```
