### ISSUE TITLE
node-red: update the ESS node to match new ESS UI

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#669]
Make sure the node-red node is feature complete wrt this, and also that naming is consitent.

![image](https://user-images.githubusercontent.com/5200296/86464450-d30a4680-bd2f-11ea-9014-90fc11edeb93.png)

See also #668

**Comment by mpvader** [comment]
@dirkjanfaber moet hier nog iets mee?

**Comment by dirkjanfaber** [comment]
No, this one can be safely closed.
