### ISSUE TITLE
sort order in gui is incorrect

### ISSUE THREAD

**Issue by audiether** [victronenergy/venus#673]
There is a bug in /opt/victronenergy/gui/qml/PageMain.qml

As the device menus are being built, they are not properly added in alphanumeric order by description (name) as the code suggests.

This line does not properly sort the devices by name:
                model.insert(i, submenu)

In order to sort by name, it needs to be modified to:
                model.insert(i++, submenu)

**Comment by jhofstee** [comment]
duplicate of https://github.com/victronenergy/venus/issues/649

**Comment by mpvader** [comment]
Thank you @audiether ! we’ll look at that.
