### ISSUE TITLE
Ve-direct interface crashes occasionally with VE.Can solarchargers

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#675]
vedirect-interface occasionally crashes and restarts -- observed between 11PM and 4:30AM -- when a VE.Can solar charger is connected via ve.direct. Example, where ttyO0 has nothing connected and ttyO2 has a VE.Can solar charger, to indicate the difference in running time:

```
root@ccgx:~# svstat /service/vedirect-interface.ttyO*
/service/vedirect-interface.ttyO0: up (pid 1175) 259757 seconds, normally down
/service/vedirect-interface.ttyO2: up (pid 24020) 22459 seconds, normally down
```

Affected site: f45eab6ba979

This was observed the same time as [this issue][1]. May or may not be related, pure speculation.

[1]: https://github.com/victronenergy/venus/issues/674

**Comment by mpvader** [comment]
This has been seen, and now not; if serious it will come back: closing.
