### ISSUE TITLE
which GSM/LTE modem would work?

### ISSUE THREAD

**Issue by undee123** [victronenergy/venus#687]
Hi,

information about working GSM/LTE modems are very hard to find here, hope someone could give me a hint about this.
Tried several Huawei and Onda modems, Venus always says "no GSM modem connected" in the settings :-(

Thank you very much!

Andreas

**Comment by mpvader** [comment]
Hi Andreas, the code is written very specifically towards the Simcom SIM5360E (3G module) & SIM7600 (a 4G module).

I've just now updated the readme: https://github.com/victronenergy/dbus-modem/blob/master/README.md.

I'd be surprised if anything else works, we've put zero effort into making it work with other modems, and also have no wish to do so on our side, sorry.
