### ISSUE TITLE
vrmlogger: change code so that it makes the vrm auth token immediately

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#688]
Change code so that it makes the VRM auth token immediately instead of waiting for a first successful post. Waiting for the first successful post was implemented to make sure the was enough entropy for the random number generator. But that's no longer necessary since we now have havegd.

Better to clean it up.

Current implementation makes it first send an announce without token, and thereafter start using tokens. Which is relatively harmless, but for example in the whole remapping circus made the complex story even more complex.

**Comment by wiebeytec** [comment]
Done, put on Venus v2.70 list.
