### ISSUE TITLE
Check Inverter RS VE.Can functionality

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#690]
There looks to have been a regression in v2.60 recently. Details in Slack.

**Comment by jhofstee** [comment]
As already noted here, https://github.com/victronenergy/venus-private/issues/115, the RS inverter was recognized as a vebus with will cause all kinds of issue. So well not done on purpose, it is actually a good thing it is no longer recognized and proper support for it should be added in v2.70.
