### ISSUE TITLE
Marine MFD app configuration menu

### ISSUE THREAD

**Issue by thlassche** [victronenergy/venus#708]
There is this menu on the GUI:

<img width="517" alt="Screenshot 2020-09-22 at 12 31 32" src="https://user-images.githubusercontent.com/2959888/93872058-e3e3ac00-fccf-11ea-8925-88a607e07c75.png">

With the new VRM dashboard, it might be better if we reword that, since VRM also uses the same dbus path to list all batteries. So, setting batteries to visible there will also show them on VRM (if two way communication is enabled)

**Comment by jhofstee** [comment]
Included in v2.70, it is now called "Battery Measurements".
