### ISSUE TITLE
add retry to u-boot autoboot

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#71]
to prevent a beaglebone from getting stuck in u-boot (which I've seen at least two times), because of a stray character on the console serial port.

https://github.com/victronenergy/u-boot/blob/master/doc/README.autoboot

**Comment by mansr** [comment]
Why not check the user button similarly to how it's done on ccgx?

**Comment by mansr** [comment]
It might be hard to reach with a cape in place.

**Comment by mpvader** [comment]
work is done by @mansr 

https://github.com/victronenergy/meta-victronenergy/tree/bootretry

**Comment by mpvader** [comment]
https://github.com/victronenergy/u-boot/commit/40e61ddc78d42bd869fa740896ff722b4cfdb757

part of https://github.com/victronenergy/u-boot/releases/tag/v2015.07-bbb-v4

**Comment by mpvader** [comment]
@jhofstee: I'll leave this for you to close once included in master

**Comment by mpvader** [comment]
Note that the change made does not fix the case that a stray character comes in every second. Which is no problem, what is done now is an easy fix to catches most of the situations: good enough.

**Comment by jhofstee** [comment]
https://github.com/victronenergy/meta-victronenergy/commit/c8696f1d76a26f6d41c5e4bfc9c18821e0086c67
