### ISSUE TITLE
NMEA2000-out: no NACK sent when AC current limit is set to not allowed value

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus#714]
Had an issue with a customer that is using N2K-out to control a Quattro.\
His complaint was that he didn't get a reponse when he had set the AC1 input current limit using VREG `0x214`.

I was able to reproduce and found that `Ac/In/1/CurrentLimitIsAdjustable` was set to `0`. It turned out he had unchecked `Overruled by remote` for AC1 input current limit in VEConfigure. Once I've changed it using remote VEConfigure and  `Ac/In/1/CurrentLimitIsAdjustable` was set to `1`, I got a ACK when setting VREG `0x214`.

No response from Quattro when `Overrule by remote` is unchecked:
```
root@einstein:~# dbus -y com.victronenergy.vebus.ttyS4 /Ac/In/1/CurrentLimitIsAdjustable GetValue
value = 0
root@einstein:~# dbus -y com.victronenergy.vebus.ttyS4 /Ac/In/2/CurrentLimitIsAdjustable GetValue
value = 1
root@einstein:~# ./vreg -c socketcan:can0 -n 0xE2 -s 0x202 un32:7 => Set remote control bits
# NAD 0xE2, reg=0x202
0x07 0x00 0x00 0x00 
root@einstein:~# ./vreg -c socketcan:can0 -n 0xE2 -s 0x214 un16:5000 => Set AC1 to 50.0A
# Error no response received!
root@einstein:~# ./vreg -c socketcan:can0 -n 0xE2 -s 0x224 un16:5000 => Set AC2 to 50.0A
# NAD 0xE2, reg=0x224
0xF4 0x01 0x00 0x00 
```
Also, when writing a value that is out of range and `/Ac/In/n/CurrentLimitIsAdjustable` is set to `1`, no response is received from the Quattro:
```
root@einstein:~# ./vreg -c socketcan:can0 -n 0xE2 -s 0x214 un16:500 => Set to 50.0, which is in range
# NAD 0xE2, reg=0x214
0xF4 0x01 0x00 0x00 
root@einstein:~# ./vreg -c socketcan:can0 -n 0xE2 -s 0x214 un16:5000 => Set to 500.0A, which should be out-of-bounds
# Error no response received!
```

In both cases the Quattro should respond with an error code.

**Comment by mpvader** [comment]
this is a wont fix.

there is no time to fix this in the Multi/Quattro firmware.

And doing it anywhere is is a workaround, and there is no time to do workarounds either.
