### ISSUE TITLE
Show custom tank name on Mobile Overview screen

### ISSUE THREAD

**Issue by Wholistic** [victronenergy/venus#715]
There is now the option to give a tank a custom name, this is shown in the device menu, and on VRM.

But it is NOT shown in the mobile overview screen, where instead it is labeled with the tank type instead. If a custom name is set, it should be shown instead of the default "Fuel, etc" options - see attachments.

<img width="532" alt="CleanShot 2020-10-06 at 22 18 45@2x" src="https://user-images.githubusercontent.com/19315922/95410980-0ed92b80-0971-11eb-8b6b-9042c9308cd2.png">

<img width="523" alt="CleanShot 2020-10-06 at 22 20 23@2x" src="https://user-images.githubusercontent.com/19315922/95410992-14367600-0971-11eb-9806-ebfedaad58c8.png">

<img width="525" alt="CleanShot 2020-10-08 at 14 19 36@2x" src="https://user-images.githubusercontent.com/19315922/95411108-58297b00-0971-11eb-82a7-cec6707f2831.png">

**Comment by jhofstee** [comment]
done, for sure included in v2.70~16. Likely earlier already.
