### ISSUE TITLE
No AC Input

### ISSUE THREAD

**Issue by Barpo** [victronenergy/venus#718]
Hi,

Im rather new in venus pi. I connected a CG powermeter EM111. I can see the grid meter readings like AC Phase L1.
How come I do not get AC Input?

mvg Barry

![2020-10-27_08-29-02](https://user-images.githubusercontent.com/10188886/97272665-8a245380-1832-11eb-8ed0-7a236e9008e9.jpg)

**Comment by Yuphorya** [comment]
Interested if you got this working? I plan to do the same.

**Comment by Wholistic** [comment]
Hi @Barpo and @Yuphorya,

The AC input display requires a Victron Inverter Charger to be connected, there is some more info in this Victron Community discussion here - https://community.victronenergy.com/questions/46152/possible-for-cerbo-gx-to-show-incoming-power-witho.html

This is working as intended. 

Any further conversation on this would probably be best located in the modifications space here - https://community.victronenergy.com/spaces/31/index.html
