### ISSUE TITLE
make the 4 LEDs indicate that its in u-boot

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#72]
The goal is to easily recognize that a unit is (stuck) in u-boot.

The only way to signal something to a user is to use the LEDs. Best would be to use the four user LEDs on the bbe / bbb. Since then it also works for customers that do not have the vecape.

**Comment by mpvader** [comment]
By the way, when all mounted together with the cape and in the enclosure, those four LEDs are no longer visible. The red/green on the cape LED is though. See LD101 on the [v0.61 schematic](https://github.com/victronenergy/bbb-hardware/blob/master/VE_BBB_Cape_v0.61_released.pdf).

**Comment by mpvader** [comment]
Done: https://github.com/victronenergy/u-boot/commit/40e61ddc78d42bd869fa740896ff722b4cfdb757

Part of https://github.com/victronenergy/u-boot/releases/tag/v2015.07-bbb-v4

**Comment by mansr** [comment]
LED indications:
- USR3 / cape red: u-boot started
- USR2 / cape green: booting kernel

**Comment by jhofstee** [comment]
ok included, slightly rewrite (recipes was renamed)
https://github.com/victronenergy/meta-victronenergy/commit/c8696f1d76a26f6d41c5e4bfc9c18821e0086c67

and with a fix for gpio number...
https://github.com/victronenergy/meta-victronenergy/commit/2eef420ab6cf013f7452e6718254b76ae67b5568

(linux will reset the gpio directly though, so they are turned almost off again, but lets make that a separate issue, closing this)
