### ISSUE TITLE
Feature request - relay control based on selectable temperature sensor

### ISSUE THREAD

**Issue by Wholistic** [victronenergy/venus#721]
Much like how you can start a pump using the relay based on a tank level sensor reading, 

Would be nice if you could open or close the relay based on a temperature reading. 

For example, if temp gets >30 degrees, start the air conditioner or fans, until temp drops below 25 degrees. 

Of course - this can already be done via Node Red (sort of).

**Comment by nmbath** [comment]
Not sure if this is of any help, but here is a dbus service to control a relay based on temperature probes. Very similar to the Pump dbus service. I also copied the test harness from the pump service and it passes!

I also modified the velib_python file vedbus.py to use /Mgmt rather than /management

I have enumerated the relays so it can be applied to either relay 1 or 2.

If this can be used to speed up delivery a number of people in the community would be very pleased.


[dbus-temperatureSwitch.tar.zip](https://github.com/victronenergy/venus/files/5725601/dbus-temperatureSwitch.tar.zip)

**Comment by nmbath** [comment]
Further to my previous comment attached is a opkg package that will modify the system allowing temperature control of the relays. It also includes some changes to the dbus-digitalinputs to support input types from a BMS for Allow to Charge, Allow to Discharge and Pre Alarm.

The relay can be associated with any temperature source, either an analogue temperature input or a battery monitor providing /Dc/0/Temperature.

If this is of use please do use.


[MB-Modifications_0.1_cortexa7hf-neon-vfpv4.ipk.zip](https://github.com/victronenergy/venus/files/5762010/MB-Modifications_0.1_cortexa7hf-neon-vfpv4.ipk.zip)

**Comment by jepefe** [comment]
This feature has been implemented and added to the ToDo for including it in Venus.

The implementation supports two conditions per temperature sensor where each one consist on a temperature range (high or low) where the configured relay must be closed.

For example a temperature sensor in the battery cabinet can be used to switch on a fan in case of high temperature or a resistor to keep a Lithium battery above the cut-off temperature:

Condition 1
Activation temperature: 35ºC
Deactivation temperature: 25ºC
Relay: 1

Condition 2
Activation temperature: 4ºC
Deactivation temperature: 10ºC
Relay: 2

Both conditions can be set to activate the same relay. This might be useful to switch on an air conditioner (set to auto) in case of high or low temperatures.

Multiple sensors can control the same relay. Relay will keep closed as long as there are one active condition of any sensor.

Conditions can be configured in two places. 
  1. From the temperature sensor menu: Devices list -> Temp sensor -> Setup -> Relay

<img width="492" alt="Screenshot 2021-12-10 at 14 46 55" src="https://user-images.githubusercontent.com/6424631/145589581-13ef27b7-5849-4cb3-97ba-ce2f2d469466.png">
<img width="490" alt="Screenshot 2021-12-10 at 14 47 02" src="https://user-images.githubusercontent.com/6424631/145589712-96febe7f-cd9a-4845-b098-19d4e02af3bb.png">

  2. From the relay settings page(Settings -> Relay -> Temperature sensors), here a the sensors are listed showing the condition values to check them all in a glance. This menu is only shown if at least one of the relays is configured as a temperature relay.
  
<img width="487" alt="Screenshot 2021-12-10 at 15 27 09" src="https://user-images.githubusercontent.com/6424631/145590067-6c6b1f26-6c6f-4d15-969d-60ade9872f86.png">
<img width="488" alt="Screenshot 2021-12-10 at 15 32 59" src="https://user-images.githubusercontent.com/6424631/145590363-4f84fe11-0365-4d8e-bbf3-00078fe4ad45.png">
 <img width="493" alt="Screenshot 2021-12-10 at 14 56 38" src="https://user-images.githubusercontent.com/6424631/145589746-349f68c2-c45b-43cb-86c5-f9703740653d.png">
<img width="489" alt="Screenshot 2021-12-10 at 14 56 25" src="https://user-images.githubusercontent.com/6424631/145590127-66403f9a-670f-4fb5-96e9-d337f2cd353e.png">

**Comment by mpvader** [comment]
Great!

**Comment by lennycb** [comment]
@jepefe What has to be done to use this with the internal CPU temp sensor from the Pi4 or a DS18B20 1-wire sensor.
According to the description, entries for the sensors and their values should be in the "Temperature sensors" tile. But is missing with me. What did i forget?
![Geräteliste](https://user-images.githubusercontent.com/23618370/147773658-32bb9683-d2d2-474e-b78f-b69d0ffefc69.JPG)
![Relais](https://user-images.githubusercontent.com/23618370/147773661-40ce9535-05f3-417c-b555-bdcd389fff20.JPG)
![Setup](https://user-images.githubusercontent.com/23618370/147773662-51d38601-8a8f-441e-aef7-19b458a0b349.JPG)
![Temp_Sensors](https://user-images.githubusercontent.com/23618370/147773663-8978f36e-5aae-4408-bd5a-46a089b74a7c.JPG)

**Comment by kwindrem** [comment]
This should be better discussed in the community forum.

I recall seeing a mod to make the RPI temp sensor visible. I tried it and worked fine but has not been upgraded for V2.80 (Python 3).

**Comment by lennycb** [comment]
Hi @kwindrem, I have no problem with the ad. I've already adjusted the mod. See forum:
[https://community.victronenergy.com/questions/58792/raspberry-pi-3b-heat-temperature.html?childToView=113688#comment-113688](url)

So, they are displayed as they should, but unfortunately I cannot control relays with the sensors. I'm not sure if this is only intended for the RuuviTags.

**Comment by kwindrem** [comment]
Made a couple of tweaks to LHardwick's code to:

1) make it run on both python 2 and 3

2) make the CPU temp alarm relays available 

The second problem was that the dbus service name included a dash (-) which caused com.victronenergy.temprelay to crash. Changed the - to _ and the alarm settings show up in the CPU temp sensor Setup menu.
[dbus-i2c.py.zip](https://github.com/victronenergy/venus/files/7797001/dbus-i2c.py.zip)

**Comment by lennycb** [comment]
Great, works. I hadn't thought of a change for Python2 and Python3. Will become obsolete after an update to Venus> v2.80.

What error are you seeing here?
# --------------------- was causing an error
#from w1thermsensor import W1ThermSensor
# ---------------------
I had to activate it again to read my DS18B20.

This library is normally not included and must be installed later.
To do this, I first had to install PIP, then the library.

**Comment by kwindrem** [comment]
The error was that the import file could not be found but that makes sense based on your explanation.

I wrapped a try: except: pass around the import statement so it no longer fails:

[dbus-i2c.py.zip](https://github.com/victronenergy/venus/files/7797972/dbus-i2c.py.zip)

Here's my setup script that uses SetupHelper if you are interested:

[RpiTemp.zip](https://github.com/victronenergy/venus/files/7797978/RpiTemp.zip)

You should be able to add the missing bits for the w1... stuff

To make this work with auto download and install, it needs to be available on GitHub. I generally set up a 'latest' tag for the most recent released version but that's optional. The branch/tag in PackageManager can simply be set to 'main'. You may wish to change the package name back to what you are using now.
