### ISSUE TITLE
Fix SSH tunnel on installations with IPv4-over-IPv6

### ISSUE THREAD

**Issue by wiebeytec** [victronenergy/venus#725]
setup-tunnel.sh looks in `/proc/net/tcp` to report which remote server is used. ~~When an installation has active IPv6, the local bind done by SSH is in the IPv6 address space and therefore `/proc/net/tcp6`. This results in the SSH session being disconnected right away, and retried ad infinitum.~~

~~Fix: not just `-4` to the ssh command, but making `get_ip_of_relay_server.py` fully IPv6 compatible.~~

On connections that use (some form of) IPv4-over-IPv6 tunneling, this breaks. The US server's IP is 35.165.124.40. In hex from `/proc/net/tcp`, that's `287CA523`. The address of `supporthosts.victronenergy.com` reported by an installation with this kind of network was `64:ff9b::23a5:7c28`. That's the IPv4 address mapped in reverse byte order.

Reporting the the remote IP address subsequently fails.

**Comment by mpvader** [comment]
included in v2.70 & v2.62~5
