### ISSUE TITLE
bbb: start watchdog from u-boot

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#73]
right now (I assume that) the bootloader is only started from userland. And therefore not protecting against hangs while starting Linux.

This same issue exists for the ccgx: #74

Some links:
- https://github.com/victronenergy/u-boot/blob/beaglebone/doc/README.watchdog
- https://e2e.ti.com/support/arm/sitara_arm/f/791/p/495092/1792799

**Comment by mpvader** [comment]
right now (I assume) the bootloader is only started from userland. And therefore not protecting against hangs while starting Linux.

https://github.com/victronenergy/u-boot/blob/beaglebone/doc/README.watchdog

https://e2e.ti.com/support/arm/sitara_arm/f/791/p/495092/1792799

**Comment by jhofstee** [comment]
hello Matthijs,

Starting the watchdog is already done in u-boot. However linux disables it directly again. We can prevent that if we want https://github.com/victronenergy/linux/commit/b3f0c4a6f188a04609a2e561f031c85d07b73826. Assigning to @mansr. 

Mans, any thought on this?

**Comment by jhofstee** [comment]
@mansr 

lets back-port these:
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers/watchdog/omap_wdt.c?id=b2102eb36e7909c779e46f66595fda75aa219f4c
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers/watchdog/omap_wdt.c?id=8605fec1ce2a397f738f1c394be7847dacf31b0c

It boils down to same thing, but there is a bootparam to control behavior so we can make sure it is only enabled when booting from onboard mmc and not when updating etc.

**Comment by jhofstee** [comment]
included in v2.01~10. You need to opt-in for keeping the watchdog alive during boot, see https://github.com/victronenergy/meta-victronenergy/commit/69f38b3beeb6ba98bbe688dc49a627c45b5d1fc4
