### ISSUE TITLE
GUI Device List: Add summary for IMT

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#734]
Its currently missing:
![image](https://user-images.githubusercontent.com/5200296/99950578-01d79680-2d7d-11eb-8ce1-1e5f3850a7f1.png)

I'd say just add the W/m2 number. Not temperature & wind, though, looking at this one, there is space (if we shorten the long IMT name a bit).

up to you, @izak 

![image](https://user-images.githubusercontent.com/5200296/99950719-42371480-2d7d-11eb-8636-d8140cbabc12.png)

**Comment by izak** [comment]
![Selection_749](https://user-images.githubusercontent.com/851549/102596195-8077e780-4121-11eb-91be-97af1f71c243.png)
