### ISSUE TITLE
Disable translations for "Update feed"

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#738]
Its translated wrongly in Dutch, but also for other langauges I can imagine that its a hard one to translate.

pls simply make it "untranslatable".

thanks.

![image](https://user-images.githubusercontent.com/5200296/100072616-c4d2d900-2e3c-11eb-8fc2-debb0674faa3.png)

**Comment by jepefe** [comment]
Done in fix_update_feed_translation branch and added to the todo.

**Comment by jhofstee** [comment]
included in gui v4.7.2 / venus v2.70~3
