### ISSUE TITLE
DVCC is not forced for BYD Premium and B-Box L batteries

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#739]
DVCC is forced on for B-Box Pro batteries but should also be turned on for the other models.

**Comment by Wholistic** [comment]
Would be nice for me at least if the little documented super user credentials could still override this (as a last resort when DVCC is cause of issues such as cell balancing and voltages need to be manually reduced below spec to prevent shutdown before balance can occur).

**Comment by mpvader** [comment]
I'll think a bit about that, but do know that its (a) out of scope of this change. (b) I'm not so sure what the priority of that is (?)
