### ISSUE TITLE
DigitalInput settings not reset when function changed or disabled

### ISSUE THREAD

**Issue by nmbath** [victronenergy/venus#744]
In working on a project involving digitalinput, I have noticed that when an input is disabled and then changed to a new function or moved from one function to another the settings under com.victronenergy.settings for that digital interface are not reset.

If for example a digitalinput is assigned to the function bilge pump, and an alarm set. Then set that digital interface to disabled or another function such as bilge alarm, the alarm is still set, as will all other settings.

While a digital input should not have its function changed that often, when reconfiguring things having them reset to default does make for an easier life. At a minimum 'Settings/DigitalInput/{}/Count' should be reset.

I have had a look around the dbus-digitalinputs driver and can see where the input is assigned or unassigned to a function within 'def handle_setting_change(inp, setting, old, new):" by calling register_gpio(inputs[inp], inp, bus, settings)  and unregister_gpio(inp)  

 
If you would rather these code related issues are reported on the community forum, then please do say and I shall report anything further their. I just feel they are a little too technical for that forum.

**Comment by mpvader** [comment]
Thank you @nmbath , Izak will look into this.
