### ISSUE TITLE
Cerbo GX and vebus_standby io lines

### ISSUE THREAD

**Issue by nmbath** [victronenergy/venus#745]
I have been doing some testing and found that the Cerbo GX does not always set the vebus_standby. I have a test rig that has an LED connected between positive and pin 6. Therefore when the VEBus Standby is pulled to ground the Led lights.

Today while doing some testing I noticed that when the Cerbo GX completed a redirect (under the Advanced page) the LED is lit. After the inverter shuts down due to load disconnect, and then restarts as allow to discharge becomes re-enabled the LED does not come back on.

System is running 2-Wire BMS assistant. I have not explored further and have no idea if this is correct behaviour or a bug. 

If there are further tests you would like me to do please advise. I plan to do further checks myself when next with the system.

**Comment by vejpasop** [comment]
This is correct. During the re-detect the standby line is only active during ~10 seconds. This wakes up the Multi.  After that the Multi keeps itself alive depending on the mode it was in "on/off/charger only"
