### ISSUE TITLE
Possible Bug in VRM related to Digital Inputs

### ISSUE THREAD

**Issue by nmbath** [victronenergy/venus#750]
Looking at devices in VRM, a digital input is presented as type NMEA 2000 GPS! 

In VenusOS they have an ID of 41316. Should VRM not map this ID to Digital Input?

<img width="706" alt="15141-1606901672605" src="https://user-images.githubusercontent.com/73959588/100916506-bd12d480-34cd-11eb-9ca0-80d7ad94244d.png">
<img width="965" alt="15131-screenshot-2020-12-02-at-093104" src="https://user-images.githubusercontent.com/73959588/100916514-c13ef200-34cd-11eb-82d4-9433401606e2.png">

**Comment by nmbath** [comment]
https://github.com/victronenergy/venus/issues/752

**Comment by mpvader** [comment]
Thank for reporting this @nmbath .
