### ISSUE TITLE
managed batteries: Log blocking status of MOSFETs to VRM

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#755]
For managed batteries that support it, these paths have been available on dbus and the gui for some time now. Log also to VRM:
```
/System/NrOfModulesBlockingCharge
/System/NrOfModulesBlockingDischarge
/System/NrOfModulesOffline
/System/NrOfModulesOnline
```

TODO
- [x] Add diagnostic paths to vrmlogger
- [x] Add warning (alarm path) to can-bus-bms to alert to condition.
- [x] Log warning to VRM (attributes `Abc` and `Abd` already requested)

**Comment by izak** [comment]
Implementation of a warning path is in `can-bus-bms` branch `blocking-warnings`.

**Comment by mpvader** [comment]
Changing this to v2.70.

With BYD now confirmed as having those fields not working properly (and us thus removing them from being visible), and also BYD being the only one that we're aware of that even has those fields; its all non-urgent anymore.

**Comment by mpvader** [comment]
@izak whats the status of this?

all done and can be closed? and whats the status with BYD about this? Do you know?

**Comment by izak** [comment]
Presently this is explicitly unsupported on BYD batteries, even though the Premium LV sends this information. That's because the information is incorrect in earlier firmware versions.

I tested a new firmware version where it works correctly. I do now know if that firmware is released yet. There were other issues with that firmware too. I will take it up with them and revert here.

**Comment by mpvader** [comment]
ok but our side works right? And Pylon has official support for this, right? @izak 

if yes, please close this

**Comment by izak** [comment]
Our side works correctly. Pylontech is in a similar boat to BYD: Wrapping up last minute changes. I'll go ahead and close it as this is being handled elsewhere.
