### ISSUE TITLE
install-sdcard: ubiformat should not ask questions...

### ISSUE THREAD

**Issue by jhofstee** [victronenergy/venus#76]
either error or force some action:

libscan: scanning eraseblock 3967 -- 100 % complete  12.446319] uncorrectable error : e
ubiformat: 1557 eraseblocks have valid erase counter, mean value is 67
ubiformat: 2411 eraseblocks are supposedly empty
ubiformat: warning!: only 1557 of 3968 eraseblocks have valid erase counter
ubiformat: erase counter 0 will be used for all eraseblocks
ubiformat: note, arbitrary erase counter value may be specified using -e option
ubiformat: continue? (y/N)

**Comment by mpvader** [comment]
fixed in https://github.com/victronenergy/meta-victronenergy/commit/229b5004384f5c6bca21b03686bd140f8a820d64
