### ISSUE TITLE
venus-large: varia

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#765]
I'll use this issue to keep note of various things I come accross while working with the large images.

### 1. Offline update not working: large .swu file not recognised by existing images.

When building a venus-large image, the end result is called, for example `venus-swu-large-raspberrypi4-20210107065823-v2.70~2-large-image-8.swu`. But with that `-large` in the file name, todays Venus OS doesn't recognise the file. To reproduce, write that file to a usb disk, insert in GX Device which is running v2.60, and in the gui try updating it. That will fail; until you remove the `-large` from the file name.

**Comment by mpvader** [comment]
Added (2).

**Comment by nmbath** [comment]
Good evening. 

I am not sure if the attached logs will help with point 2. I have managed to use software update on a Cerbo without problem. My Raspberry Pi fails, even when I rename the file to remove the -large.

The filenames that failed on the Raspberry Pi are:
venus-swu-raspberrypi2-20210111135948-v2.70~3-large-10.swu
venus-swu-raspberrypi2-20210111135948-v2.70~3-10.swu

Even when I manually request the upgrade using these commands it fails

/opt/victronenergy/swupdate-scripts/check-updates.sh -swu /media/sda1/venus-swu-raspberrypi2-20210111135948-v2.70~3-large-10.swu

or 

swupdate -v -i venus-swu-raspberrypi2-20210111135948-v2.70~3-10.swu -e "stable,copy2"

It seems to be something in the embedded file venus-image-large-raspberrypi2.ext4.gz  that is causing an issue.

[Cerbo - Success.txt](https://github.com/victronenergy/venus/files/5798381/Cerbo.-.Success.txt)
[Raspberry Pi - Failed.txt](https://github.com/victronenergy/venus/files/5798391/Raspberry.Pi.-.Failed.txt)

**Comment by mpvader** [comment]
Oh yes. I’m pretty sure you’ll need to reflash the rpi - unfortunate as that may be. We changed some things making the old flashed cards incompatible. See here:

https://github.com/victronenergy/meta-victronenergy/commit/892d2c117e46239baa095f85b2c2f94b3d36b75f

**Comment by mpvader** [comment]
Ps; needs mentioning in changelogs ofcourse. Thanks for bringing it up! I’ll make sure and then add it

**Comment by mpvader** [comment]
Fixed
