### ISSUE TITLE
vedirect: GetValue on root dbus path does not return all possible paths

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#771]
Symptoms: Solar chargers are not sent a voltage setpoint by systemcalc.
Reason: dbusmonitor in velib_python doesn't think the `/Link/ChargeVoltage` exists, because it wasn't in the returned object when it called GetValue on `/`.

More details: It seems that when calling GetValue on the root of the service, only vregs that have been fetched at that point are in the returned object (not confirmed, really difficult to confirm due to the close timing). This means that if systemcalc (or any other program) scans the new solarcharger service, it will think some paths are not supported.

If this is also a path that will not later change value and send a `PropertiesChanged`, it will be considered unsupported.

The effect is that there is a race condition, depending on how fast systemcalc scans the service after it becomes available on dbus.

A possible fix may already be in `thiemo/WIP_registerWhenFetched`.

**Comment by ThiemoVanEngelen** [comment]
Solved in vedirect-interface v3.56.
