### ISSUE TITLE
gui: add are you sure message to wifi disable action

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#773]
https://community.victronenergy.com/questions/73895/gx-software-menu-recommendation.html

**Comment by jepefe** [comment]
Confirmation request added to Wi-Fi access point on/off and forget network.
Added to the todo, branch: feat_wifi_confirmation


https://user-images.githubusercontent.com/6424631/129495559-9858a21e-9ca6-4af1-9564-15027ff75fec.mov

**Comment by jhofstee** [comment]
![image](https://user-images.githubusercontent.com/1315205/169659162-35fca58f-cb20-4f9d-9d7f-07519d60979b.png)
merged
