### ISSUE TITLE
Add view of comm error counters

### ISSUE THREAD

**Issue by tabreu** [victronenergy/venus#775]
In order to allow a better VE.Can communication analysis of the MPPTs, it is good to have some communication error counters available in  venus and also in the VRM. The counters are send on request on the following VREGs:

- VE_REG_RX_HW_OVERFLOW_COUNT (0x0130) - Stats RX HW overflow count 
- VE_REG_RX_SW_OVERFLOW_COUNT (0x0131) - Stats RX SW overflow count
- VE_REG_ERROR_PASSIVE_COUNT (0x0132) - Stats Error Passive count
- VE_REG_BUSOFF_COUNT (0x0133) - Stats Bus Off count
- VE_REG_PAYLOAD_OVERRUN_COUNT (0x0134) - Stats Payload Overrun count
- VE_REG_TX_ERROR_COUNT (0x0135) - Stats Tx Error count

VE.Can MPPT version v3.04 and above will have the counter available and implemented.

**Comment by jhofstee** [comment]
There is no need for that. They can be requested from the command line if they are needed. They error counters of the Venus device is already shown in the user interface. And since all devices on a CAN-bus see the errors they will already indicate if there is a problem.
