### ISSUE TITLE
Python "runpy" required to run Ansible to install stuff

### ISSUE THREAD

**Issue by IoTPlay** [victronenergy/venus#777]
Hi, I want to use Ansible from my Mac to install node-red on EasySolar-II GX - I get stuck where Ansible - when it gathers facts on venus.local. Btw. I do not think this has anything to do with Ansible - but probably a missing python module, or even needing a python upgrade. I did set the Ansible interpreter to python2.7 - which seams the only python available on VenusOS. 

Ansible throws an error as follows:  `import runpy\r\nImportError: No module named runpy`

My questions:
a) Can I upgrade / install python3 on the VenusOS?
b) Or - should I wait - will Python3 come with VenusOS soon?
c) Or - is there a way to install what looks like a missing python module, called **runpy** ?
  
(Ohh, btw - I can log into ssh root@venus.local - have done all those steps on https://www.victronenergy.com/live/ccgx:root_access )

**Comment by mpvader** [comment]
Hi,

c) Python3 is currently not installed on Venus OS yet. You could install it: run opkg update, and then opkg list-installed | grep python3, or something similar like that. opkg lets you install "online available but not default installed" packages. See the Venus OS commandline manuals as well as google for more info. I had a quick look, and looks like python3 is available for download and install; disclaimer: I have no idea what breaks if you do that, maybe nothing, or worst case the GX Card in the EasySolar doesn't properly boot properly any more and you'd need to find your way into the serial console.

b) We are preparing to switch from Python 2.7 to Python3, can take anything between  1 month or much longer from now until we have it done and available in a beta.

c) yes probably you can install runpy python2.7 module. Google a bit to find out in which OE/opkg  recipe its included. v2.62, which I assume you are using, is based on the Rocko version of OE.

For further questions like this, can I ask you to use either the mailinglist or the Modifications section on https://community.victronenergy.com/ ?

Lastly, we have images with node-red preinstalled, see here: https://www.victronenergy.com/live/venus-os:extended.

all the best, Matthijs

**Comment by IoTPlay** [comment]
Thank you !!!
