### ISSUE TITLE
dvcc: Force settings for pylontech

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#784]
Todo list

- [x] Implement and include (done per v2.80-something)

**Comment by izak** [comment]
Rather than force the settings, which will affect a very large number of users, I updated the documentation.

**Comment by mpvader** [comment]
Ok but lets keep the issue open still; we need to fix this somehow someday.

And which documentation did you update? Don’t forget to check the gx manual.

**Comment by izak** [comment]
Some statistics that may be helpful.

Total of 8115 Pylontech batteries on VRM.

| Total installations | DVCC on | DVCC off | % |
|---|---|---|---|
| All installations | 7083 | 1032 | 12% |
| Venus OS >= 2.50 | 6882 | 940 | 12% |
| Venus OS >= 2.60 | 6168 | 825 | 12% |

Roughly 12% of Pylontech installations don't use DVCC.

**Comment by mpvader** [comment]
very helpful! lets force it on. and then make sure to do it at the start of a beta series that takes a while. Ie the complete opposite of what would happen if we'd make that change now in the latest v2.70 release candidate.

**Comment by mpvader** [comment]
closing. doc updates going into https://github.com/victronenergy/venus/issues/882
