### ISSUE TITLE
dbus-modbustcp: Add register for com.victronenergy.vebus/Hub4/FixSolarOffsetTo100mV

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#785]
When using external control, there is presently no way to change the solar offset. This has the unfortunate side effect of using a much larger offset than some Lithium batteries are happy with.

**Comment by mpvader** [comment]
After release, this document needs updating: https://www.victronenergy.com/live/ess:ess_mode_2_and_3.

Lets keep the issue open until thats done.

**Comment by mpvader** [comment]
@izak , looks like a document needs updating, will you take care of that and then close this issue?

**Comment by izak** [comment]
Document updated, excel spreadsheet also sent to be updated on website. Closing.
