### ISSUE TITLE
Touchscreen configuration scripts gone?

### ISSUE THREAD

**Issue by Schmiedgasse** [victronenergy/venus#786]
Hi all,

I can't find the information for the touchscreen configuration on https://github.com/kwindrem/Raspberry-Pi-7-Touchscreen-for-VenusOS anymore. The link only gives a 404 back.

Are the scripts and the git where it was gone?
Is there another source for it?

Regards

Martin

**Comment by mpvader** [comment]
Hi, sorry but thats nothing from Victron; I can help you. Perhaps ask kwindrem on community. I’ll close this issue now

**Comment by kwindrem** [comment]
Yes, things have moved and completely rewritten. Sorry. New link:

https://github.com/kwindrem/RpiDisplaySeutp-for-VenusOs
