### ISSUE TITLE
mqtt-rpc: Add remote firmware update feature for GX device.

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#788]
TODO
- [x] List GX device in device list
- [x] Call `check-updates.sh -swu URL` with returned url if type is `swu`.
- [x] Document in README.txt
- [x] Prep system for El Nino to implement VRM support
- [x] Merge it into master and list on the TODO

May have some overlap with https://github.com/victronenergy/venus/issues/634

**Comment by mpvader** [comment]
This was waiting for it to be deployed on VRM by the VRM developers. But as discussed just now, we can already merge it now; its better.

**Comment by mpvader** [comment]
@izak, I did a quick test, and doesn't seem to work?

See the error 1342 in the screenshot.

Also, would be nice to have the GX Device at the top; just like in the Device List on VRM.

![image](https://user-images.githubusercontent.com/5200296/146260696-c1eb7c7d-e179-4a05-9b21-d823738462bd.png)

**Comment by mpvader** [comment]
Implementation is complete in Venus v2.80. Whats missing is implementation in VRM, which is documented here: 

https://github.com/victronenergy/vrm-portal/issues/228

I'll discuss with Barbara.

I'm leaving this issue open, to not forget to follow up if need be.

**Comment by mpvader** [comment]
status, as discussed just now [https://victrondevelopment.slack.com/archives/CJJ24D30X/p1660658817546049](here): this feature is finished in both Venus OS, as well as VRM. But not yet deployed to production of VRM, which will do only a while *after* releasing v2.90 officially. 

More on that in the linked thread.

**Comment by izak** [comment]
I looked in the wrong place. This is indeed not deployed yet. Reopening.

**Comment by mpvader** [comment]
@izak can this now be closed? Iirc this feature is now deployed?

**Comment by izak** [comment]
Yes. Closing.
