### ISSUE TITLE
GUI: vecan-dbus Multi product name not shown 

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#797]
Only the general "Multi - Inverter / Charger" name is shown.

![image](https://user-images.githubusercontent.com/10847324/110483252-d4bfb180-80e9-11eb-88a4-eadeb9c9c9d2.png)

Product name on the dbus is correct.

![image](https://user-images.githubusercontent.com/10847324/110483495-0a649a80-80ea-11eb-9428-e343ae1e5c6e.png)

**Comment by jhofstee** [comment]
The CAN cable is no longer supported (which looks to be used in this case). Perhaps check the custom name? This doesn't seem to be an issue. Feel free to open it otherwise.
