### ISSUE TITLE
DVCC: Make it work well with the RS Smart inverter

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#803]
TODO

- [x] Copy battery parameters (DCL, CVL) across to /Link parameters
- [x] Share CCL across solar chargers and inverters (and decide if there will be a priority)
- [x] Write SVS and SCS across for VE.Direct connections (already works with CAN-connection)
- [x] In system with Multi and RS-Smart, ESS assistant controls charge voltage of inverter (or?)

**Comment by mpvader** [comment]
Hi, VE.Bus Multi + RS Smart Inverter can for me be a non supported combination.

if people have VE.Bus Multis and want more solar they can buy a MPPT RS. And if they want more inverter power they can buy another VE.Bus MultiPlus.
