### ISSUE TITLE
remove dbus-redflow

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#81]
## Background
The new way of connecting is that the installation as a Redflow product called the Z-Cell BMS. A RaspberryPi. Which communicates its SOC over ModbusTCP into our VE.Bus SOC field. Which is all it does, and which works beautifully.

The Z-Cell BMS is about to support the canbus-bms protocol, and besides that it might also be possible to communicatie those same BMS parameters over modbustcp.

## Action
All existing installations have been converted to using the Z-Cell BMS. So time to clean up and take this code out:

- [x] remove it from serial starter
- [x] remove it from the gui code
- [x] remove the service from OE
- [x] remove it from documentation

**Comment by mpvader** [comment]
- [ ] remove the service
- [ ] remove it from serial starter
- [ ] remove it from the gui code
- [ ] remove it from documentation

**Comment by edevries-victron** [comment]
We should also remove all references to the com.victronenergy.zbmnode (created by dbus-redflow) service from VRM logger.
BTW. This service is not supported by modbus TCP.

**Comment by mpvader** [comment]
@edevries-victron: fyi this is on hold. Its still actively used in South Africa.

**Comment by jhofstee** [comment]
can this be removed by now or should it be closed?

**Comment by mpvader** [comment]
Yes it can be removed now.

**Comment by mpvader** [comment]
I checked the CCGX manual as well as battery compatibility pages: its no longer mentioned; which ticks the last box. closing.
