### ISSUE TITLE
Beaglebone: make it look for swu version 2

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#812]
Background: Venus GXes were first produced with "small" partition sizes. And somewhere in 2018 that was changed to "large". Venus OS rootfs is slowly growing in size, and recently we had to reduce the standard freespace allocation by OE to keep the images small enough to fit on "small" variant. Also, per v2.70, a script was added that will automatically increase the partition sizes at boot (without losing data) from "small" to "large". Which is a fine status quo, until Venus OS really outgrows the "small" partition sizes.

This issue is to prepare for that, by introducing a swu version 2. By having that, we can force customers using < v2.70 to always update to v2.70 first. Which at boot will increase the partition sizes; after which customer can continue updating to later (larger) versions of Venus OS.

For customers using the online update system, all will then go by itself. Customers using offline updates will have to manually put in a v2.70 (or some tbd latest version). Boot that, and will then be able to move to later versions again.

- [x] we’ll release v2.70 including a patch to keep the rootfs small. (using the bbb-patch that goes into master today/tomorrow). And including the resize function (already in master). 
- [x] next a patch needs adding that (from then on) it looks for swu version 2 (thats what this issue is about).
- [x] vXXX will be released with increased swu version, forcing customers to update to v2.70 first

**Comment by mansr** [comment]
The changes are in https://github.com/victronenergy/meta-victronenergy/commits/mans/bbb-swu. The first commit should be included in a 2.7x release, the rest only for 2.80. This ensures that systems running older versions will first update to the latest 2.7x. This version will resize the root partitions and start using swu version 2. Builds of 2.80 can thus drop venus-swu-1, the rootfs size adjustment, and the repartioning script.
