### ISSUE TITLE
can-bus-bms: Increase possible CCL and DCL max (currently limited to 3276A)

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#817]
The protocol documentation of many batteries indicate that the CCL and DCL is sent as a signed 16-bit number, scaled with one decimal.

A negative value doesn't make any sense, but simply changing the spec doesn't change the fact that multiple battery makers specify it as a signed 16-bit integer with one decimal.

This limits the maximum discharge current to around 160kW. The maximum theoretical Victron system is already 180kW.

Even if we violate the specification and treat this as an unsigned number, the new limit is still conceivable reachable in the near future.

A better long-term solution is to extend the protocol with a new CAN message that uses a 32-bit number, without decimals. There is no reason to specify a charge/discharge current limit to the nearest 100mA.

TODO
- [ ] Add a CAN message with two UN32 values for the charge and discharge current
- [ ] If a battery sends both the old message and the new one, use the new one.
- [ ] Update the CAN-bms documentation

**Comment by mpvader** [comment]
This has been increased already to 6553. Further increases will require a new can frame; and since there is no customer asking for this we won't do this now - closing.

btw 6553 amps at 50V = 327.650 kWh.
