### ISSUE TITLE
gui process unaware of whether the display is on

### ISSUE THREAD

**Issue by tyandersen** [victronenergy/venus#818]
I have a CCGX running 2.66 (build date 20210411213304). 

My particular CCGX is installed on a sailboat and has a lot of items connected(*1).

This unit is regularly fully loaded (top shows cpu 0% idle, loadavg is always above 2.5, usually around 3, and if I have everything reporting hovers just over 4, but can be high enough to trigger the watchdog) (*1)(*2).

I realize there are workarounds to these problems (get a second CCGX, for example), but I noticed:

- the gui process uses about 13% cpu (on my device) deterministically when the "Overview" page is on the screen. 
- the gui process uses about 5% cpu (on my device) deterministically when a blank page (specifically the "Notifications" page from the menu) is on the screen.

Here's the kicker: Those numbers are irrespective of whether the display is on or not. *Most* of the time, the display is off. This shows a considerable amount of cpu savings potential for the CCGX just by identifying whether the display is on.

(*1) See https://community.victronenergy.com/questions/86744/ccgx-load-too-high.html
(*2) Watchdog currently configured to trip when the 5- or 15-minute load surpasses 6.

**Comment by mpvader** [comment]
Hi @tyandersen , I answered on Community; I’ll close this issue to keep it in one place
