### ISSUE TITLE
Reduced bandwith keep-alive mechanism proposal

### ISSUE THREAD

**Issue by thlassche** [victronenergy/venus#819]
**Reason:** Some MQTT users in the field raised concerns regarding data usage when enabling MQTT on their installations

**Current state:** When no keep alive is sent to `dbus-mqtt` no data is sent to the cloud broker. When there is something sending a keep-alive to the broker every minute, all dbus paths are sent to the cloud broker

**Proposal:** 
Add support for a middle way: sent a part of the set of dbus paths to the cloud broker by indicating that in the keep-alive message.

Proposal would be to add support for a payload containing the dbus paths that the consumer needs, e.g. to get only system data and inverter voltages:

```
Topic: R/<siteid>/system/0/Serial
Payload: ["system/#","inverter/+/voltage"]
```

(the `<action>/<siteid>` part is left out the make the payloads smaller)

## Possible cases and proposed actions by `dbus-mqtt`:

**A client sends an empty payload to `R/<siteid>/system/0/Serial`**: 
Fallback to the old keep-alive behaviour and send all data to the broker, this ensures backwards compatibility. It also allows for an efficient way to get all data, without specifying every path

**A client issues a read/write requests on a specific topic**: 
Execute the read write requests just like its done now, but don't trigger a keep alive rest of all paths. That last part is a change compared to the current implementation. But I think its justified

**Multiple clients ask for a specific set of paths in their keep alive payload**
E.g. client A requests `system/#` and client B requests `inverter/#`. I propose to send both sets of paths to the broker in that case and as soon as e.g. client A stops sending the keep alive payload, only sent the set of paths of client B to the broker

**Is `R/<siteid>/system/0/Serial` the right path to implement this keep-alive payload?** 
Thats up for discussion, `R/<siteid>/keepalive` would be more intuitive I'd say, however, `R/<siteid>/system/0/Serial` is already documented wrt keep alives. Implementation wise it does not matter that much

**Isn't this covered by MQTT V5?**
As far as I'm aware there is no mechanism in MQTT v5 that covers sending partial sets from the device to the broker. The closed thing I've found is a feature called shared subscriptions, but that covers the part from the broker to the clients: 
https://www.hivemq.com/blog/mqtt5-essentials-part7-shared-subscriptions/

**Comment by izak** [comment]
Transferred to https://github.com/victronenergy/venus/issues/819

**Comment by mpvader** [comment]
The version of dbus-mqtt that implements this is included in v2.80-something. Which is now in public beta as v2.80~11.

@izak can this be closed now?

**Comment by mpvader** [comment]
Before closing this, double check that the readme in the repo has been updated about all this; including that the new method is backwards compatibly: requesting just a few paths on an old device will result in gettign all paths: OK.

**Comment by aaronsb** [comment]
Will the readme include some specific examples of what the selective keepalive payload will look like?

**Comment by izak** [comment]
Yes, the README was  updated. Look under the heading "Keepalive". There is even a specific notice about the important changes so nobody can say they didn't know.

**Comment by adejongh** [comment]
Thanks all;  this will be a great improvement.  Quick question - how can I figure out which method I can use against a specific Venus installation?  If I use the new "R/<portal ID>/keepalive" method against an older Venus version I assume I'll get no notifications, so we need to be ablet to figure out which method to use against which Venus devices - we have a few that we need to monitor like this.

**Comment by izak** [comment]
> how can I figure out which method I can use

The new method always sends `N/<portal-id>/keepalive` (as well as the existing `N/<portal-id>/system/0/Serial`), so if you want to support both methods, simply subscribe to both when you connect.

**Comment by izak** [comment]
It appears I have to make the README better.

@adejongh to answer your question better: Older versions of Venus will respond with everything if you request `R/portal-id/keepalive`. It errors on the request, but still activates the send-everything-keepalive. So you don't have to do anything special. Just use the new method and it will work for both.
