### ISSUE TITLE
VE.Bus: Add support for MultiPlus-II 2x120V 

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#820]
### Intro & todo list
This new product is the first time we have a single Multi that *can* be multi-phase, more precisely split-phase.

Its common use case is in US RVs and Boats, allowing the end-user to connect to a split-phase shore connection when available, and if not then then at least connect to a single phase shore connection.

What the product does in case connected to single phase shore connection is short L1 and L2 out together, so that the user still has 120V on both of their circuits. Similarly, when in inverter mode, it also shorts L1 and L2 together.

Obviously, when L1 and L2 are shorted together, there is no 240V available - only 120V. But thats no issue since all requests to customers/sales/ambassadors so far on that topic yielded that that 240V loads are not existing or at least extremely rare.

One, maybe two, things need fixing:
1. show info on L2, at the moment L2 is completely invisible, also in VictronConnect.
2. use the status on the relays (are L1 and L2 shorted together or not) in the visualisation. Optional.

Changes need to be made to:
- [x] Multi firmware (report voltage, current, power for L2). Status is finished, available in a beta version.
- [x] vebus-interface (pass those parameters along). Status is finished also.
- [x] GUI
- [x] VRM
- [x] Document the path here: https://github.com/victronenergy/venus/wiki/dbus

### D-Bus paths:

`Ac/NumberOfPhases`: will normally be 2. Unless the 2x120V product is configured in a three phase system, in which case its L2 output isn't used at all, and then this D-Bus path will be as it always is: showing the number of phases in the system.

`Ac/State/SplitPhaseL2Passthru` (new): 
- yes: L2 is being passed through from AC-in to AC-out.
- no: L1 and L2 are shorted together.
- invalid: The unit is configured in such way that its L2 output is not used.

### Inverter mode
![image](https://user-images.githubusercontent.com/10847324/117954764-a04db900-b317-11eb-8cf5-823c10509c42.png)
**D-Bus output**
![image](https://user-images.githubusercontent.com/10847324/117954865-bce9f100-b317-11eb-9d03-1c9e9f899667.png)
**GUI**
![image](https://user-images.githubusercontent.com/10847324/118937855-4324b980-b94e-11eb-83a6-3a37af02e931.png)

### 120VAC single phase input mode
![image](https://user-images.githubusercontent.com/10847324/117955026-e60a8180-b317-11eb-9551-2ba49b3f628f.png)
**D-Bus output**
![image](https://user-images.githubusercontent.com/10847324/117955069-f15dad00-b317-11eb-9095-ba30ed5a7f10.png)
**GUI**
![image](https://user-images.githubusercontent.com/10847324/118937684-107ac100-b94e-11eb-81f7-fc2b416fbd58.png)

### Split phase input mode
![image](https://user-images.githubusercontent.com/10847324/117955541-7052e580-b318-11eb-929a-a6f9cfd31893.png)
**D-Bus output**
![image](https://user-images.githubusercontent.com/10847324/117955570-79dc4d80-b318-11eb-8e82-89c01272b075.png)
**GUI**
![image](https://user-images.githubusercontent.com/10847324/118937363-bf6acd00-b94d-11eb-8333-5edaa9ef0b43.png)

### Test setup
https://vrm.victronenergy.com/installation/102738/dashboard

**Comment by vejpasop** [comment]
Included in mk2-dbus V3.21

**Comment by jepefe** [comment]
I implemented the changes as discussed. gui branch: feat_overview_splitphase

L1 & L2 connected:
![Screenshot_20210528_160102](https://user-images.githubusercontent.com/6424631/120002612-4d415a80-bfd5-11eb-9b41-caef800d0cf3.png)

L1 connected | L2 disconnected:
![Screenshot_20210528_160823](https://user-images.githubusercontent.com/6424631/120002940-92658c80-bfd5-11eb-88ba-d00efbdeb572.png)

**Comment by mpvader** [comment]
@vejpasop & @jepefe : you're all done with this, right?

Which then leaves some work to be done by @izak, and thereafter perhaps also the overview on the VRM Portal.

Jos, please list which extra paths (if any?) need to be supported by Izak for that.

**Comment by jepefe** [comment]
@mpvader Yes, and I see that gui changes are already included in gui v4.9.2.

**Comment by vejpasop** [comment]
@mpvader Yes,

@izak. The only new dbus path for this is  `Ac/State/SplitPhaseL2Passthru` (See issue description)

**Comment by izak** [comment]
Closing now that the dbus path is documented.
