### ISSUE TITLE
Issue upgrading 2.66 to 2.70/2.70-large

### ISSUE THREAD

**Issue by PatrickB100** [victronenergy/venus#822]
Hi Develop team,

I have an issue on the upgrade of the 2.66 to 2.70 version. I have formatted an usb-stick as FAT32 and copied both .swu and .wic files to the stick. When i plug in the usb into the RPI 3B a notification shows up that updates are present on the usb stick. When i try to update i get a notification that there are no updates available on the stick. 

Can anybody assist on how to fix this issue?

Best regards,

Patrick

**Comment by mpvader** [comment]
Hi Patrick, to update a rasberrypi from pre v2.70, you need to burn a new image.

Its not possible to update it while keeping everything in tact.

note that burning a new image also means losing all data and settings. For which there are work arounds, see the modifications space on Community.
