### ISSUE TITLE
GUI: changing access level to user breaks the settings menu

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#823]
Only the five items visible in the photo remain, and as a result its no longer possible to set the system back to user&installer

most likely a regression since v2.70~12

![image](https://user-images.githubusercontent.com/5200296/119049212-8cadec80-b9c0-11eb-8283-e5b9da6ebf7a.jpg)

**Comment by mpvader** [comment]
Settings menu is also gone btw:

![Uploading image.jpg…]()

**Comment by mpvader** [comment]
![image](https://user-images.githubusercontent.com/5200296/119050792-a05a5280-b9c2-11eb-8c75-a12433d83038.jpg)

**Comment by RobDuthie** [comment]
Hi all also the analog setting page is missing?
