### ISSUE TITLE
Serial connection to Shipmodul miniplex

### ISSUE THREAD

**Issue by PatrickB100** [victronenergy/venus#824]
Hi Devs,

I have connected a Shipmodul miniplex to the raspberry pi with VenusOS 2.70 large image installed and SignalK enabled. I have added the serial nmea 0183 connection in the data sources but unfortunately no data is coming in. Is this a known issue or am i doing something wrong? 

In the dashboard the connection is established.

Best regards,
Patrick

**Comment by mpvader** [comment]
Hi @PatrickB100 , sorry for the long no response; but frankly this is the wrong place to ask for support. We use this issue tracker to track development. Not for support.

For questions like this (asking how to make some not officially supported thing work) I recommend to use the Communications space on https://community.victronenergy.com/
