### ISSUE TITLE
Phantom Power Drain on new  Multiplus or Venus GX FW Baselines

### ISSUE THREAD

**Issue by Yoda101** [victronenergy/venus#827]
Portal ID: f045da7d75b0
I believe the change to the new Venus GX V2.66 / MultiPlus-II V4.82 software introduced a phantom SOC drain that was not present on the previous versions.

**Loss of 25% on 15-Jun is not expected here and is considered a phantom drain and is 25% in 14 hours:** 
![image](https://user-images.githubusercontent.com/22992276/122171363-ea2e3f80-ce7f-11eb-8a28-568ef7c9cdf2.png)
In comparison:  Phantom drain on 02-May is 5% (3% + 2%) in 9 hours which is acceptable
![image](https://user-images.githubusercontent.com/22992276/122171446-0500b400-ce80-11eb-96e3-2af902ddcc88.png)

**Comparison of "System - Battery Voltage And Current" graphs for the 2 dates show significant current spikes not expected:**
15-Jun:
 ![image](https://user-images.githubusercontent.com/22992276/122171783-62950080-ce80-11eb-870f-88610b7b7645.png)
02-Mar:
![image](https://user-images.githubusercontent.com/22992276/122171821-6cb6ff00-ce80-11eb-89be-404c1a5ff739.png)

**Detailed additional information attached.**

Thanks in advance!
[Victron Phantom Power Analysis 20210616.pdf](https://github.com/victronenergy/venus/files/6660839/Victron.Phantom.Power.Analysis.20210616.pdf)

**Comment by jhofstee** [comment]
Closing this as it is almost a year old, and I would guess fixed in the meantime. I this is still an issue feel free to reopen it.
