### ISSUE TITLE
Anyone having Issues with the latest 2.66 version on Raspberry Pi 3B+

### ISSUE THREAD

**Issue by martinplaska** [victronenergy/venus#828]
I have had the 2.66 version running for almost 2 months now and one day it just stopped working all of a sudden.

Rasbian works fine on the same Pi.

Will try installing 2.65 and see if it boots.

![image](https://user-images.githubusercontent.com/80949399/122205178-3ee1b280-cea0-11eb-8192-362ff1301a27.png)

Martin

**Comment by martinplaska** [comment]
Solved

**Comment by martinplaska** [comment]
Solved, Wifi stopped working on Pi

**Comment by mpvader** [comment]
Hi Martin, thank you. Next time, please don’t make an issue but make a post on the modifications section on https://community.victronenergy.com/
