### ISSUE TITLE
Add better support for temperature sensors

### ISSUE THREAD

**Issue by jhofstee** [victronenergy/venus#829]
From the old todo page, so adding it here, so it can be deleted:

"Typical locations are Inside Cabin, Outside, Plumbing Bay, Engine Compartment, Fridge, Freezer. At a glance in the UI I would love to see min/max for the past 24 hours, and all time min-max since reset. Alarms and graphs would be awesome too."

**Comment by mpvader** [comment]
all either done or being done, I'll close this one.
