### ISSUE TITLE
Feature request: Add measurement of apparent power to energy meters

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#830]
Possible starting point: https://github.com/victronenergy/dbus-cgwacs/tree/apparentpower

ET340 meter doesn't seem to provide good values, so this would only enhance EM24 and ET112.

Not high priority.

**Comment by jhofstee** [comment]
Why would we want add this?

**Comment by izak** [comment]
Customer request. In a factory environment it is useful to have the information available from VRM.

**Comment by mpvader** [comment]
The Multi RS (and Inverter RS) will also report both watts as well as apparent power.

**Comment by izak** [comment]
I'm going to kill this for the following reasons:

1. Few people are asking for it
2. The ET340 seems to be broken, or the registers are swapped.
3. You can work out the apparent power yourself by multiplying V and I (it yields the same values, I tested).
