### ISSUE TITLE
can-bus-bms: Add detection of BMZ_ESS battery

### ISSUE THREAD

**Issue by dirkjanfaber** [victronenergy/venus#831]
For the setup on https://vrm.victronenergy.com/installation/47444/overview

TODO
- [x] Add detection to can-bus-bms
- [x] Add DVCC=on, SVS=off, STS=off to systemcalc

**Comment by mpvader** [comment]
Also, there is a new ongoing email exchange with BMZ, where they asked me to have DVCC auto enabled. So lets do that too
