### ISSUE TITLE
Have problems installing the touch screen...

### ISSUE THREAD

**Issue by KamiSchami** [victronenergy/venus#833]
Hi, I'm not getting the touch screen installed.  I'm following the instructions, but only bring error messages.  Please help me.

**Comment by kwindrem** [comment]
What error messages are you getting?

What Raspberry PI model are you installing on?

Did you install SetupHelper also? It's needed for the RpiDisplay script to run.

**Comment by KamiSchami** [comment]
I hava a 3B. What Setuphelper? I have manual here...

First i habe to install opkd Update, but then comes this error

![20210623_213401](https://user-images.githubusercontent.com/67215246/123206275-b2487d00-d4bb-11eb-9441-9594e30897d4.jpg)

![20210623_215149](https://user-images.githubusercontent.com/67215246/123206292-baa0b800-d4bb-11eb-92bc-ac8830342602.jpg)

**Comment by KamiSchami** [comment]
![20210623_203617](https://user-images.githubusercontent.com/67215246/123206784-94c7e300-d4bc-11eb-9b0a-d7e79b3741e4.jpg)

All is working, but mit the touch

**Comment by kwindrem** [comment]
Disregard my question about SetupHelper. I had assumed you were using my RpiDisplay package.

It isn't clear where you are getting the instructions to follow. I seem to recall some issues with opkg recently but don't recall the details.

I can offer an alternate way to make the Official Raspberry PI 7" touchscreen and potentially others work that doesn't require installing all the things I've seen in other posts on this community:

https://github.com/kwindrem/RpiDisplaySetup

This package does use SetupHelper and in fact, installing that package simplifies installing RpiDisplaySetup.

**Comment by mpvader** [comment]
Hi all, sorry, but could you please continue this here:  https://community.victronenergy.com/spaces/31/index.html.

we use this issue tracker for development only.
