### ISSUE TITLE
Wifi zombie state issue

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#834]
Reported for the Cerbo only (sofar). Report by the customer:

It seems that sometime after 2.70-11 a WiFi issue has been introduced. This continues with 2.72-2.

The symptoms:

- Everything is working well

- Cerbo GX will loose connection to VRM

- WiFi will indicate it is connected on Cerbo GX screen

- Cerbo GX will not accept SSH or pings, network seems down

- On Cerbo GX display in VRM settings it is indicating a URL lookup issue.

- Check logs in DNS server and Cerbo GX has not made a DNS request for hours.

- Using Bluetooth VictronConnect connect to the Cerbo GX.

- Go in and disconnect the WiFi network under Settings/Networks

- Then reconnect WiFi network

- All works again for several hours until it repeats itself

It appears that once in this WiFi zombie state the only way to recover is to disconnect/reconnect or reboot the device. This doesn't occur over ethernet connection.

—-

From jw1971 here: https://community.victronenergy.com/questions/93185/venus-os-v2722-available-for-testing.html

**Comment by jhofstee** [comment]
Closing this, since we patched connman to always try to reconnect. We can make a new issue if it still present.
