### ISSUE TITLE
Install VenusOS 2.72 on Raspberry Pi 4 (Rev 1.1)

### ISSUE THREAD

**Issue by AirTobe91** [victronenergy/venus#837]
Hello,

I try installing the venus-image-raspberrypi2-20210705130613-v2.72.rootfs.wic.gz on my RPi 4.
I'm using Balena Etcher for writing the wic-Image. After flashing and inserting the SD Card, the Pi doesn't boot.
Does anybody have the same problem? Or does somebody has some recommendation how to solve this problem.

Thanks!

**Comment by mpvader** [comment]
Hi, see the the instructions, many (most?) raspberrypi4s are not supported.

Instructions here: https://github.com/victronenergy/venus/wiki/raspberrypi-install-venus-image
