### ISSUE TITLE
replace canutils by can-utils

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus#84]
The can-utils package has more tools and is able to record and playback can-dumps with timestamps, unlike the tools in canutils. It seems to be the more common way to use SocketCAN.

**Comment by jhofstee** [comment]
the beaglebone production test script uses these, so this cannot be done blindly. Its the only user afaik, so shouldn't be to difficult, but does need testing.

**Comment by mpvader** [comment]
@jhofstee: there is still some time left for the beaglebone. So for me its fine to make the change now.

**Comment by jhofstee** [comment]
done, https://github.com/victronenergy/meta-victronenergy/commit/d659fda0865fca3245def957d45d687ed9f2959f
