### ISSUE TITLE
Lost Battery History Widget in VRM after loading 2.72 on Pi

### ISSUE THREAD

**Issue by jwarchol** [victronenergy/venus#844]
I recently made a new SD card with the 2.72 image and fired it up. Everything proceeded as expected, except several VRM widgets no longer show up, notably the Battery History widget (number of cycles, deepest discharge, etc). If I go in the remote console the values are all still in my SmartShunt, but they don't seem available in VRM. Has anyone else seen an issue like this before? Suggestions for what I'm doing wrong are gratefully accepted.

**Comment by mpvader** [comment]
Hi @jwarchol its possibly a bug in VRM. I’ll find out and let you know.

**Comment by jwarchol** [comment]
Here are some screenshots to show  what's happening there: 
![image](https://user-images.githubusercontent.com/2336/129905966-7fb5103b-1677-4fc0-9a0e-b533d5d09819.png)

This is VRM installation 111929

**Comment by mpvader** [comment]
Hi @jwarchol , the Battery history widget is only available if "H7 - Minimum battery voltage" is available in the data. And its missing on your system; please restart your GX device, that would solve it.

**Comment by jwarchol** [comment]
Restarting worked, thank you @mpvader 🎉 

Hopefully this Issue showing up in search helps folks with the same problem in the future.

**Comment by mpvader** [comment]
yes indeed. For future things, please though use Community: https://community.victronenergy.com. And then either the normal area or the Modifications area.

Making issues here triggers emails to all or almost all our developers, and so forth.

thanks!

**Comment by jwarchol** [comment]
I did post there but it was quickly buried with the volume of new posts. Since the only change on my side was the release of the pi image, I opted to raise the issue. Apologies if too many people were notified. I know there are challenges managing notifications on a public repository like this. Appreciate the help!
