### ISSUE TITLE
DVCC Limit managed battery voltage Modbus

### ISSUE THREAD

**Issue by shaneyake** [victronenergy/venus#849]
Hi,

It looks like the scale for Modbus is incorrect.
Address 2710 : Limit managed battery voltage
The current scale is 1 which is a resolution of 1V but in the UI you can change it at a resolution 0.1V.

Any chance the Modbus scale can be changed to 10 or 100 so we can have the same or more resolution.

Also it seems to be read only, can this be changed like Address 2705 : DVCC system max charge current

Thank you,

Shane

**Comment by mpvader** [comment]
Noted, will be looked into. Thank you shaneyake.
