### ISSUE TITLE
gpio cannot be switched !!

### ISSUE THREAD

**Issue by Micha854** [victronenergy/venus#856]
Hello guys, I have the venus image on my raspi and if the internet connection is lost I want to switch a relay via gpio to restart the router.

I can control the gpio21 (pin40) with "dbus -y com.victronenergy.system/Relay/0/State SetValue% 0 or 1" but it is not switched on the raspi. What am I doing wrong?

**Comment by mpvader** [comment]
Hi, can I ask you to ask that here: https://community.victronenergy.com/spaces/31/mods.html

?

This issue tracker is to manage the development, not support.
