### ISSUE TITLE
Increase range of resistances for tank sensors

### ISSUE THREAD

**Issue by AlexMuir** [victronenergy/venus#857]
Currently the maximum resistance that can be saved for tank sensors is 264Ω.  The Cerbo has no problem displaying the actual resistance value in the setup menu (up to 330Ω) so the hardware has the range.  

The resistance range for standard Vetus senders is  0Ω (full) to 300Ω (empty).  If the resistance range can be increased, then Vetus sensors will be fully supported out of the box.  

Reference: https://www.vetus.com/en/waste-water-sensor.html

**Comment by mpvader** [comment]
Hi @AlexMuir , thanks for this. We can increase it to 300Ohm, and will do that. all the best, Matthijs

**Comment by AlexMuir** [comment]
Wonderful, thanks!

**Comment by mpvader** [comment]
Hi, available per v2.80~24, in candidate since today. thanks again.
