### ISSUE TITLE
Inverter RS and Multi RS: Sync SOC and Extra Charge Current

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#859]
For the Multi this was done a long time ago. The same is needed for Inverter RS:

- [x] Add /Link/ExtraBatteryCurrent path to dbus-vecan (mbo)
- [x] Add /Link/Soc path to dbus-vecan (mbo)
- [x] If there is a BMV or another managed battery in the system with a more accurate SOC, copy this to /Soc on the inverter
- [x] If there are other chargers in the system, write their combined charge current to /ExtraBatteryCurrent on the inverter

A decision was made to only support connection of Inverter RS by VE.Can. This simplifies this issue somewhat.

On VE.Can, Inverter RS already knows about the charge current of other VE.Can connected devices (via the CAN-bus connection), we need only inform it of what the VE.Direct chargers and the Multi (if there is one) is doing. So /ExtraBatteryCurrent is only the sum of the currents of the non-VE.Can chargers (VE.Direct, Multi).

Shared Current Sense (SCS) already covers Inverter RS. If there is a suitable battery monitor in the system, this is already sent to the CAN-bus where Inverter RS can use it for tail current and/or SOC estimation.

**Comment by rvanzundert** [comment]
The battery state-of-charge can be communicated to the Inverter RS and Multi RS using VE_REG_SOC (0x0FFF), un16 = SOC [0.01%], 0xFFFF = not available.

On ve.can the the RS units listen for VE_REG_SOC broadcasts from:
- lowest priority: a battery (e.g. Lynx Smart BMS)
- highest priority: a GX device
Alternatively the VE_REG_SOC can be written directly to the unit, in this case it will not listen for broadcasts anymore. This can be used on ve.direct or a ve.smart network if needed.

Receiving a state-of-charge in this way overrules the internal state-of-charge mechanism.
The timeout is 1 minute, so after 1 minute absence the internal mechanism takes over.

**Comment by martinbosma** [comment]
dbus-vecan will support two new paths on `com.victronenergy.vecan.canx`:
- `/Link/Soc` - periodic broadcast of `VE_REG_SOC` with 60s time-out
- `/Link/ExtraBatteryCurrent` - periodic broadcast of `VE_REG_LINK_EXTRA_BATTERY_CURRENT` with 60s time-out

**Comment by mpvader** [comment]
@izak pls confirm (test!) whether this all works now, both for Inverter RS and Multi RS, or if it still needs work.

**Comment by izak** [comment]
No this definitely still needs work!

**Comment by mpvader** [comment]
prioritise this, should be simple - or not?
