### ISSUE TITLE
ccgx stuck (Almere Hub-1)

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#86]
On the first attempt to reproduce issue #85 on one of our Ccgx-es, it got stuck.

a different problem than #85, the Ccgx is stuck:
- The GUI is still visible: showing device list (strange, I'd expect it to show the backup rootfs menu)
- time is running
- values on the device list are also being updated. But looks like those updates are slower than usual.
- it doesn't respond to any button presses.
- on the device list shown, the two mppts via VE.can are missing. But they were present right before something went wrong: see VRM. They have been their right up to the last set of data received, at 22:10

I'm not sure if the Ccgx got in this state before or after the reboot.

**Comment by jhofstee** [comment]
closing this, since there are many load specific issues / fixes now and this smells like an overload situation.
