### ISSUE TITLE
SPI on BBB?

### ISSUE THREAD

**Issue by JuWorkshop** [victronenergy/venus#863]
I don't understand how to install/set spi1 port avaible on bbb venus.
Test install/compile DTC, convert dts to  dtbo, ok. But after??
Could someone show me the process?

**Comment by mpvader** [comment]
Hi, I'm sorry but this issue tracker is for development; not for support. You could try here: https://community.victronenergy.com/spaces/31/mods.html, though I'm afraid that the amount of people around that can actually help you with that is real low.
