### ISSUE TITLE
gui: Reword "Low Power" state to "AES mode"

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#864]
When AES mode is active the GUI confusingly shows "Low Power".  This should have been "Low Power Mode". 
Since that line is too long to fit in the Multi status icon I would recommend to rename it to "AES mode"

This corresponds to the setting name in VictronConnect and VEConfigure.

Needs changing here: https://github.com/victronenergy/gui/blob/master/qml/SystemState.qml#L14

**Comment by jhofstee** [comment]
mmm, doesn't search mode not report this state as well?

**Comment by mpvader** [comment]
we call both these power save options AES in VEConfigure:


![image](https://user-images.githubusercontent.com/5200296/187216154-a8c71c0e-40dc-439a-a23d-1fe3d9911f6c.png)
