### ISSUE TITLE
mqtt memory usage is high (almere hub1)

### ISSUE THREAD

**Issue by jhofstee** [victronenergy/venus#87]
```
 1241  1207 root     S    22920   9%   7% {dbus_mqtt.py} /usr/bin/python -u /opt/color-control/dbus-mqtt/dbus_mqtt.py --init-broker
 1213  1190 mosquitt S    97636  39%   0% /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
```

Combined it takes roughly 120MB (which is half the RAM)

**Comment by jhofstee** [comment]
cpu can be high as well, 3638,  1752  1553 root     R    22760   9%  16% {dbus_mqtt.py} /usr/bin/python -u /opt/color-control/dbus-mqtt/dbus_mqtt.py --init-broker

**Comment by mpvader** [comment]
continued here: https://github.com/victronenergy/venus/issues/189
