### ISSUE TITLE
RPi 4 (new version), No USB and Touch not working

### ISSUE THREAD

**Issue by toglader** [victronenergy/venus#870]
There seems to be some issues with the latest version of Venus OS in RPi 4. At first, it doesn't boot but after upgrading start.elf and fixup.dat, system boots. However, None of the USB-ports works and in Official 7" screen touch-functionality doesn't work. Also, dimming functionality is missing. By switching card to an older RPi 4 problems remains but older RPi4 works fine with original elf and dat file.

**Comment by mpvader** [comment]
Hi, sorry, but this sounds like the familiar issues: the newer rpi4 doesnt properly work.

also not 100% by updating elf and dat file manually;

and yes it might work even less in a newer build, we’re not testing at all for it and know that it needs some real work to get OK: most likely newer kernel & newer uboot.

For details, see the link to some post on community, you’ll find that link on or venus image install raspberrypi page.

I’ll close this issue; what the (newer) rpi4 boards need is someone out there with time and knowledge on his hands to take a look.
