### ISSUE TITLE
Feature request: Change dashboard background color

### ISSUE THREAD

**Issue by fpugliano** [victronenergy/venus#871]
When sailing at night, the white background of the dashboard disturbs my night vision.  Would it be possible to add an option to cange the background color from white to black?

![VenusGXBackgroundColor](https://user-images.githubusercontent.com/18278071/139534325-70f452e7-7f2e-4b16-a834-7aa2ed4116c2.png)

**Comment by mpvader** [comment]
Hi, yes! We’re working on a complete new UI, having a dark mode will be part of that.

**Comment by fpugliano** [comment]
Awesome! Is this going to be in the next release?  When it is scheduled to roll out?

**Comment by mpvader** [comment]
Hi, that will take a while, its a complete redesign of the UI. Somewhere next year. In case you’re on the northern hemisphere, then - with a bit of luck!- right when the common season starts.
