### ISSUE TITLE
Ruuvis various

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#881]
Three things:

1. We need to add a /Status path. Its used by VRM to validate that there actually is temperature sensor input. It can't rely on the temperature for that, since that might be missing due to a sensor error. See [here](https://github.com/victronenergy/venus/wiki/dbus#temperatures) for what can be put on that path. Depending on how its implemented in the dbus-ble-sensors, one solution could be to always set 0 (OK). And when not OK then remove the service from the D-Bus - as that is how I expect its implemented now?  Some other variant, which includes using the 1 (Disconnected) state is also fine - then enabled sensors can remain visible on the Device List in the GUI as well, even though the sensor is gone. Which does have its advantages to a user.

2. Ruuvi Tag show "not connected" in irregular intervals, details in the link. Perhaps first await his vrm url and report of it happening again: https://community.victronenergy.com/questions/108453/venus-os-v28029-available-for-testing.html?childToView=109754#comment-109754

3. (seen on v2.80~29 only!) There is an issue visible in the gui when removing a missing a sensor. It has been reported by Stefanie, second item in this screenshot:

![image](https://user-images.githubusercontent.com/5200296/146265994-5868aafb-1f5f-4ff7-b26b-c5a574439f6c.png)

from: https://community.victronenergy.com/questions/108453/venus-os-v28029-available-for-testing.html.

Then I tried to reproduce, I have one sensor that is sometimes connected and sometimes not - range issue most likely. And it happened to now be not connected. So first I clicked the button in the gui to get it removed. Then I went to Settings -> I/O -> Bluetooth, there disabled that sensor, and then things got a little messy like in this screenshot:

![image](https://user-images.githubusercontent.com/5200296/146267184-20b52d02-9ed0-44d0-b6ef-2283e54f56c5.png)

Going out and back in to the menu doesn't matter, list remains the same. Note that that is on v2.80~29, both on my side, and for 99% also on Stefanies side.

This is what the D-Bus shows:

![image](https://user-images.githubusercontent.com/5200296/146267424-04d9ec06-bab7-41e1-be27-eac9837db89f.png)

**Comment by mpvader** [comment]
added "Ruuvi Tag show "not connected" in irregular intervals"

**Comment by mansr** [comment]
The blank items in the settings menu for vanished sensors are caused by `VeQItemTableModel` or something related. The same thing happens if a USB tank sensor is unplugged.

**Comment by mansr** [comment]
Sensors are removed from dbus (and thus show as "not connected") if they have not been seen for 60 seconds. If the signal is weak, it's possible this timeout is too low. Increasing it is trivial, though.
