### ISSUE TITLE
Ruuvi: add alarm for battery voltage

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#889]
- [x] implement it in dbus-ble-sensors (per v2.82)
- [x] add it to the gui, (not as audible alarm) - done / waiting for review by Jesus per 2023-3-24
- [x] add it to vrm

See here for discussion on levels:
https://github.com/ruuvi/com.ruuvi.station/issues/335

**Comment by mpvader** [comment]
if temp is less than -20C, low battery threshold = 2V
else if temp is less than 0C, low battery threshold = 2,3V
else low battery threshold = 2,5V

**Comment by jepefe** [comment]
I will include this alarm in venus platform service.

**Comment by mpvader** [comment]
@jepefe , pls fix it and add it to the old gui as well; not make it part of venus-platform. You're here in the office with Dirk-Jan this week, should be easy to test.

**Comment by jepefe** [comment]
dbus-ble-sensors has been changed to use` /Alarms/LowBattery` instead of `/Status` and alarm was added to the gui.

Both are added to the todo.

**Comment by mpvader** [comment]
so per this change, we'll actually have that alarm show up in the GUI as a notification. Instead of only show somewhere hidden in a menu. Right, @jepefe  ?

Can you post a screenshot of how the alarm looks in the gui?

**Comment by jepefe** [comment]
@mpvader Now it is only shown in the notifications center but not in the sensor page. If necessary I can make it show also in the sensor page.

<img width="496" alt="Screenshot 2024-02-01 at 15 45 49" src="https://github.com/victronenergy/venus/assets/6424631/fb6952ba-668d-4831-9d46-cd10e60c3bd8">

**Comment by mpvader** [comment]
hey @izak can you take care of the vrmlogger change? the updated dbus-ble-sensors repo you'll need to test against is ready, on the todo. (but not yet in a build)
