### ISSUE TITLE
add VE.Bus BMS status

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#89]
The BMS status will be reported by the ESS assistant through ramVars.

Reported variables by the assistant:

- A/D value of High cell signal 
- flags as used in the assistants:
   - LowCell
   - HighCell
   - Error
   - VE.Bus BMS Expected 

And the info wanted is:
- is there a VE.Bus BMS expected yes/no.   (for now this is when the VE.Bus Assistant is installed, early next year when this is integrated in the firmware, this will probably just be a flag or something)
- allow-to-discharge [yes/no]
- allow-to-charge [something analog]

DBus path:

- Bms/AllowToCharge                  (!HighCell && !BMSerror)
- Bms/AllowToChargeRate           (A/D value of High Cell signal)
- Bms/AllowToDischarge              (!LowCell && !BMSError)
- Bms/BmsExpected
- Bms/Error                                 

Projects:

- [x] mk2-dbus (but not via the VE.Can <-> VE.Bus interface cable)
- [x] gui showing
- [ ] gui alarms
- [x] vrmlogger / vrmporal
- [x] modbustcp

**Comment by mpvader** [comment]
What logic is applied to the AD value by the VE.Bus devices?

**Comment by mpvader** [comment]
@vejpasop: can you answer my question on that logic? FYI I updated your comment, added a small todo list in there.

**Comment by vejpasop** [comment]
When bit 7 gets high the "High cell" flag will be set.

**Comment by vejpasop** [comment]
Done implementing the  above on branch: 

https://git.victronenergy.com/ve-products/vebus_interface/commits/WIP_VEBUS_BMS_status

@edevries-victron: I copied "mk2-dbus-bms" on your test setup, so you can play with it.

**Comment by jhofstee** [comment]
gui showing is included in v2.01. Do we need additional alarms for this?

**Comment by mpvader** [comment]
no we do not. At least not without any further thought or testing: the overvoltage signal is part of the normal balancing procedure.

**Comment by jhofstee** [comment]
ok closing this then. If we need more alarms it can be reopened again.
