### ISSUE TITLE
SDK does not install gcc

### ISSUE THREAD

**Issue by MrHyrex** [victronenergy/venus#892]
Hello

I'm trying to set up an ubuntu vm for creating C/Cpp drivers for Venus.
I'm trying to follow the SDK article in the wiki, and have downloaded and installed the SDK. However, when I try to compile by using commands cc, CC or gcc, it seems that GCC is not installed. 

From the SDK install output it seems that Gcc is missing even before the extract, shouldn't it have been included in the SDK as the wiki says?

```
$ sudo ./venus-zeus-x86_64-arm-cortexa8hf-neon-toolchain-qte-v2.73.sh
./venus-zeus-x86_64-arm-cortexa8hf-neon-toolchain-qte-v2.73.sh: 24: gcc: not found
Victron Energy SDK installer version v2.7
==========================================                                                                                                                                                               
Enter target directory for SDK (default: /opt/venus/zeus-arm-cortexa8hf-neon):
The directory "/opt/venus/zeus-arm-cortexa8hf-neon" already contains a SDK for this architecture.
If you continue, existing files will be overwritten! Proceed [y/N]? y                                                                                                                                    
Extracting SDK.......................................................................done 
Setting it up...done
Updating qt4 mkspecs
/opt/venus/zeus-arm-cortexa8hf-neon/post-relocate-setup.sh: 4: export: -mfpu: bad variable name
SDK has been successfully set up and is ready to be used.
Each time you wish to use the SDK in a new shell session, you need to source the environment setup script e.g. $ . /opt/venus/zeus- arm-cortexa8hf-neon/environment-setup-cortexa8hf-neon-ve-linux-gnueabi 
```

**Comment by nmbath** [comment]
You might get better support by asking this on the community from (community.victronenergy.com) and the modifications section.

A could of pointers.. What device are you installing this on, as it seems that gcc is not installed. A cross compiler version is installed as part of the SDK and the sourcing of this script ". /opt/venus/zeus-arm-cortexa8hf-neon/environment-setup-cortexa8hf-neon-ve-linux-gnueabi" will adjust paths to ensure that the cross-compiler version of gcc is early in the path.
