### ISSUE TITLE
MQTT solarchager problem after update to v2.80

### ISSUE THREAD

**Issue by sunnyday333** [victronenergy/venus#900]
Dear team,

There is a bug with MQTT topic solarcharger/Pv/I after Venus OS upgrade to v.2.80 shows nothing for my MPPT regulators.

[![Screenshot-2022-02-02-at-09-36-45.png](https://i.postimg.cc/qM9QwSNz/Screenshot-2022-02-02-at-09-36-45.png)](https://postimg.cc/8jmhPyBS)
Thank you.

**Comment by mpvader** [comment]
Hi @sunnyday333 , this was indeed changed - see the changelog.

Sorry for this breaking change for your monitoring, but this is as it is I'm afraid.

Closing this issue.
