### ISSUE TITLE
NMEA2000 CerboGX Tank140 instances configurable

### ISSUE THREAD

**Issue by DevoDave** [victronenergy/venus#909]
Raymarine cannot cope with tanks with NMEA2000 device instances greater than 5. My  setup is a CerboGX with a Tank140 and I have two tank level senders connected to the Tank140. Looking at the NMEA2000 data, the device instance is set to 10 and 11. To the best of my knowledge I cannot modify these settings via the CerboGX gui or my Raymarine setup. (I do have an Actisense NGT but again cannot modify this particular PGN)

**Comment by mpvader** [comment]
Tbd during upcoming n2k/tank meeting. Pls put on the agenda @martinbosma, thanks

**Comment by martinbosma** [comment]
@DevoDave We found and fixed an issue related to changing fluid level (data) instances. To my knowledge Raymarine is using the data instance in the fluid level PGN, not the device instance. 

This fix is scheduled to be included in the next VenusOS version (v3.00). The fix enables the fluid level instance to be changed using Actisense NMEA Reader. However, it look like there is also a bug in the Actisense tool. It seems to combine the fluid level instance and fluid type (both 4-bit fields) as a single 8-bit value as selector. I raised this issue at Actisense today and they will look into it and hopefully provide a fix soon.

The device instance is also configurable on the devices page, found in Settings -> Services -> VE.Can port -> Devices and then goto the device you want to change.

**Comment by DevoDave** [comment]
Fantastic. When 3.00 drops I'll give it a try.

**Comment by mpvader** [comment]
Hey @DevoDave , to add to above, the fix is included per beta version v3.00~29. Which I'll make available tomorrow.

Thank you for reporting! I assume that many people, whom are already in difficult waters when having to deal with NMEA2000 instances, will be very thankful for having this fixed.

**Comment by DevoDave** [comment]
Sweet. I'm away from my vessel for a week but that's the first job I'll do
when I return.

Thanks for hopefully fixing this.
