### ISSUE TITLE
dbus-generator: Remove distinction between generic relay-controlled and FischerPanda generators

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#912]
On dbus service `com.victronenergy.generator.startstop0` the paths are different depending on whether you're using a FischerPanda generator (CAN-bus controlled), or you are controlling it using the built-in relay.

When using a FischerPanda generator, all paths are prefixed with `/FischerPanda0`, while it is prefixed with `/Generator0` in other cases.

This distinction should be removed.

TODO:
- [x] Change dbus-generator so each module has its own service
- [x] Remove prefix on dbus paths
- [x] Update generator tracking in systemcalc
- [x] Update GUI QML
- [x] Update vrmlogger attributes
- [x] Update modbus-tcp paths 
- [x] Update dbus wiki page
- [x] It will be necessary to rebuild venus-docker; Let developers know.
- [ ] HTML5 app
- [x] Add /AutoStartEnabled path to dbus-modbustcp

Device instances:
Generic relay-controlled generators will remain on DeviceInstance=0. Since this is a breaking change for MQTT anyway, and FischerPanda paths are not accessible through modbus-tcp anyway, it is the more suitable candidate to move to DeviceInstance=1.

**Comment by kwindrem** [comment]
When this gets rolled in, please notify me as I'll need to make changes to my GeneratorConnector package due to the path changes.

kwindrem@icloud.com

**Comment by izak** [comment]
modbus-tcp will be unaffected. Everything stays in the same place.

MQTT: some paths will change.
