### ISSUE TITLE
Can’t see any topics at Mqtt analyser

### ISSUE THREAD

**Issue by testpaul999** [victronenergy/venus#917]
Hello, I have run Venus os 2.84 at one RPI.
Attached devices MPPT 100/30 and SmartShunt.
MQTT is enabled at Services, but I don’t see any topics from my devices.
![IMG_3018](https://user-images.githubusercontent.com/35597907/157299402-dc8b0b4f-59a8-4aa2-85ef-a756ba57de7a.jpeg)
That’s all what I see.
At the console I see with dubs-spy
com.victronenergy.battery.ttyUSB1
Alarms/Alarm                                                                                                                       
0Alarms/HighStarterVoltage
0Alarms/HighTemperature  
0Alarms/HighVoltage     
0Alarms/LowSoc
0Alarms/LowStarterVoltage
0Alarms/LowTemperature    
0Alarms/LowVoltage
0Alarms/MidVoltage     
… 6.69Dc/1/Voltage

So what’s happened with MQTT?
THX for Help

**Comment by mpvader** [comment]
Hi, please ask this at https://community.victronenergy.com and then the Modifications space.

thank you! I’ll close this issue. Matthijs
