### ISSUE TITLE
vebus: Add serial number(s) to dbus and log to VRM

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#922]
There is a need to be able to show the serial numbers of Multis/Quattros on VRM, on the device list.

Currently this information is not available on dbus, but since firmware 308 it is possible to obtain it. Older firmware versions return 0, which can simply be displayed as invalid on dbus.

TODO
- [x]  Add serial number readout to vebus_interface/dbus
- [x] Add the information to a suitable place in the GUI, possibly on the Device page as with other types
- [x] Log Serial numbers to VRM (to be consistent with existing practice, up to 12 serial numbers).

**Comment by vejpasop** [comment]
Implemented in mk2-dbus v3.39

On older (<308) versions the dbus path "Devices/#/SerialNumber" remains invalid

**Comment by mpvader** [comment]
Jos, Izak, can this issue be closed?
