### ISSUE TITLE
VenusOS and Epever charge controllers

### ISSUE THREAD

**Issue by e-i-k-e** [victronenergy/venus#923]
Hi,
I would like to add two Epever MPPT charge controllers to VenusOS via RS485.
I ask because there are now many drivers for other hardware and I could not find anything ready.

I can read out the charge controllers via the "Solaranzeige" project.
Maybe you could take a look at one or the other here?

Would something like this be possible with VenusOS and a Raspberry?

I suspect that a driver would have to be created. Am I in the right place here or who can I contact with my request?

Many greetings :)

**Comment by mpvader** [comment]
Hi, I'm sorry but that is not something we are going to do or help with.
