### ISSUE TITLE
Password node UI

### ISSUE THREAD

**Issue by Jsrivet** [victronenergy/venus#924]
Why when I activate the "http Node Auth" password in the settings.js file and I want to edit a Victron node I always have a password request but there is no working password. when I disable the "http Node Auth" no more password is asked. Thank you

![Capture d’écran 2022-03-29 222542](https://user-images.githubusercontent.com/75587171/160739271-ceca3530-fb53-4387-9f47-110d09a12a41.jpg)

![Capture d’écran 2022-03-29 223407](https://user-images.githubusercontent.com/75587171/160739462-62c83c5e-11ab-4874-8792-e82faeef8a65.jpg)

**Comment by dirkjanfaber** [comment]
Node RED on Venus uses the remote console password for protecting authentication, so there is not need to edit the `settings.js` file to get this to work. This is handled by the existing `adminAuth: require("/usr/lib/node_modules/node-red/user-authentication.js"),` line in there.

The username is `admin` and the password is set in the. (See also '_How can I password protect Node-RED_' on https://www.victronenergy.com/live/venus-os:large#node-red_faq )
