### ISSUE TITLE
GX / Venus OS - System - PV Yield 

### ISSUE THREAD

**Issue by Courty40** [victronenergy/venus#926]
Since the last round of updates, the Widget 'System - PV Yield' is not displaying data whereas it had previously.

![GX System Capture](https://user-images.githubusercontent.com/24435141/161504141-58f921f5-59d4-45a5-a44a-2f13d701ac81.PNG)

**Comment by mpvader** [comment]
Hi @Courty40 , thanks. I'll make sure the VRM developers are on to this. Could be they are already. I'll close this issue, as its a different tracker.

have a good day!
