### ISSUE TITLE
Em24 Raspberry Modbus rtu

### ISSUE THREAD

**Issue by blaumsass** [victronenergy/venus#934]
Wie bekomme ich eine Verbindung? Mit der Carlo Software usc7 funktioniert die Verbindung.
Wie sage ich Venus os welcher Usb Port? Ist Rs485 überhaupt implementiert?

**Comment by jhofstee** [comment]
This is an issue tracker, please ask questions at https://community.victronenergy.com/spaces/31/index.html.
