### ISSUE TITLE
/NrOfTrackers not documented for RS MPPT

### ISSUE THREAD

**Issue by kwindrem** [victronenergy/venus#935]
It appears /NrOfTrackers parameter does exist for MPPT solar chargers (aka PV chargers) as evidenced in PageSolarCharger.qml. However, this parameter is not listed in the Wiki.

Note the Wiki DOES list /NrOfTrackers for Multi RS.

If my assumption is correct, a Wiki update should be made.

**Comment by izak** [comment]
Updated. Took the opportunity to also document other missing paths for solarchargers, such as the Link parameters, settings, and DeviceOffReason(s).
