### ISSUE TITLE
VE.Bus: BMS V1 BMS error path toggles between invalid and error when Multi is switched off

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#938]
From Venus V.280 VE.Bus BMS info is reported while Multi is switched off.
In case of a BMS V1 the BMS can not be detected since it powers off along with the Multi. The BMS error path is set as a result.
However this path alternates between invalid and true every ~2 seconds.

Todo:

- [x] Fix in mk2-dbus

**Comment by SturmUDrang** [comment]
Hi! I reported this issue, happy to see that is has been confirmed as a bug. Do you have an ETA for this fix? If not yet, can you tell me if reverting to any pre 2.80 release would be a temp soution?

**Comment by vejpasop** [comment]
Fixed in mk2-dbus V3.38
