### ISSUE TITLE
Venus USB connection to Victron control

### ISSUE THREAD

**Issue by sanitariu** [victronenergy/venus#944]
Hello,
Is it possible using that OS to control my Victron Multiplus Inverter ? Actually i would like only one thing ! Force by my command the inverter to switch from batteries to main AC grid.
Is this possible ?
I want this gentle not turning off all loads ... just switch like when battery is low.

**Comment by mpvader** [comment]
Same thing, sorry but please go to your distributor or to community.victronenergy.com. Thank you!
