### ISSUE TITLE
Venus OS on a Multiplus Compact 1200VA

### ISSUE THREAD

**Issue by sanitariu** [victronenergy/venus#945]
Hello,
I have Multiplus Compact 1200VA. Currently I have MK2 usb device for setting it up. Can I use this venus os ?

Regards,
Todor

**Comment by mpvader** [comment]
Hi, can you please go to https://community.victronenergy.com, or to your distributor?

this issue tracker is not for customer support.

thank you. Matthijs

**Comment by sanitariu** [comment]
Hello,
I thought  question was simple enough :) Does your project support MK2 USB device from victron ?

**Comment by mpvader** [comment]
Hi, this project from Victron. Answer is no: you need a MK3-USB.

But please, for any followup, not here. We use this to manage software development
