### ISSUE TITLE
Support Mopeka

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#946]
Work mostly done; needs testing and inclusion. Currently awaits Mopeka devices to test with.

**Comment by mansr** [comment]
I am working on it. There was a bit more left to do than it appeared at first.

**Comment by damonblumenstein** [comment]
> 

Great to hear!  Are you thinking a month or 2?

**Comment by riprock67** [comment]
Thanks for the work! Any updates?

**Comment by mansr** [comment]
The Mopeka support has been merged and will be in the next release candidate.

**Comment by riprock67** [comment]
Thanks again for the hard work!

**Comment by damonblumenstein** [comment]
Is this going to support all of the sensor types or only a specific one?
I.e. the origial series or just the new pro series?

**Comment by mansr** [comment]
Only the Pro sensors are supported for now.
