### ISSUE TITLE
Separate SDCard Logging settings from VRM Online Portal settings

### ISSUE THREAD

**Issue by greendrake** [victronenergy/venus#949]
Currently the feature of logging data to SDCard resides in / is tied to the VRM Online Portal settings area (v 2.85):

![Screenshot from 2022-05-19 14-33-20](https://user-images.githubusercontent.com/1991299/169192322-4ef73dc0-b5ab-4dd6-8d79-44bb91bcf1b8.png)
![Screenshot from 2022-05-19 14-33-39](https://user-images.githubusercontent.com/1991299/169192340-915802d2-b2e4-498a-a31e-2fde7743a3ea.png)

This appears to be an issue when the user does _not_ want to use VRM at all but still wants data to be logged to SDCard.

Currently I have to simply deny the device access to the Internet via local network firewall. The proposed solution is to move the SDCard logging settings out of the scope of VRM settings.

As a side note, it would also help to have all VRM settings in one place or have a single switch "Disable VRM altogether". Currently, there seem to be 2 separate ways of how the device can talk to VRM: logging as above, and Remote Console setting:

![Screenshot from 2022-05-19 14-39-12](https://user-images.githubusercontent.com/1991299/169193121-c2908fd9-4486-4a0e-97b5-d027b7c85b70.png)

So, if a user wants to prevent the device from trying to talk outside he/she has to disable _both_ VRM Logging and Remote Console on VRM, and maybe something else I have missed?

**Comment by jhofstee** [comment]
Your are misunderstanding this feature, the sd-card can be used as backup.

**Comment by greendrake** [comment]
> the sd-card can be used as backup.
That's what I use it for — to save ("backup") data about the battery state, load, solar power etc. But I don't need to feed it to VRM. How can I backup it without feeding to VRM?

**Comment by jhofstee** [comment]
I understand what you want, but that is a feature request not an issue. I will discuss how we can handle feature requests, but I would like like to keep this issue tracker for bugs / things we need to do. Not for possible new features, since it will explode if we start doing that.
