### ISSUE TITLE
mk2-dbus: reduce # of signals being published to D-Bus

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#95]
To reduce the load on the dbus.

- [x] mk2-dbus: Remove the /S paths, nobody uses them.
- [x] mk2-dbus: Don't publish the Hub4/ESS set point back (but keep a commandline flag to re-enable this for debugging hub4 / ess systems)
- [x] Double check that this doesn't break hub4control: it does, and hub4control has been updated for this.

Rest of the dbus users:
- vrmlogger doesn't break if they are not there
- GUI doesn't use them (perhaps some debug function breaks though?)
- dbus-generator doesn't use them.
- mqtt: not relevant
- ModbusTCP: not relevant

**Comment by vejpasop** [comment]
mk2-dbus v2.41 solves the above.

**Comment by mpvader** [comment]
@edevries-victron up to you now to make sure the rest of the system still works.

**Comment by mpvader** [comment]
Fixed, will be in v2.00~16

**Comment by mpvader** [comment]
@edevries-victron: I added 'Rest of the dbus users' section in above top comment. You agree with those?

(To prevent forgetting a dependency)

**Comment by edevries-victron** [comment]
@mpvader  I agree. One exception however:
ModbusTcp support reading and writing the Hub-4 setpoint. Reading the setpoint in v2.00~16 will not give the latest setpoint. I don't think this is a problem, because it is better to read the AC-In power instead of the setpoint itself.
