### ISSUE TITLE
Wish: Library for Pimoroni Automation Hat

### ISSUE THREAD

**Issue by runout0** [victronenergy/venus#952]
Hi, is it possible to adapt this Library "https://github.com/pimoroni/automation-hat" to the Venus Image?
That Library is for Debian-based S (apt/apt-get) and fails while install procedure.

complete info here: https://learn.pimoroni.com/article/getting-started-with-automation-hat-and-phat

**Comment by mpvader** [comment]
Hi, possibly/probably. Could you please post that in the Modifications space on https://community.victronenergy.com/ ?

You'll have more chance there in finding someone that can help you with that.
