### ISSUE TITLE
Installation Documentation - unzip the .wic.gz file?

### ISSUE THREAD

**Issue by amas008** [victronenergy/venus#956]
In the Instructions (below), it says we need to unzip the .wic.gz file, but then it says we need to burn the original .wic.gz file. I assume the "unzip" it instruction is incorrect?

Getting started:
Download the latest image, a .wic.gz file from [here](https://updates.victronenergy.com/feeds/venus/release/images/raspberrypi2/), and for the raspberrypi4, go up one folder and select the raspberrypi4 subfolder.
**Unzip it.**
Get an sdcard, put it in your computer.
Burn the image file (.wic.gz) on an sdcard. On windows, use win32diskimager or balenaEtcher.
Insert the sdcard in the raspberry pi.

Thanks for a great project.

**Comment by mpvader** [comment]
Hi, thanks for closing reading those instructions! I've removed the "unzip it"  step from the list. Its not necessary indeed.
