### ISSUE TITLE
Add new tank types

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus#958]
Since we are going to support inbound tank data from RV-C, we also need to support LPG tank types, as this is part of the RV-C spec. The tank types currently supported in VenusOS map directly to NMEA2000 fluid types. However, N2K is missing support for LPG. Hence we submitted a request and they came up with the following new tank types:
- 0x07 = Diesel
- 0x08 = Liquid Petroleum Gas (LPG)
- 0x09 = Liquid Natural Gas (LNG) 
- 0x0A = Hydraulic Oil
- 0x0B = Raw Water

_Do note that these values are currently still pending for approval, scheduled to be published at June 28th 2022, if unchallenged._

Both tank types need to be added to Venus, to the following services:
- [x] dbus-rv-c (mbo)
- [x] gui
   - [x] tank setup page (mbo)
   - [x] tank overview (mbo)
   - [x] icons (jpe)
- [x] vrm-logger/vrm - add to enum (ibu)
- [x] modbus-tcp - add to enum (ibu)
- [x] node-red - (dfa)
- [x] dbus-adc (mbo)

**Comment by kwindrem** [comment]
Suggest adding galley waste water tank also. Many RVs at least in the US have two gray water tanks and without naming capability (e.g., SeeLevel N2K) you can't tell the difference.
