### ISSUE TITLE
GUI: new Ve.Bus state, External control, is too long to fit in the box

### ISSUE THREAD

**Issue by weichenb** [victronenergy/venus#960]
On GX web-frontend the mode "Externe Steuerung" is not properly displayed.
Either a line break is required or expression has to be shortened.
![grafik](https://user-images.githubusercontent.com/106034560/173179276-5fd34ca9-2b28-469e-a6f4-c0433d0586a2.png)
Issue reproduced on Firefox, Edge and Chrome

**Comment by mpvader** [comment]
Hi @weichenb , yes we noticed the same. It will be fixed shortly. Thanks!

**Comment by mpvader** [comment]
Hi @jepefe could you make sure that this is done (if not done already).

This state, Ext. Control, is a new one for the VE.Bus devices.

**Comment by jepefe** [comment]
Translations were checked and where necessary changed to fit in the spot.
