### ISSUE TITLE
dbus_modbustcp: extra /System/ fields for ESS systems

### ISSUE THREAD

**Issue by dirkjanfaber** [victronenergy/venus#963]
In order to give the end user more information, I'd like to have the following fields added to dbus_modbustcp and node-red-contrib-victron.

```
com.victronenergy.battery

- /System/MaxCellTemperature
- /System/MaxCellVoltage
- /System/MaxTemperatureCellId
- /System/MaxVoltageCellId
- /System/MinCellTemperature
- /System/MinCellVoltage
- /System/MinTemperatureCellId
- /System/MinVoltageCellId
- /System/NrOfModulesBlockingCharge
- /System/NrOfModulesBlockingDischarge
- /System/NrOfModulesOffline
- /System/NrOfModulesOnline
```
To be added to:
- [x] dbus_modbustcp (ibu)
- [x] node-red-contrib-victron (dfa)

**Comment by jhofstee** [comment]
oh please don't do this.. This assumes there is a single battery.

**Comment by izak** [comment]
You will have to explain it to me. If there are multiple CAN-bms batteries, they each get their own DeviceInstance and therefore their own Modbus slave address. And where there are multiple modules in a battery, the point is exactly that we want to know which module has the low/high cell, or how many modules are online/offline/blocking. I struggle to see how it would be affected by multiple batteries or modules?

Many of the mentioned items were already on modbus as well, and especially the online/offline/blocking items are extremely useful.

**Comment by jhofstee** [comment]
> oh please don't do this.. This assumes there is a single battery.

Ah right, nevermind. I was in the impression you wanted systemcalc to handle this, not the BMS service itself.

**Comment by dirkjanfaber** [comment]
Added to node-red-contrib-victron in https://github.com/victronenergy/node-red-contrib-victron/releases/tag/v1.4.21.
