### ISSUE TITLE
i2c and related overlays

### ISSUE THREAD

**Issue by smurfix** [victronenergy/venus#964]
Hello,

could you please build and/or ship various "standard" `.dtb` files?

Specifically, I want to use a lifepo4wered.com battery with my Venus-ized Raspberry Pi, but the device cannot be used without talking to it via i²c.

**Comment by mpvader** [comment]
Hi @smurfix , sorry but no; we will not get into that.

You can however build dtb files yourself. The kernel is available on github; as are the parameters that we use to build it (encoded in the relevant OE recipes).
