### ISSUE TITLE
pi Venus 2.9 install Touch Screen won't work (MPI3501 ILI9486 320x480 LCD)

### ISSUE THREAD

**Issue by mvdh02** [victronenergy/venus#966]
I've followed the instructions on the "pi Venus  install Touch Screen (MPI3501 ILI9486 320x480 LCD)".  And everything likes to go good, until the "run calibration".  "ts_calibrate".  It's says "not found". What am i doing wrong.

The display is perfect working on a Raspberry Pi OS without a problem.

**Comment by mpvader** [comment]
Hi, for support on raspberrypis, please use https://community.victronenergy.com/spaces/31/mods.html.

Thanks!
