### ISSUE TITLE
vrmlogger: add VE.Bus temp. sense & volt. sense alarms

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#97]
These alarms have always been on the dbus, but we never showed them. 

Somewhere in v2.00 they were already added to the gui. 

All thats left now is to also add them to vrmlogger.

See also https://git.victronenergy.com/mirrors/venus/issues/16

**Comment by edevries-victron** [comment]
/Alarms/TemperatureSensor and /Alarms/VoltageSensor were added to vrmlogger in v2.64 (released with CCGX 2.01~5).

**Comment by jhofstee** [comment]
thanks, closing the issue then..
