### ISSUE TITLE
BMV-712 issues with connection

### ISSUE THREAD

**Issue by DannyAt** [victronenergy/venus#972]
Hey, Any ideas why this is timing out?

root@raspberrypi4:/service/vedirect-interface.ttyUSB0# ./run
vedirect-dbus 3.68

-------- dumping backlog -------
030.088 INF.VE.Text: SOC=993
030.088 INF.VE.Text: TTG=14400
030.088 INF.VE.Text: ALARM=OFF
030.105 INF.VE.Text: RELAY=ON
030.105 INF.VE.Text: AR=0
030.105 INF.VE.Text: BMV=712 SMART
030.116 INF.VE.Text: FW=0408
030.116 INF.VE.Text: MON=0
030.507 INF.service: 0x4248c: sending 5 :154

030.542 INF.VE.Text: H1=-146837
030.542 INF.VE.Text: H2=-1647
030.559 INF.VE.Text: H3=-106456
030.559 INF.VE.Text: H4=3
030.559 INF.VE.Text: H5=0
030.559 INF.VE.Text: H6=-1649393
030.575 INF.VE.Text: H7=26
030.575 INF.VE.Text: H8=15116
030.575 INF.VE.Text: H9=13309
030.575 INF.VE.Text: H10=11
030.592 INF.VE.Text: H11=0
030.592 INF.VE.Text: H12=0
030.592 INF.VE.Text: H15=-674
030.609 INF.VE.Text: H16=15158
030.609 INF.VE.Text: H17=2156
030.609 INF.VE.Text: H18=3176
031.002 ERR.values: timeout connecting device
031.002 INF.task: done in 031.002

**Comment by mpvader** [comment]
Hi, my first guess is that your RX is working, but TX is not. For more, please post on the Modifications section on Community. This issue tracker is not for support.

thank you.
