### ISSUE TITLE
Low amperage charging broken

### ISSUE THREAD

**Issue by smurfix** [victronenergy/venus#973]
Consider a setup with a MultiPlus (or three), a battery, and a bunch of chargers.

Sometimes a battery is nearly full and needs to *not charge*, or to charge with a really low amperage (e.g. top balancing). On the other hand you don't want to waste energy and would like to feed the surplus to the grid instead of setting all your chargers to zero.

This is currently impossible. In my setup, setting the charge current to zero in DVCC results in ~4.5A of charge on average, which is too much for my BMS. As my solar capacity is also too large for three Multis to transfer to the grid in real-time, this results in an overcharged battery and a tripped battery relay.

This effect is not surprising given the fact that all DC current measurements would have to be ~0.2% correct for this to work, which is not realistic.

I propose that dbus-systemcalc-py should monitor the battery current, compare the actual value to the DVCC settings,and adjust the current it asks the solar chargers to deliver accordingly. As a side effect this would also allow us to deal with battery chargers and loads that don't talk to Venus/GX.

**Comment by mpvader** [comment]
discussed on community here: https://community.victronenergy.com/questions/150732/multiplusess-battery-current-doesnt-go-to-zero-whe.html.

closing.
