### ISSUE TITLE
Temporary overcharging when /hub/Lx/AcPowerSetpoint is increased

### ISSUE THREAD

**Issue by smurfix** [victronenergy/venus#974]
Given an ESS system with active charging and a running grid feed.

Consider what happens when the grid feed is reduced (i.e. `AcPowerSetpoint` goes from very-negative to zero-or-just-somewhat-negative). The current to the Multiplus(es) stops and goes into the battery instead, possibly exceeding the DVCC limits arbitrarily, until dbus-systemcalc-py notices and reduces the solar charger's max current appropriately.

This is backwards and potentially trips the battery safety relay if the thing is too small to take the solar array's full power.

Thus I propose that setting `/Hub4/Lx/AcPowerSetpoint` should be mediated by DVCC, i.e. reduce solar power feed-in first and *then* reduce grid feed-out.

NB: Yes I know, the same thing happens when there's a power failure, in which case this method is not available. However there's lots of countries where power failures basically don't happen; on the other hand, around here when you feed to the grid you have to prove to your utility company that you can stop, and restart, your feed on demand. Not a good idea if the battery is full.

**Comment by mpvader** [comment]
Hi, I'm pretty sure this can be closed as well, like the other one: as long as the BMS properly manages its voltage, current is not going in batteries.

And even if its not: making the proposed change further complexifies the whole setup, potentially adding other issues either now or later, while it already works fine now for a huge number of systems out there (Pylon, BYD, MG, etc etc).
