### ISSUE TITLE
Flows missing in NR after upgrade to v2.90~27 large ?

### ISSUE THREAD

**Issue by houser42** [victronenergy/venus#978]
Upgraded 4 systems to Venus OS large to `v2.90~27` today.
I system ok, but 3 of the 4 systems came up without flows in Node Red after reboot.
Reverting back to v2.90~26 also shows flows missing.
Anyone else seeing this? Hoping for a fix?
Many thanks!

**Comment by mpvader** [comment]
yes, but lets keep the discussion in one place: modifications section on Community. I'll post what will happen there now.

(its being fixed)
