### ISSUE TITLE
File not found (serial-starter)

### ISSUE THREAD

**Issue by fynnsh** [victronenergy/venus#981]
Hello,

i installed Venus via the apt repo on my PI (https://updates.victronenergy.com/feeds/venus/candidate/packages/raspbian-buster/) and always i get an error that i cant start the vedirect interface because of a lack of the file /opt/victronenergy/serial-starter/run-service.sh. I cant find that file anywhere or in any dokumentation. Is this source working? Or is there any tested source for Debian / PI. And also is there anywhere any GPG Key?

Thanks

**Comment by mpvader** [comment]
Hi @fynnsh , this tracker is for development, not support.

Please can you ask your question here:

https://community.victronenergy.com/spaces/31/mods.html

?

Thanks. matthijs
