### ISSUE TITLE
vrmlogger: Cerbo and EasySolar sends CPU temperature every ten seconds

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#983]
Due to a change in vrmlogger, released in Venus 2.90, a Cerbo/Nanopi with a CPU temperature that fluctuates may end up posting to VRM every ten seconds.

CPU temperature posting should be done only on interval.

The way filemonitors (as opposed to the usual dbus path monitoring) are structured makes it more difficult to limit to interval only, therefore it might be easier to move the temperature reading to another process (such as systemcalc) and monitor the temperature in the usual manner.

TODO
- [x] For Venus 2.91, simply disable it. Then if we decide to keep it...
- [ ] Implement temperature check (where supported) in systemcalc
- [ ] Change vrmlogger to log temperature OnIntervalOnly

**Comment by mpvader** [comment]
In v2.91, the logging of cpu temperature was removed. closing this.
