### ISSUE TITLE
DVCC: Make it possible to use SVS with FreedomWon batteries

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#984]
Previously we opted to force good settings for batteries, including FreedomWON. SVS=off works best in most cases, so that is what we forced, but the manufacturer has now advised as that they'd like the ability to use it in some cases.

Therefore, stop forcing SVS for all FreedomWON batteries (Lite as well as eTower).

In systems where it is already forced-OFF, after an update it will remain off, but you will have the option of turning it on in cases where that might be beneficial.

**Comment by mpvader** [comment]
Implemented in v2.91~1
