### ISSUE TITLE
DVCC ESS not working rpi4

### ISSUE THREAD

**Issue by realJoelbiten** [victronenergy/venus#985]
DVCC current limit and/or voltage limits is ignored. 

ESS charge limits is ignored.

Setup
3 multiplus 2 in 3phase setup. 

RPI4 8GB 1.4 connected via Mk3 USB.

Leaf DIY powerwall, no BMS integrations.

OS version Beta 2.91-1 

Same setup worked with DVCC with Cerbo GX.

**Comment by mpvader** [comment]
Hi, sorry to hear you're having issues! To get helped, please ask on the modifications section on Community, which is here: https://community.victronenergy.com/spaces/31/mods.html.

This issue list is for development only; thanks!
