### ISSUE TITLE
DVCC: Control only the Multi on the built-in port

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#988]
This is for systems with more than one Multi/Quattro connected.

Presently the Multi with the lowest Device Instance that is switched on is controlled by DVCC. This is always the built-in VE.Bus port, which is a good thing.

This means that if you more than one Multi connected, and you turn off the "main" unit, DVCC starts controlling the second Multi. This is not really what you want.

Furthermore, if you later turn on the "main" Multi again, DVCC stops controlling the second multi and starts controlling the first Multi again. This will cause the second Multi to go into passthru, or switch off. Also not really what you want.

Finally, none of this is properly communicated to the user either.

Suggestion.
- [x] One devices with a built-in mk2/mk3, only use the built-in port for DVCC
- [x] On other devices, stick with the existing method of using the first one (lowest device instance).

**Comment by izak** [comment]
@warwickchapman , conversely we also have people with boats with multiple battery banks which may not even be of the same voltage. If I make you happy, I make them decidedly unhappy.

The point of this issue is to have a well defined state of operation. The present implementation is to control only one Multi, and changing that is a big departure. Flopping control back and forth between two Multis is however a problem that must be fixed, and the target of this issue.

Maybe in future we'll look into something like that again, but right now you will probably have to use Node-Red or similar to do it.

**Comment by mpvader** [comment]
All done, adding the documentation part of this to the v3.00 documentation issue.
