### ISSUE TITLE
VE.Bus BMS v2: Pre-alarm to VRM, GUI

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#989]
The Pre-alarm for VE.Bus BMS v2 is available on dbus, but is not used anywhere nor shown to the user.

It should at least be logged to VRM, and probably shown on the "Alarm Status" page on the GUI.

TODO
- [x] Log to VRM
- [x] Add to modbus
- [x] Show on GUI

**Comment by mpvader** [comment]
@izak does this work in VRM, ie can you post a screenshot here of a pre alarm showing up as an entry in the VRM alarm log?

and can you make the required change in the gui code?

**Comment by izak** [comment]
After a quick discussion with @vejpasop , we're going to make this an alarm so that it will show up in the Alarm log. At present it does not.

The dbus path changes tor consistency, so a vrmlogger update will also be required. Already requested a change in VRM as well.

**Comment by vejpasop** [comment]
I added `Alarms/BmsPreAlarm ` the state of this can be 0 = OK, 1 = WARNING

Now when this pre alarm is active the Multi will also report al low battery warning. (`Alarms/LowBattery` = WARNING)

**Comment by vejpasop** [comment]
Implemented in mk2-dbus v3.51
