### ISSUE TITLE
How to install Venus OS on ubuntu?

### ISSUE THREAD

**Issue by mrgithub** [victronenergy/venus#992]
How do I install venus os on my linux machine. I want to be able to connect my old laptop to my shiny new Victron rig. How do I do that? I'm hoping in future I can go buy a USB stick and connect it the VE functions etc.

**Comment by mpvader** [comment]
Hi, that won't work; at least I don't see how.

For further questions, please go to https://community.victronenergy.com/spaces/31/mods.html

This issue tracker is not for support.

Thanks!
