### ISSUE TITLE
No WiFi/Bluetooth on Raspberry Pi Zero 2W

### ISSUE THREAD

**Issue by bagges** [victronenergy/venus#993]
After boot with latest stable release no wifi and bluetooth connection is possible. Menu just shows: no wifi adapter

Image: Large v2.92
Board: Pi Zero 2W

Reference: https://community.victronenergy.com/questions/144249/no-wifi-on-pi-zero-2w-venus-os-v29016-and-14.html

To fix the issue I did the following steps:

```
git clone https://github.com/RPi-Distro/bluez-firmware.git
git clone https://github.com/RPi-Distro/firmware-nonfree.git
cp bluez-firmware/broadcom/BCM43430B0.hcd <mountpoint>/lib/firmware/brcm/
cp firmware-nonfree/debian/config/brcm80211/brcm/brcmfmac43436* <mountpoint>/lib/firmware/brcm/
cd <mountpoint>/lib/firmware/brcm/
ln -s BCM43430B0.hcd BCM.hcd
```

**Comment by jhofstee** [comment]
Please don't post such issues here, the RaspberryPi is community supported, please post it there.
